//exported from doodads.slk
export const doodatCodes = {
    APms: "Mushrooms",
    AOhs: "Hollow Stump",
    APtv: "Thorny Vines",
    APct: "Cattail",
    AObd: "Birds",
    AObr: "Skull Brazier",
    AWfs: "Fish",
    AOgs: "Guardian Statue of Aszune",
    AOks: "Keeper Statue",
    AOlg: "Straight Log",
    AOla: "Angled Log",
    AOob: "Glowing Obelisk",
    AOsk: "Obelisk",
    AObo: "Broken Obelisk",
    AOsr: "Scorched Remains",
    APbs: "Bush",
    AWlp: "Lily Pads",
    AWfl: "Floating Lily Pads",
    ARrk: "Rocks",
    ASbc: "Broken Column",
    ASbr: "Black Ruined Rubble",
    ASHB: "Ruined Blocks",
    ASra: "Archway",
    ASr1: "Archway",
    ASwt: "World Tree",
    BPca: "Cactus",
    BObo: "Bones",
    BOct: "Totem",
    BOth: "Throne",
    BOtt: "Totem",
    BRcr: "Crater",
    BRfs: "Fissure",
    BRrk: "Rocks",
    BRrp: "Pillar of Rock",
    BRrs: "Rock Spires",
    BRrc: "Rock Spires (Cinematic)",
    BRsp: "Small Rock Spires",
    BRgs: "Geyser",
    BSar: "Ruined Arch",
    BSra: "Archway",
    BSr1: "Archway",
    BSrc: "Ruined Chunk",
    BSrv: "Ruined Curved Wall",
    BSrw: "Ruined Wall",
    CObl: "Blighted Mist",
    COhs: "Hollow Stump",
    COlg: "Straight Log",
    COla: "Angled Log",
    COob: "Obelisk",
    CObo: "Broken Obelisk",
    CPbs: "Bush",
    CPct: "Cattail",
    CPms: "Mushrooms",
    CPlp: "Lily Pad",
    CRfs: "Fissure",
    CRrs: "Rock Spires",
    CSbc: "Broken Column",
    CSbr: "Black Ruined Rubble",
    CSbl: "Ruined Blocks",
    CSra: "Archway",
    CSr1: "Angled Archway",
    LPcr: "Corn",
    LPfp: "Floating Lily Pads",
    LPlp: "Lilly Pad",
    LPrs: "River Rushes",
    LPwb: "Wheat Bunch",
    LPwh: "Wheat",
    LPcw: "Scorched Grain",
    LOar: "Archery Target",
    LOam: "Armor Rack",
    LOh1: "Human Banner",
    LOo1: "Orc Banner",
    LOo2: "Tutorial Orc Banner",
    LObr: "Brazier",
    LObz: "Glowing Brazier",
    LOce: "Empty Cage",
    LOca: "Cauldron with Heads",
    LOct: "Empty Cage",
    LOfl: "Flies",
    LOgr: "Grave",
    LOhb: "Hay",
    LOch: "Hay Cart",
    LOcb: "Broken Hay Cart",
    LOrc: "Hay Cart Infected",
    LOxx: "Broken Hay Cart Infected",
    LOhc: "Hay Clump",
    LOsh: "Head on Spear",
    LOhp: "Hitching Post",
    LOic: "Impaled Corpse",
    LOlp: "Lantern Post",
    LOpg: "Peasant Grave",
    LOrb: "Rib Bones",
    LOrh: "Hay (Infected)",
    LOsp: "Sign Post",
    LOsc: "Sitting Corpse",
    LOss: "Skulls on Stick",
    LOsk: "Skull Pile",
    LOsm: "Smoke Smudge",
    LOsw: "Stone Wall",
    LOth: "Torch",
    LOtz: "Glowing Torch",
    LOt1: "Trash",
    LOtr: "Trough",
    LOwb: "Wheelbarrel",
    LOwr: "Broken Wheelbarrel",
    LOwp: "Weapon Rack",
    LRrk: "Rocks",
    LSba: "Barn",
    LSeb: "Elven Building",
    LSsb: "Scorched Barn",
    LSsf: "Scorched Farm",
    LSgr: "Granary",
    LSgs: "Scorched Granary",
    LSin: "Inn",
    LSra: "Rock Archway",
    LSr1: "Angled Rock Archway",
    LSsi: "Scorched Inn",
    LSst: "Scorched Tower",
    LSwl: "Well",
    LSwb: "Burned Wind Mill",
    LSwm: "Wind Mill",
    NObc: "Broken Column",
    NObk: "Broken Obelisk",
    NObo: "Bones",
    NOfl: "Fence",
    NOal: "Angled Fence",
    NOgv: "Stone Grave",
    NOok: "Obelisk",
    NOtb: "Tombstone",
    NWfb: "Floating Box",
    NWfp: "Floating Plank",
    NWf1: "IceFloe",
    NWf2: "IceFloe",
    NWf3: "IceFloe",
    NWf4: "IceFloe",
    NWi1: "Iceberg",
    NWi2: "Iceberg",
    NWi3: "Iceberg",
    NWi4: "Iceberg",
    NWpa: "Floating Panel",
    NOfp: "Fire Pit",
    NOfg: "Fire Pit w/ Pig",
    NOft: "Trashed Fire Pit",
    NObt: "Bats",
    NWrw: "Rowboat",
    NWrd: "Destroyed Rowboat",
    NWsp: "Ship",
    NWsd: "Destroyed Ship",
    NWwh: "Whale",
    NPth: "Thorny Vines",
    NRfs: "Fissure",
    NRic: "Ice Claws",
    NRrk: "Rocks",
    NRwr: "Webbed Rocks",
    NSct: "Crypt",
    NSra: "Archway",
    NSr1: "Angled Archway",
    NSrb: "Rubble",
    VOfl: "Long Fence",
    VOal: "Angled Long Fence",
    VOfs: "Short Fence",
    VOas: "Angled Short Fence",
    VSvb: "Building",
    YObb: "Long Blue Banner",
    YOwb: "Long White Banner",
    YObs: "Stone Bench",
    YOsa: "Angled Stone Bench",
    YOsb: "Alonsus Chapel",
    YOmb: "Alonsus Chapel",
    YOms: "Clock Tower",
    YOm1: "Market Stall Small",
    YOm2: "Market Item Baubles",
    YOm3: "Market Item Baubles (Alt)",
    YOm4: "Market Item Produce",
    YOm5: "Market Item Produce (Alt)",
    YOm6: "Market Item Textiles",
    YOm7: "Market Item Textiles (Alt)",
    YObw: "Wood Bench",
    YOwa: "Angled Wood Bench",
    YOfn: "Fountain",
    YOgr: "Grave",
    YOob: "Obelisk",
    YOlp: "Lantern Post",
    YOst: "Statue",
    YOks: "Shieldless Statue",
    XOcs: "Power Generator",
    XOcl: "Magical Lantern",
    XOmr: "Magical Runes",
    YOts: "Tavern Sign",
    YObg: "Bob's Guns Sign",
    YOta: "Tracey's Armory Sign",
    YOec: "Empty Crates",
    YOth: "Throne",
    YOws: "Whale Statue",
    YOss: "King Terenas Statue",
    YOig: "Iron Gate (A)",
    YOi1: "Iron Gate (B)",
    YPbs: "Bush",
    YPtp: "Tree Planter",
    YPfs: "Straight Flower Bed",
    YPfa: "Angled Flower Bed",
    YPpp: "Potted Plant",
    YSaw: "Archway",
    YSa1: "Angled Archway",
    YSa2: "Archway Entrance",
    YSa3: "Angled Archway Entrance",
    YSca: "Cathedral",
    YSco: "Single Column",
    YScd: "Double Column",
    YSc5: "Double Column 45",
    YScs: "Column Semi Circle",
    YSc2: "Column Semi Circle2",
    YSc3: "Column Semi Circle3",
    YSc4: "Column Semi Circle4",
    YSls: "Short Wall End",
    YSw0: "Low Wall",
    YSw1: "Low Wall",
    YSw2: "Low Wall",
    YSw3: "Low Wall",
    YSw4: "Wall Corner",
    YSw5: "Wall Endcap",
    YSw6: "Wall Staright",
    YSw7: "Wall Corner",
    YSw8: "Wall Straight Long",
    YSw9: "Wall Straight Short",
    YSwA: "Wall Straight Tee",
    YSwB: "Wall Straight Tee (Alt)",
    YSwC: "Wall Entrance",
    YSwD: "Wall Door",
    YSwE: "Wall Door (Short)",
    YSlt: "Tall Wall End",
    YSll: "Lantern Wall End",
    YSta: "Tavern",
    COdf: "Dead Fish",
    CRrk: "Rocks",
    DRrk: "Rocks",
    YOlb: "Lightning Bolt",
    YOtf: "Fire",
    YOfb: "Blue Fire",
    YOfs: "Small Fire",
    YOf1: "Side Fire Trap",
    YOf2: "Fire Trap",
    YOf3: "Fire Gust",
    YOr1: "Side Frost Trap",
    YOr2: "Frost Trap",
    DSar: "Archway",
    DSa1: "Angled Archway",
    DSah: "Stone Archway",
    DSa2: "Stone Archway",
    DOtp: "Pile of Treasure",
    DOjp: "Pile of Junk",
    DOch: "Chains",
    DOcp: "Chain Post",
    DRfc: "Fiery Crater",
    DRst: "Stalagmite",
    DOlc: "Lava Cracks",
    DOcr: "Chair",
    DObh: "Bench",
    DObk: "Bookshelf",
    DOkb: "Large Bookshelf",
    DObw: "Long Bookshelf",
    DOab: "Angled Bookshelf",
    DOob: "Obelisk",
    DOtb: "Table",
    DOtc: "Table and Chair",
    DOim: "Iron Maiden",
    DOtt: "Torture Table",
    DOmc: "Mine Cart",
    DOme: "Empty Mine Cart",
    DSp0: "Barred Wall",
    DSp9: "Barred Wall",
    GPsh: "Blue Mushroom",
    GRrk: "Rocks",
    GRfc: "Fiery Crater",
    GRst: "Stalagmite",
    GOob: "Obelisk",
    GSah: "Stone Archway",
    GSa2: "Stone Archway",
    GSar: "Archway",
    GSa1: "Archway",
    GSp0: "Barred Wall",
    GSp9: "Barred Wall",
    GOlc: "Lava Cracks",
    LWw0: "WaterfallEffect",
    LCc0: "Cave0",
    LCc2: "Cave2",
    YOsw: "Sun Well",
    YOcp: "Camera Prop",
    YS00: "City Building",
    YS01: "City Building",
    YS02: "City Building",
    YS03: "City Building",
    YS04: "City Building",
    YS05: "City Building",
    YS06: "City Building",
    YS07: "City Building",
    YS08: "City Building",
    YS09: "City Building",
    YS10: "City Building",
    YS11: "City Building",
    YS12: "Large City Building",
    YS13: "Large City Building",
    YS14: "Large City Building",
    YS15: "Large City Building",
    YZef: "Energy Field",
    LZth: "Thrall's Hut",
    ZObz: "Ruins Brazier",
    ZOst: "Ruins Statue",
    ZOsb: "Ruins Broken Statue",
    ZOss: " Ruins Stones",
    ZSar: "Archway",
    ZSa1: "Archway",
    ZSas: "Archway",
    ZSs1: "Archway",
    ZSab: "Ruined Archway",
    ZSb1: "Ruined Archway",
    ZWfs: "Green Fish",
    ZWsf: "School of Fish",
    ZSrb: "Ruins",
    ZOfo: "Ruins Fountain",
    ZOob: "Ruins Obelisk",
    ZOrt: "Ruins Throne",
    IRrk: "Rocks",
    ZOrp: "Ruins Pillar",
    ZOsh: "Shells",
    YCc1: "CityCliffCave1",
    YCc2: "CityCliffCave2",
    YCc3: "CityCliffCave3",
    YCc4: "CityCliffCave4",
    YCd1: "CityCliffCollapse1",
    YCd2: "CityCliffCollapse2",
    YCd3: "CityCliffCollapse3",
    YCd4: "CityCliffCollapse4",
    ZOrc: "Ruined Crystal Tower",
    ZOdt: "Ruined Tower",
    ZOd2: "Ruined Tower",
    ZOrb: "Ruined Tower Base",
    ZOtb: "Ruined Double Base",
    ZOt2: "Ruined Double Base",
    ZOvr: "Ruined Violet Citadel",
    ZOfp: "Ruins Firepot",
    ZRrk: "Rocks",
    ZCv1: "Cliffside Vines",
    ZCv2: "Cliffside Vines",
    ZWsw: "Seaweed",
    ZWbg: "Bubbles",
    IWbg: "Steam Bubbles",
    IWie: "Floating Ice",
    IWw0: "Icy Waterfall Effect",
    ZPfw: "Flowers",
    ZPsh: "Shrub",
    ZPlp: "Lilypad",
    ZPru: "CatTail",
    ZWcl: "Coral",
    ZWca: "Coral Arch",
    ZZdt: "Demonic Footprints",
    IOst: "Skull Torch",
    ISar: "Ice Archway",
    ISa1: "Ice Archway",
    IOob: "Obelisk",
    IOpr: "Pillar",
    IRic: "Ice Block",
    DOas: "Statue of Azshara",
    IOsm: "Snowman",
    ZRrs: "Rock Spires",
    ZRsp: "Small Rock Spires",
    ORrk: "Rocks",
    ORrs: "Rock Spires",
    IOss: "Ice Spider on Pedestal",
    IOsl: "Ice Spider Statue",
    AZrf: "Ruined Ship",
    OPop: "Plants",
    IRgc: "Glacier",
    ORmk: "Magma Rock",
    YCx1: "RuinedFloor2x2_",
    YCx2: "RuinedFloor2x2_",
    YCx3: "RuinedFloor2x2_",
    YCx4: "RuinedFloor2x2_",
    YCx5: "RuinedFloor4x4_",
    YCx6: "RuinedFloor4x4_",
    YCx7: "RuinedFloor4x2_",
    YCx8: "RuinedFloor4x2_",
    YCr1: "Rough cliff cave 1",
    YCr2: "Rough cliff cave 2",
    YCr3: "Rough cliff cave 3",
    YCr4: "Rough cliff cave 4",
    YCp1: "Rough Cliff Collapse 1",
    YCp2: "Rough Cliff Collapse 2",
    YCp3: "Rough Cliff Collapse 3",
    YCp4: "Rough Cliff Collapse 4",
    YCs1: "City Cliff Slide 1",
    YCs2: "City Cliff Slide 2",
    YCs3: "City Cliff Slide 3",
    YCs4: "City Cliff Slide 4",
    YCt1: "CityCliffCollapseShort1",
    YCt2: "CityCliffCollapseShort2",
    YCt3: "CityCliffCollapseShort3",
    YCt4: "CityCliffCollapseShort4",
    YCo1: "City Cliff Slide Short 1",
    YCo2: "City Cliff Slide Short 2",
    YCo3: "City Cliff Slide Short 3",
    YCo4: "City Cliff Slide Short 4",
    YCg1: "Rough Cliff Slide 1",
    YCg2: "Rough Cliff Slide 2",
    YCg3: "Rough Cliff Slide 3",
    YCg4: "Rough Cliff Slide 4",
    YCu1: "Rough Cliff Slide Short 1",
    YCu2: "Rough Cliff Slide Short 2",
    YCu3: "Rough Cliff Slide Short 3",
    YCu4: "Rough Cliff Slide Short 4",
    YCl1: "Rough Cliff Collapse Short 1",
    YCl2: "Rough Cliff Collapse Short 2",
    YCl3: "Rough Cliff Collapse Short 3",
    YCl4: "Rough Cliff Collapse Short 4",
    ZRbs: "Small Rubble",
    ZRbd: "Large Rubble",
    ORfk: "Floating Rock",
    OZfc: "Floating Rock Cluster",
    ASpr: "Pier",
    ASpt: "Ruined Pier",
    ZPms: "Mushrooms",
    ZPvp: "Viny Plant",
    ZOls: "Library Shelf",
    YScr: "Ruined Cathedral",
    YOfr: "Ruined Fountain",
    ZZgr: "Gul'dan's Runes",
    JZif: "Invulnerability Field",
    YSr0: "City Building",
    YSr1: "City Building",
    YSr2: "City Building",
    YSr3: "City Building",
    YSr4: "City Building",
    YSr5: "City Building",
    YSr6: "City Building",
    YSr7: "City Building",
    YSr8: "City Building",
    YSr9: "City Building",
    YSra: "City Building",
    YSrb: "City Building",
    YSrc: "Large City Building",
    YSrd: "Large City Building",
    YSre: "Large City Building",
    YSrf: "Large City Building",
    YSbr: "City Building Row",
    YSb1: "City Building Row",
    YSb2: "City Building Row",
    ZZys: "Eye of Sargeras",
    JScs: "Column Semi Circle Ruined",
    JSc2: "Column Semi Circle2 Ruined",
    JSc3: "Column Semi Circle3 Ruined",
    JSc4: "Column Semi Circle4 Ruined",
    JSco: "Single Column Ruined",
    JScx: "Single Column Ruined",
    JSrc: "Large City Building Ruined Base",
    JSr6: "City Building Ruined Base",
    JSar: "Archway Ruined",
    JSax: "Archway Ruined",
    ZZcd: "Dust",
    LSrg: "Ruined Goblin Shipyard",
    AOnt: "Totem Lantern",
    DOsv: "Sewer Vent",
    DOsw: "Sewer Wallpipes",
    LOwf: "Wall Fountain",
    KOdr: "Runes",
    OZsp: "Shimmering Portal",
    ASv0: "Elven Fishing Village",
    ASv1: "Elven Fishing Village",
    ASv2: "Elven Fishing Village",
    ASv3: "Elven Fishing Village",
    ASv4: "Elven Fishing Village",
    ASx0: "Ruined Elven Fishing Village",
    ASx1: "Ruined Elven Fishing Village",
    ASx2: "Ruined Elven Fishing Village",
    ZOtr: "Trash",
    ZOba: "Bloody Altar",
    IZrw: "Rising Water",
    KOst: "Black Citadel Statue",
    IZft: "The Frozen Throne",
    IOic: "Icey Chair",
    IRcy: "Crystal",
    ISsr: "Stone Archway",
    ISs1: "Angled Stone Archway",
    IOch: "Chair",
    OOal: "Altar",
    OOgr: "Flame Grate",
    OOob: "Obstacle",
    OOsk: "Skull",
    OOst: "Stake",
    ORrr: "Rubble",
    JZud: "Underground Dome",
    OOsd: "Standard",
    IRrs: "Snowy Rocks",
    ISrb: "Rubble",
    JOgr: "Glowing Runes",
    BPtw: "Barrens Tree",
    ZPtw: "Sunken Ruins Tree",
    IZww: "Rising Water Wide",
    YSlx: "No Lantern Wall End",
    OSar: "Rock Archway",
    OSa1: "Angled Rock Archway",
    SCt0: "Strahnbrad Clock Tower",
    SLt0: "Strahnbrad Large Tree",
    BCt0: "Brill Clock Tower",
    ACt0: "Androhal Clock Tower",
    ACtd: "Androhal Clock Tower (Destroyed)",
    HA00: "Hearthglen Abbey",
    PVct: "Pyrewood Village Clock Tower (Destroyed)",
    HEcs: "High Elf Crest Standing Banners",
    HEch: "High Elf Crest Hanging Banners",
    SRbc: "Silvermoon Residential Buildings (Diagonal 1)",
    SRbe: "Silvermoon Residential Buildings (Diagonal 2)",
    SRbv: "Silvermoon Residential Buildings (Vertical)",
    SRbh: "Silvermoon Residential Buildings (Horizontal)",
    SSmt: "Sunfury Spire Main Tower",
    SSst: "Sunfury Spire Side Tower",
    STdl: "Silvermoon Tower Doodads Large",
    STdm: "Silvermoon Tower Doodads Medium",
    STds: "Silvermoon Tower Doodads Small",
    SWss: "Silvermoon Wall Straight Short",
    SWs0: "Silvermoon Wall Straight",
    SWsl: "Silvermoon Wall Straight Long",
    SWt0: "SilvermoonWall_T",
    SWsd: "Silvermoon Wall Straight Door",
    SWse: "Silvermoon Wall Straight Door Short",
    SWc0: "Silvermoon Wall Corner",
    SWe0: "Silvermoon Wall Endcap",
    SAe0: "Silvermoon Archway Entrance",
    SAe1: "Silvermoon Archway Entrance 45",
    SA00: "Silvermoon Archway",
    SA01: "Silvermoon Archway 45",
    LSt0: "Large Silvermoon Tower",
    EMt0: "Exterior Main Tower",
    ET00: "Exterior Tower",
    EW00: "Exterior Wall",
    EG00: "Exterior Gate",
    ASd0: "Archway (Standard Dimension)",
    SA02: "Statue of Azshara",
    CGd0: "Corpse of Gul)2Dan",
    VHms: "VioletHoldMainStructure",
    VHs0: "Violet Hold Spire",
    VHss: "Violet Hold Spire (Small)",
    VHae: "Violet Hold Archway Endpiece",
    MT00: "Magus Turret",
    MH00: "Magus Highrise",
    MC00: "Magus Conservatory",
    SA03: "Sunreaver Archway",
    SD00: "Sunreaver Dome",
    SDs0: "Sunreaver Dome (Small)",
    SS00: "Sunreaver Spire",
    EMs0: "Enclave Main Structure",
    ES00: "Enclave Spire",
    EH00: "Enclave House",
    EHb0: "Enclave House B",
    ET01: "Enclave Turret",
    RSf0: "Runeweaver Square Fountain",
    BA00: "Building A",
    BB00: "Building B",
    BC00: "Building C",
    WSs0: "Wall Straight Short",
    WS00: "Wall Straight",
    WSl0: "Wall Straight Long",
    WT00: "Wall T",
    WTa0: "Wall T Alt",
    WS01: "Wall Spire",
    WSa0: "Wall Spire Alt",
    WD00: "Wall 90 Degree",
    WE00: "Wall Endcap",
    ZPf0: "Flowers",
}