//exported from abilitydata.slk
export const abilityCodes = {
	AHbz: "Arch Mage - Blizzard",
	AHab: "Arch Mage - Brilliance Aura",
	AHmt: "Arch Mage - Mass Teleport",
	AHwe: "Arch Mage - Water Elemental",
	ANst: "Beast Master - Stampede",
	ANsg: "Beast Master - Summon Bear",
	ANsq: "Beast Master - Summon Quilbeast",
	ANsw: "Beast Master - Summon Hawk",
	AOww: "Blade Master - Bladestorm",
	AOcr: "Blade Master - Critical Strike",
	AOmi: "Blade Master - Mirror Image",
	AOwk: "Blade Master - Wind Walk",
	AHbn: "Blood Mage - Banish",
	AHfs: "Blood Mage - Flame Strike",
	AHdr: "Blood Mage - Siphon Mana",
	AHpx: "Blood Mage - Phoenix",
	AUcb: "Crypt Lord - Carrion Scarabs",
	AUim: "Crypt Lord - Impale",
	AUls: "Crypt Lord - Locust Swarm",
	AUts: "Crypt Lord - Spiked Carapace",
	ANba: "Dark Ranger - Black Arrow",
	ANch: "Dark Ranger - Charm",
	AHdr: "Dark Ranger - Drain",
	ANsi: "Dark Ranger - Silence",
	AUan: "Death Knight - Animate Dead",
	AUdc: "Death Knight - Death Coil",
	AUdp: "Death Knight - Death Pact",
	AUau: "Death Knight - Unholy Aura",
	AEev: "Demon Hunter - Evasion",
	AEim: "Demon Hunter - Immolation",
	AEmb: "Demon Hunter - Mana Burn",
	AEme: "Demon Hunter - Metamorphosis",
	AUsl: "Dreadlord - Sleep",
	AUav: "Dreadlord - Vampiric Aura",
	AUcs: "Dreadlord - Carrion Swarm",
	AUin: "Dreadlord - Inferno",
	AOcl: "Farseer - Chain Lightning",
	AOeq: "Farseer - Earthquake",
	AOfs: "Farseer - Far Sight",
	AOsf: "Farseer - Spirit Wolf",
	AEer: "Keeper - Entangling Roots",
	AEfn: "Keeper - Force of Nature",
	AEah: "Keeper - Thorns Aura",
	AEtq: "Keeper - Tranquility",
	AUdr: "Lich - Dark Ritual",
	AUdd: "Lich - Death and Decay",
	AUfa: "Lich - Frost Armor",
	AUfu: "Lich - Frost Armor (Autocast)",
	AUfn: "Lich - Frost Nova",
	AHav: "Mountain King - Avatar",
	AHbh: "Mountain King - Bash",
	AHtb: "Mountain King - Thunder Bolt",
	AHtc: "Mountain King - Thunder Clap",
	ANfl: "Sea Witch - Forked Lightning",
	AHca: "Sea Witch - Frost Arrows",
	ANto: "Sea Witch - Tornado",
	ANms: "Sea Witch - Mana Shield",
	AHad: "Paladin - Devotion Aura",
	AHds: "Paladin - Divine Shield",
	AHhb: "Paladin - Holy Light",
	AHre: "Paladin - Resurrection",
	ANbf: "Brewmaster - Breath of Fire",
	ANdb: "Brewmaster - Drunken Brawler",
	ANdh: "Brewmaster - Drunken Haze",
	ANef: "Brewmaster - Storm, Earth and Fire",
	ANdo: "Pit Lord - Doom",
	ANht: "Pit Lord - Howl of Terror",
	ANca: "Pit Lord - Cleaving Attack",
	ANrf: "Pit Lord - Rain of Fire",
	AHfa: "Priestess - Searing Arrows",
	AEst: "Priestess - Scout",
	AEsf: "Priestess - Starfall",
	AEar: "Priestess - Trueshot Aura",
	AOae: "Chieftain - Endurance Aura",
	AOre: "Chieftain - Reincarnation",
	AOsh: "Chieftain - Shock Wave",
	AOws: "Chieftain - War Stomp",
	AOhw: "Shadow Hunter - Healing Wave",
	AOhx: "Shadow Hunter - Hex",
	AOwd: "Shadow Hunter - Serpent Ward",
	AOvd: "Shadow Hunter - Voodooo",
	AEbl: "Warden - Blink",
	AEfk: "Warden - Fan of Knives",
	AEsh: "Warden - Shadow Strike",
	AEsv: "Warden - Spirit of Vengeance",
	ANab: "Alchemist - Acid Bomb",
	ANcr: "Alchemist - Chemical Rage",
	ANhs: "Alchemist - Healing Spray",
	ANtm: "Alchemist - Transmute",
	ANeg: "Tinkerer - Engineering Upgrade",
	ANcs: "Tinkerer - Cluster Rockets (Level 0)",
	ANcs: "Tinkerer - Cluster Rockets (Level 1)",
	ANcs: "Tinkerer - Cluster Rockets (Level 2)",
	ANcs: "Tinkerer - Cluster Rockets (Level 3)",
	ANrg: "Tinkerer - Robo-Goblin (Level 0)",
	ANrg: "Tinkerer - Robo-Goblin (Level 1)",
	ANrg: "Tinkerer - Robo-Goblin (Level 2)",
	ANrg: "Tinkerer - Robo-Goblin (Level 3)",
	ANsy: "Tinkerer - Summon Factory (Level 0)",
	ANsy: "Tinkerer - Summon Factory (Level 1)",
	ANsy: "Tinkerer - Summon Factory (Level 2)",
	ANsy: "Tinkerer - Summon Factory (Level 3)",
	ANde: "Tinkerer - Demolish (Level 0)",
	ANde: "Tinkerer - Demolish (Level 1)",
	ANde: "Tinkerer - Demolish (Level 2)",
	ANde: "Tinkerer - Demolish (Level 3)",
	ANic: "Firelord - Incinerate",
	ANia: "Firelord - Incinerate",
	ANso: "Firelord - Soul Burn",
	ANlm: "Firelord - Summon Lava Spawn",
	ANvc: "Firelord - Volcano",
	ANin: "Inferno",
	AUin: "Tichondrius - Inferno",
	ANfb: "Fire Bolt",
	ANfd: "Finger of Death",
	ANfd: "Finger of Pain",
	ANfd: "Finger of Pain (2,1 Button)",
	ANdp: "Dark Portal",
	ANrc: "Rain of Chaos",
	ANrc: "Rain of Chaos(Button 0,2)",
	AEsf: "Cenarius - Beefy Starfall",
	AOre: "Mannoroth - Reincarnation",
	ANdc: "Malganis - Dark Conversion",
	ANdc: "Dark Conversion (Fast)",
	ANsl: "Malganis - Soul Preservation",
	AEme: "Illidan - Metamorphosis",
	AEme: "Evil Illidan - Metamorphosis",
	AOeq: "Super Earthquake",
	AUdd: "Super Death and Decay",
	ANmo: "Monsoon",
	AEpa: "Poison Arrows",
	ANwm: "Watery Minion",
	AHca: "Cold Arrows",
	ANbr: "Battle Roar",
	AOsf: "Rexxar - Summon Bear",
	Aamk: "Attribute Modifier Skill",
	ANsq: "Rexxar - Summon Quilbeast",
	ANst: "Rexxar - Stampede",
	AHtb: "Rexxar - Storm Bolt",
	AOhw: "Rokhan - Healing Wave",
	AOwd: "Rokhan - Serpent Ward",
	AOhx: "Rokhan - Hex",
	AUls: "Rokhan - Voodoo Spirits",
	ANbf: "Chen - Breath of Fire",
	ANdb: "Chen- Drunken Brawler",
	ANdh: "Chen - Drunken Haze",
	ANef: "Chen - Storm, Earth and Fire",
	AOae: "Cairne - Endurance Aura",
	AOre: "Cairne - Reincarnation",
	AOsh: "Cairne - Shock Wave",
	AOws: "Cairne- War Stomp",
	ANcl: "Illidan - Channel",
	Aadm: "Abolish Magic",
	Aadm: "Abolish Magic(naga)",
	Aadm: "Abolish Magic (Creep)",
	Aadm: "Abolish Magic (Creep, 1,2 pos)",
	Aabs: "Absorb Mana",
	Aaha: "Acolyte Harvest",
	AHav: "Avatar(Garithos)",
	Aalr: "Alarm",
	Aall: "Allied Building",
	Aast: "Ancestral Spirit",
	ACad: "Animate Dead (creep)",
	Aams: "Anti-magic Shield",
	Aams: "Anti-magic Shield (Matrix)",
	Aams: "Anti-magic Shield (creep)",
	Aatk: "Attack",
	AHab: "Aura - Brilliance (creep)",
	AOac: "Aura - Command (Creep)",
	AHad: "Aura - Devotion (Creep)",
	AOae: "Aura - Endurance (Creep)",
	Aapl: "Aura - Plague (Abomination)",
	Aapl: "Aura - Plague (Plague Ward)",
	Aapl: "Aura - Plague (Creep)",
	Aapl: "Aura - Plague (Creep gfx)",
	Aapl: "Aura - Plague (Animated Dead)",
	Aoar: "Aura - Regeneration (Ward)",
	Aabr: "Aura - Regeneration (Statue)",
	Aasl: "Aura - Slow",
	AEar: "Aura - Trueshot (Creep)",
	Aakb: "Aura - War Drums",
	Aave: "Avenger Form",
	Aawa: "Awaken",
	Abof: "Balls of Fire",
	AHbn: "Banish(Creep)",
	AHbh: "Bash (creep)",
	AHbh: "Bash (Beastmaster Bear)",
	AHbh: "Bash (maul , SP Bear, level 3)",
	Abtl: "Battlestations",
	Abtl: "Battlestations (Chaos)",
	Abrf: "Bearform",
	Absk: "Beserk",
	Acha: "Berserker Upgrade",
	ANba: "Black Arrow (melee, creep)",
	Abli: "Blight Dispel (Small)",
	Abli: "Blight Dispel (Large)",
	Abli: "Blight Growth (Small)",
	Abli: "Blight Growth (Large)",
	Abgm: "Blighted Gold mine",
	AEbl: "Blink(Beastmaster Bear)",
	AHbz: "Blizzard (creep)",
	Ablo: "Bloodlust",
	Ablo: "Bloodlust (Creep)",
	Ablo: "Bloodlust (creep, Hotkey B)",
	ANbf: "Breath of Fire(Creep)",
	ACbf: "Breath of Frost(Creep)",
	ANbu: "Build (Neutral)",
	AHbu: "Build (Human)",
	AObu: "Build (Orc)",
	AEbu: "Build (Night Elf)",
	AUbu: "Build (Undead)",
	AGbu: "Build (Naga)",
	Abur: "Burrow",
	Abur: "Burrow(scarab lvl 2)",
	Abur: "Burrow(scarab lvl 3)",
	Abur: "Burrow(Barbed Arachnathid)",
	Abdt: "Burrow Detection (Flyers)",
	Acan: "Cannibalize",
	Acan: "Cannibalize (Abomination)",
	Acan: "Cannibalize (creep)",
	Abun: "Cargo Hold (Burrow)",
	Advc: "Cargo Hold (Devour)",
	Amtc: "Cargo Hold (Meat Wagon)",
	Acar: "Cargo Hold (Ship)",
	Acar: "Cargo Hold (Tank)",
	Acar: "Cargo Hold (Transport)",
	Aenc: "Cargo Hold (Gold Mine)",
	Achd: "Cargo Hold Death",
	AUcs: "Carrion Swarm (creep)",
	AUcs: "Crushing Wave",
	AUcs: "Crushing Wave (Dragon Turtle)",
	AUcs: "Crushing Wave (Lesser)",
	AOcl: "Chain Lightning (creep)",
	AIdc: "Chain Dispel",
	Acha: "Chaos (Grunt)",
	Acha: "Chaos (Raider)",
	Acha: "Chaos (Shaman)",
	Acha: "Chaos (Kodo)",
	Acha: "Chaos (Peon)",
	Acha: "Chaos (Grom)",
	Achl: "Chaos Cargo Load",
	ANch: "Charm",
	ANca: "Cleaving Attack (Creep)",
	Aclf: "Cloud of Fog",
	AHca: "Cold Arrows (creep)",
	Acmg: "Control Magic",
	Acpf: "Corporeal Form",
	Acor: "Corrosive Breath",
	Acoa: "Couple (Archer)",
	Acoh: "Couple (Hippogryph)",
	Acoi: "Couple Instant (Archer)",
	Acoi: "Couple Instant (Hippogryph)",
	ACsp: "Creep Sleep",
	Acri: "Cripple",
	Acri: "Cripple (Warlock)",
	Acri: "Cripple (creep)",
	AOcr: "Critical Strike (creep)",
	Acrs: "Curse",
	Acrs: "Curse (creep)",
	Acyc: "Cyclone",
	Acyc: "Cyclone (naga)",
	Acyc: "Cyclone (creep)",
	Acyc: "Cyclone (Cenarius)",
	AUdc: "Death Coil (creep)",
	Adda: "Death Damage (sapper)",
	Adda: "Death Damage (mine)",
	Adda: "Death Damage (mine BIG)",
	Adec: "Decouple",
	Adef: "Defend",
	Adet: "Detect (Sentry Ward)",
	Atru: "Detect (Shade)",
	Atru: "Detect (general)",
	Atru: "Detect(War Eagle)",
	Agyv: "Detect (Gyrocopter)",
	Adts: "Detect (Magic Sentinel)",
	Adtn: "Detonate",
	Adev: "Devour",
	ACdv: "Devour (Dragon Creep)",
	Advm: "Devour Magic",
	Advm: "Devour Magic(creep)",
	Adch: "Disenchant(old)",
	Adis: "Disenchant(new)",
	Adis: "Dispel Magic",
	Adis: "Dispel Magic (creep)",
	AHds: "Divine Shield (creep)",
	AHdr: "Drain Life(Creep)",
	Adri: "Drop Instant",
	Adro: "Drop",
	Adro: "Drop",
	Atdp: "Drop Pilot",
	Aeat: "Eat Tree",
	AIdd: "Elune's Grace",
	Aens: "Ensnare(Naga)",
	Aens: "Ensnare",
	Aens: "Ensnare (Creep)",
	Aent: "Entangle",
	Aegm: "Entangled Gold Mine",
	AEer: "Entangling Roots (creep)",
	AEer: "Entangling Seaweed",
	Aetl: "Ethereal",
	Aetf: "Ethereal Form",
	AEev: "Evasion (creep)",
	AEev: "Evasion (creep 100%)",
	Aexh: "Exhume",
	ANfy: "Factory",
	Afae: "Faerie Fire",
	Afae: "Faerie Fire",
	Afae: "Faerie Fire (creep)",
	Afbk: "Feedback",
	Afbk: "Feedback(Arcane Tower)",
	Afbk: "Feedback (Spirit Beast)",
	AOsf: "Feral Spirit (creep)",
	AOsf: "Feral Spirit (creep - pig)",
	AOsf: "Feral Spirit (Spirit Beast)",
	AOsf: "Feral Spirit (Akama)",
	ANfd: "Finger of Death",
	ANfb: "Fire Bolt (warlock)",
	ANfb: "Fire Bolt (creep)",
	Aflk: "Flak Cannon",
	Afla: "Flare",
	AHfs: "Flame Strike (Creep)",
	AHfs: "Flame Strike (Improved Creep)",
	AEfn: "Force of Nature (creep)",
	ANfl: "Forked Lightning(creep)",
	Afsh: "Frag Shards",
	Afrz: "Freezing Breath",
	Afzy: "Frenzy",
	AUfa: "Frost Armor (creep,old)",
	AUfu: "Frost Armor (creep,autocast)",
	AUfu: "Frost Armor (Autocast, Naga)",
	Afra: "Frost Attack",
	Afra: "Frost Attack (1,2)",
	Afrb: "Frost Breath",
	Afrb: "Frost Breath (new, has icon)",
	AUfn: "Frost Nova (creep)",
	AHtb: "Frost Bolt",
	Agho: "Ghost",
	Aeth: "Ghost (Visible)",
	Agld: "Gold Mine",
	Agra: "Grab Tree",
	Agyd: "Graveyard",
	Agyb: "Gyrocopter Bombs",
	Assk: "Hardened Skin",
	Assk: "Hardened Skin(Naga Turtle)",
	Ahar: "Harvest",
	Ahar: "Harvest (naga)",
	Ahrl: "Harvest Lumber",
	Ahrl: "Harvest Lumber (shredder)",
	Ahrl: "Harvest Lumber (Arch ghouls)",
	Ahea: "Heal",
	Anhe: "Heal (Creep Normal)",
	Anhe: "Heal (Creep Normal)",
	Anhe: "Heal (Creep High)",
	Ahwd: "Healing Ward",
	Ahwd: "Healing Ward (creep)",
	AOhw: "Healing Wave(Creep)",
	Aroa: "null roar (summoner)",
	AHer: "Hero",
	AOhx: "Hex (Creep)",
	ANht: "Howl of Terror",
	AEim: "Immolation (creep)",
	AUim: "Impale(Creep)",
	Aimp: "Impaling Bolt",
	Ainf: "Inner Fire",
	Ainf: "Inner Fire (Creep)",
	Aivs: "Invisibility",
	AInv: "Inventory",
	AInv: "Inventory (Pack Mule)",
	AInv: "Inventory(2 slot unit) Orc",
	AInv: "Inventory(2 slot unit) Human",
	AInv: "Inventory(2 slot unit) Night Elf",
	AInv: "Inventory(2 slot unit) Undead",
	Avul: "Invulnerable",
	Alit: "Lightning Attack",
	Alsh: "Lightning Shield",
	Alsh: "Lightning Shield (creep)",
	Aliq: "Liquid Fire",
	Aloa: "Load",
	Aloa: "Load (Burrow)",
	Aloa: "Load (Entangled Gold Mine)",
	Aloa: "Load (Navies)",
	Atlp: "Load Pilot",
	Aloc: "Locust",
	Amdf: "Magic Defense",
	Amim: "Magic Immunity",
	Amim: "Magic Immunity (Creep)",
	Amim: "Magic Immunity (Archimonde)",
	Amim: "Magic Immunity (Dragons)",
	Amls: "Aerial Shackles",
	Ambt: "Mana Battery",
	Ambt: "Mana Battery (Obsidian Statue)",
	AEmb: "Mana Burn (demon)",
	AEmb: "Mana Burn (demon)",
	AEmb: "Mana Burn (Hotkey B)",
	Amfl: "Mana Flare",
	ANms: "Mana Shield(Creep)",
	Amed: "Meat Drop",
	Amel: "Meat Load",
	Amil: "Militia",
	Amic: "Militia Conversion",
	ANmr: "Mind Rot",
	Amin: "Mine",
	ANmo: "Monsoon(creep)",
	Aaab: "Moon Glaive",
	Aaab: "Moon Glaive (No research)",
	Amov: "Move",
	Aneu: "Neutral Building",
	Aneu: "Neutral Building (any unit)",
	Andt: "Neutral Detection (Reveal ability)",
	Aarm: "Neutral Regen (mana only)",
	Aoar: "Neutral Regen (health only)",
	AAns: "Neutral Spell",
	Ansp: "Neutral Spies",
	Afak: "Orb of Annihilation",
	Afak: "Orb of Annihilation (Quill Spray)",
	Afir: "On Fire",
	Afih: "On Fire (Human)",
	Afio: "On Fire (Orc)",
	Afin: "On Fire (Night Elf)",
	Afiu: "On Fire (Undead)",
	ANpa: "Parasite",
	ANpa: "Parasite(eredar)",
	ANpi: "Permanent Immolation",
	ANpi: "Permanent Immolation (flying)",
	Apig: "Permanent Immolation (graphic)",
	Apiv: "Permanent Invisibility",
	Apsh: "Phase Shift",
	Aphx: "Phoenix",
	Apxf: "PhoenixFire",
	Apts: "Plague Toss",
	Apoi: "Poison Attack",
	Aply: "Polymorph",
	Aply: "Polymorph (creep)",
	Apos: "Possession",
	Apos: "Possession (creep)",
	Aps2: "Possession (Channeling)",
	Awar: "Pulverize",
	Awar: "Pulverize (Sea Giant)",
	Apit: "Purchase Item",
	Aprg: "Purge",
	Aprg: "Purge",
	Aprg: "Purge (Creep)",
	ANrf: "Rain of Fire (creep)",
	ANrf: "Rain of Fire (creep,greater)",
	Arai: "Raise Dead",
	Arai: "Raise Dead (Creep)",
	ARal: "Rally",
	Arav: "Raven Form (Druid)",
	Arav: "Raven Form (Medivh)",
	ACrn: "Reincarnation (creep)",
	AOre: "Reincarnation (generic)",
	Arbr: "Reinforced Burrows",
	Arej: "Rejuvination",
	Arej: "Rejuvination (creep)",
	Arej: "Rejuvination (Furbolg)",
	Aren: "Renew",
	Arep: "Repair (Human)",
	Arep: "Repair (Orc)",
	Arpb: "Replenish (Life & Mana)",
	Arpl: "Replenish (Life)",
	Arpm: "Replenish (Mana)",
	Arsk: "Resistant Skin",
	Arsk: "Resistant Skin (creep)",
	Arsk: "Resistant Skin(3,1 pos, creep)",
	Arst: "Restoration",
	Artn: "Return (Gold)",
	Artn: "Return (Gold & Lumber)",
	Artn: "Return (Lumber)",
	AIta: "Reveal(Arcane Tower)",
	Arng: "Revenge",
	Arev: "Revive",
	Aroa: "Roar",
	Aroa: "Roar",
	Aroa: "Roar (creep) -- Skeletal Orc",
	Aroa: "Roar (creep)",
	Aroc: "Rocket Attack",
	Aroo: "Root (Ancients)",
	Aroo: "Root (Ancient Protector)",
	Asac: "Sacrifice (Sacrificial Pit)",
	Asal: "Pillage",
	Alam: "Sacrifice (Acolyte)",
	AHfa: "Searing Arrows (creep)",
	Asds: "Self Destruct",
	Asds: "Self Destruct (Clockwerk Goblins)",
	Asds: "Self Destruct 2 (Clockwerk Goblins)",
	Asds: "Self Destruct 3 (Clockwerk Goblins)",
	Asid: "Sell Item",
	Asud: "Sell Unit",
	Aesn: "Sentinel",
	Aesn: "Sentinel (no research)",
	Aeye: "Sentry Ward",
	AOwd: "Serpent Ward (tentacle, Forgotten one)",
	Ashm: "Shadow Meld",
	Ashm: "Shadow Meld (Item)",
	Ashm: "Shadow Meld (Instant)",
	Ahid: "Shadow Meld (Akama)",
	AEsh: "Shadow Strike(Creep)",
	AOsh: "Shockwave (Creep)",
	AOsh: "Shockwave (Trap)",
	AOsh: "Garithos - Shock Wave",
	ANsi: "Silence(Creep)",
	AHdr: "Siphon Mana (Creep)",
	AUsl: "Sleep (creep)",
	Asla: "Sleep Always",
	Aslo: "Slow",
	Aslo: "Slow (Creep)",
	Aspo: "Slow Poison",
	Asod: "Spawn Skeleton",
	Assp: "Spawn Spiderling",
	Aspd: "Spawn Spider",
	Aspd: "Spawn Hydra",
	Aspd: "Spawn Hydra Hatchling",
	Asps: "Spell Steal",
	Asph: "Sphere",
	Asph: "Sphere (SoV Level 1)",
	Asph: "Sphere (SoV Level 2)",
	Asph: "Sphere (SoV Level 3)",
	Asph: "Sphere (SoV Level 4)",
	Asph: "Sphere (SoV Level 5)",
	Asph: "Sphere (SoV Level 6)",
	Aspa: "Spider Attack",
	Aspi: "Spiked Barricades",
	Aspl: "Spirit Link",
	Astd: "Stand Down",
	Asta: "Stasis Trap",
	Astn: "Stone Form",
	Asth: "Storm Hammers",
	ANsu: "Submerge (Myrmidon)",
	ANsu: "Submerge (Royal Guard)",
	ANsu: "Submerge (Snap Dragon)",
	ANwm: "Summon Lobstrok Prawns",
	AHwe: "Summon Sea Elemental",
	Attu: "Tank Turret",
	Acha: "Tank Upgrade",
	Atau: "Taunt",
	Atau: "Taunt(Creep)",
	AUts: "Thorny Shield (Creep)",
	AUts: "Thorny Shield (Dragon Turtle)",
	AEah: "Thorns Aura (creep)",
	ACtb: "Thunder Bolt (Creep)",
	ACtc: "Thunder Clap (Creep)",
	ACtc: "Thunder Clap (Thunder Lizard)",
	Atdg: "TornadoDamage",
	Atsp: "TornadoSpin",
	Atwa: "TornadoWander",
	Atol: "Tree of life (for attaching art)",
	Ault: "Ultravision",
	AUau: "Unholy Aura (creep)",
	Auhf: "Unholy Frenzy",
	Auhf: "Unholy Frenzy (Warlock)",
	Auhf: "Unholy Frenzy (creep)",
	Auuf: "Incite Unholy Frenzy",
	Auco: "Unstable Concoction",
	Auns: "Unsummon",
	AIva: "Vampiric attack",
	AUav: "Vampiric Aura (creep)",
	Avng: "Vengeance",
	Awan: "Wander",
	AOws: "War Stomp (creep)",
	AOws: "War Stomp (sea giant)",
	AOws: "War Stomp (hydra)",
	AOwk: "Wind Walk",
	Awha: "Wisp Harvest",
	Awha: "Wisp Harvest (Invulnerable)",
	Aven: "Venom Spears",
	Aven: "Venom Spears (Creep)",
	Awrp: "Warp",
	Aweb: "Web",
	Aweb: "Web (creep)",
	AIab: "AgilityBonus (+1)",
	AIab: "AgilityBonus (+2)",
	AIab: "AgilityBonus (+3)",
	AIab: "AgilityBonus (+4)",
	AIab: "AgilityBonus (+5)",
	AIab: "AgilityBonus (+6)",
	AIab: "Crown of Kings (All + 5)",
	AIab: "(All + 1)",
	AIab: "(All + 2)",
	AIab: "StrengthBonus (+1)",
	AIab: "StrengthBonus (+2)",
	AIab: "StrengthBonus (+3)",
	AIab: "StrengthBonus (+4)",
	AIab: "StrengthBonus (+5)",
	AIab: "StrengthBonus (+6)",
	AIab: "IntelligenceBonus (+1)",
	Aiab: "IntelligenceBonus (+2)",
	AIab: "IntelligenceBonus (+3)",
	AIab: "IntelligenceBonus (+4)",
	AIab: "IntelligenceBonus (+5)",
	AIab: "IntelligenceBonus (+6)",
	AIvm: "Reassignable Attribute Bonus (+1)",
	AIxm: "Permanent All + 1",
	AIam: "AgilityMod",
	AIim: "IntelligenceMod",
	AIsm: "StrengthMod",
	AIam: "AgilityMod +2",
	AIim: "IntelligenceMod +2",
	AIsm: "StrengthMod +2",
	AIaa: "AttackMod",
	AIat: "AttackBonus",
	AIat: "AttackBonus",
	AIat: "AttackBonus",
	AIat: "AttackBonus",
	AIat: "AttackBonus",
	AIat: "AttackBonus +1",
	AIat: "AttackBonus +2",
	AIat: "AttackBonus +4",
	AIat: "AttackBonus +5",
	AIat: "AttackBonus +7",
	AIat: "AttackBonus +8",
	AIat: "AttackBonus +10",
	AIva: "Vampiric attack",
	AEbl: "Blink (Item)",
	AIbl: "Build Tiny Castle",
	AIbl: "Build Tiny Great Hall",
	AIbl: "Build Tiny Scout Tower",
	AIbl: "Build Tiny Blacksmith",
	AIbl: "Build Tiny Farm",
	AIbl: "Build Tiny Lumber Mill",
	AIbl: "Build Tiny Barracks",
	AIbl: "Build Tiny Altar",
	Acyc: "Cyclone",
	AIde: "DefenseBonus (+1)",
	AIde: "DefenseBonus (+2)",
	AIde: "DefenseBonus (+3)",
	AIde: "DefenseBonus (+4)",
	AIde: "DefenseBonus (+5)",
	AIgl: "FortificationGlyph",
	AIgl: "UltraVisionGlyph",
	AIem: "ExperienceMod",
	AIem: "ExperienceMod greater",
	AIfs: "FigurineRedDrake",
	AIfs: "FigurineFurbolg",
	AIfs: "FigurineRockGolem",
	AIfs: "FigurineDoomGuard",
	AIfs: "FigurineFelHound",
	AIfs: "FigurineSkeleton",
	AIfs: "FigurineIceRevenant",
	AIfs: "FigurineUrsaWarrior",
	AIfl: "Flag",
	AIfm: "Flag (Human)",
	AIfo: "Flag (Orc)",
	AIfn: "Flag (Night Elf)",
	AIfe: "Flag (Undead)",
	AIfl: "Flag (Orc Battle Standard)",
	AIfa: "FlareGun",
	AUin: "ItemInferno",
	AIlm: "LevelMod",
	AIlp: "LightningPurge",
	AIml: "MaxLifeBonus (Least)",
	AIml: "MaxLifeBonus (Lesser)",
	AIml: "MaxLifeBonus (Greater)",
	AIms: "MoveSpeedBonus",
	ANbs: "Orb of Darkness (Black Arrow)",
	AIsb: "Orb of Darkness",
	AIcb: "Orb of Corruption",
	AIfb: "Shadow Orb Ability",
	AIfb: "Orb of Fire",
	AIfb: "Orb of Guldan",
	AIzb: "Orb of Freezing",
	AIob: "Orb of Frost",
	AIsb: "Orb of Lightning",
	AIlb: "Orb of Lightning(old)",
	AIsb: "Orb of Spells",
	AIpb: "Orb of Venom",
	Apo2: "Orb of Venom (Poison Attack)",
	ACad: "Animate Dead (item, special)",
	Arel: "Regen Life",
	Arel: "Regen Life",
	AIsi: "SightBonus",
	Aslo: "Slow",
	AIso: "SoulTrap",
	Asou: "SoulPossession",
	AIcf: "ItemCloakOfFlames",
	AIco: "ItemCommand",
	AIdm: "ItemDamageAoe",
	AIda: "ItemDefenseAoe",
	AIda: "ItemDefenseAoe (+ Healing)",
	AIta: "ItemDetectAoe",
	AIdi: "ItemDispelAoe",
	AIdi: "ItemDispelAoeWithCooldown",
	AIdi: "PowerupDispelAoe",
	AIhe: "ItemHeal (Lesser)",
	AIhe: "ItemHeal (Greater)",
	AIhe: "ItemHeal (Least)",
	AIha: "ItemHealAoe",
	AIha: "ItemHealAoeGreater",
	AIha: "PowerupHealAoeLesser",
	AIha: "PowerupHealAoe",
	AIha: "PowerupHealAoeGreater",
	Ahwd: "Healing Ward",
	Aeye: "Sentry Ward (Item)",
	AIil: "ItemIllusion",
	AIvi: "ItemInvis (Lesser)",
	AIvi: "ItemInvis (Greater)",
	AIvu: "ItemInvul (Normal)",
	AIvu: "ItemInvul (Lesser)",
	AIvu: "ItemInvul (Divinity)",
	AIma: "ItemManaRestore (Lesser)",
	AIma: "ItemManaRestore (Greater)",
	AImr: "ItemManaRestoreAoe",
	AImr: "RuneManaRestoreAoe",
	AImr: "RuneManaRestoreGreaterAoe",
	AIpm: "ItemPlaceMine",
	AIrt: "ItemRecall",
	AIrm: "ItemRegenMana",
	AIrm: "ItemRegenMana lesser",
	AIrc: "ItemReincarnation",
	AIre: "ItemRestore",
	AIra: "ItemRestoreAoe",
	AIra: "RuneRestoreAoe",
	AIsp: "ItemSpeed",
	AIsa: "ItemSpeedAoe",
	AIsa: "RuneSpeedAoe",
	AItp: "ItemTownPortal",
	AHad: "ItemAuraDevotion",
	AOac: "ItemAuraCommand",
	Aakb: "ItemAuraWarDrums",
	AHab: "ItemAuraBrilliance",
	AUav: "ItemAuraVampiric",
	AEar: "ItemAuraTrueshot",
	AOae: "ItemAuraEndurance",
	AUau: "ItemAuraUnholy",
	Ault: "ItemUltravision",
	Alsh: "Lightning Shield (item)",
	Aami: "Anti-magic Shield",
	AIan: "Animate Dead",
	AIrs: "Resurrection",
	Aroa: "Roar",
	AEev: "Evasion",
	Amim: "Magic Immunity",
	AImi: "Permanent Hit point Bonus",
	AImm: "MaxManaBonus (Least)",
	AImm: "MaxManaBonus (Most)",
	AIas: "Attack Speed Increase",
	AIas: "Attack Speed Increase(greater)",
	AIrg: "Potion of Life Regen",
	AIrg: "Potion of Mana Regen(greater)",
	AIrg: "Scroll of Life Regen",
	AIrg: "Potion of Mana Regen(lesser)",
	AIrg: "Potion of Rejuv I",
	AIrg: "Potion of Rejuv II",
	AIrg: "Potion of Rejuv III",
	AIrg: "Potion of Rejuv IV",
	AIrg: "Scroll of Rejuv I",
	AIrg: "Scroll of Rejuv II",
	AIgo: "GiveGold",
	AIlu: "GiveLumber",
	AIrv: "ItemRevealMap",
	AIdc: "ItemDispelChain",
	AIwb: "ItemWeb",
	AImo: "ItemMonsterLure",
	AIct: "ItemChangeTOD",
	AIri: "ItemRandomItem",
	AIsr: "Runed Bracers",
	Ablp: "BlightPlacement",
	AIpv: "ItemPotionVampirism",
	Aste: "ManaSteal",
	Amec: "MechanicalCritter",
	Ashs: "ShadowSight",
	ANpr: "Preservation",
	ANsa: "Sanctuary",
	ANss: "Spell Shield",
	ANse: "Spell Shield AOE",
	Aret: "Retrain",
	AHmt: "Staff o' Teleportation",
	Aspb: "Spell Book",
	AIrd: "Raise Dead (Item)",
	AItb: "Dust of Appearance",
	AHds: "Divine Shield (Item)",
	ANsi: "Silence(Item)",
	Aprg: "Purge(orb)",
	Aprg: "Purge(Totem, SP)",
	Aprg: "Purge(Wand of Negation)",
	Aclf: "Cloud of Fog (Item)",
	AHre: "Rune of Lesser Resurrection",
	AHre: "Rune of Greater Resurrection",
	AIrb: "Rune of Rebirth",
	Aspl: "Rune of Spirit Link",
	AUds: "Dark Summoning",
	Aeye: "Rune of the Watcher",
	Auhf: "Unholy Frenzy (item)",
	AIde: "DefenseBonus (+10)",
	Acmg: "Control Magic (item)",
	AImm: "MaxManaBonus (Leastest)",
	ANfd: "Finger of Death (item)",
	AUdp: "Death Pact (item)",
	AImm: "MaxManaBonus (Leastest, Really)",
	AImi: "Permanent Hit point Bonus (small)",
	AIdd: "Defend (Item)",
	AIde: "DefenseBonus (+8)",
	AIde: "DefenseBonus (+7)",
	AIml: "MaxLifeBonus (Leastest)",
	AIhe: "ItemHeal (Leastest)",
	AIab: "AgilityBonus (+10)",
	AHre: "Resurrection - Item",
	AHbh: "Bash (item)",
	AIat: "AttackBonus +20",
	ANwm: "Watery Minion (item)",
	AIsh: "Summon Headhunter (item)",
	AImm: "200 mana bonus",
	Aoar: "Aura - Regeneration (item)",
	AHhb: "Holy Light (item)",
	Aspo: "Slow Poison (item)",
	AIha: "Penguin Squeek",
	AIfb: "Searing Blade - fire melee",
	AIob: "Frostguard - frost melee",
	AIsb: "Shaman Claws - lightning melee",
	AOcr: "Critical Strike (item)",
	AOcl: "Chain Lightning (item)",
	AIab: "(All + 3)",
	AIab: "(All + 4)",
	Absk: "Beserk (item)",
	AIdg: "ItemRitualDagger (Instant)",
	AIdg: "ItemRitualDagger (Regen)",
	AIhu: "Orb of Fire v2",
	Aaab: "Sundering Blades",
	APai: "PassiveSimple",
	APai: "Passive - human rifleman plus range (Rhri)",
	APai: "Passive - human animal breeding (Rhan)",
	APai: "Passive - phoenix (Fire and Egg)",
	APai: "Passive - human lumber harvesting (Rhlh)",
	APai: "Passive - orc grunt berserk (Robs)",
	APai: "Passive - orc berserkers (Robk)",
	APai: "Passive - orc reinforced defense (Rorb)",
	APai: "Passive - orc spiked barricade (Rosp)",
	APai: "Passive - orc Ghost(icon only, orc, Aeth, unused)",
	APai: "Passive - orc troll regeneration (Rotr)",
	APai: "Passive - undead ghoul frenzy (Rugf)",
	APai: "Passive - Ghost (icon only, undead, Agho)",
	APai: "Passive - undead skeletal mastery (Rusm)",
	APai: "Passive - nightelf improved bows (Reib)",
	APai: "Passive - nightelf marksmanship (Remk)",
	APai: "Passive - nightelf well spring (Rews)",
	AIfs: "FigurineBlueDrake",
	AIfs: "FigurineFurbolgTracker",
	AIfs: "FigurineDragonspawnOverseer",
	ANtm: "ItemTransmute",
	Aatp: "Attack Target Priority",
	Aosl: "Slow",
	Amgi: "Bouncing Missile Filter",
	AUa2: "Death Knight - Animate Dead",
}