// exported from itemdata.slk
export const itemCodes = {
    ckng: "Crown of Kings +5",
    modt: "mask of death",
    tkno: "Tome of Power",
    ratf: "Claws of Attack +15",
    ofro: "Orb of Frost",
    infs: "Inferno Stone",
    desc: "Dagger of Escape",
    fgdg: "Demonic Figurine",
    engr: "Engraved Scale",
    shar: "Ice Shard",
    ccmd: "Scepter of Mastery",
    wild: "Amulet of the Wild",
    scav: "Scepter of Avarice",
    odef: "Orb of Darkness",
    rde4: "Ring of Protection +5",
    pmna: "Pendant of Mana",
    rhth: "Khadgar's Gem of Health",
    ssil: "Staff of Silence",
    spsh: "Amulet of Spell Shield",
    sres: "Scroll of Restoration",
    pdi2: "Potion of Divinity (Invulnerability)",
    pres: "Potion of Restoration",
    iotw: "Idol of the wild",
    fgfh: "Spiked Collar",
    fgbd: "Blue Drake Egg",
    fgrg: "Stone Token",
    hcun: "Hood of Cunning",
    hval: "Helm of Valor",
    mcou: "Medallion of Courage",
    ajen: "Ancient Janggo of Endurance",
    clfm: "Cloak of Flames",
    ratc: "Claws of Attack +12",
    war2: "Warsong Battle Drums (Kodo)",
    kpin: "Khadgar's Pipe of Insight",
    lgdh: "Legion Doom-Horn",
    ankh: "Ankh of Reincarnation",
    whwd: "Healing Wards",
    fgsk: "Book of the Dead",
    wcyc: "Wand of the Wind",
    hlst: "Health Stone",
    mnst: "Mana Stone",
    belv: "Boots of Quel'Thalas +6",
    bgst: "Belt of Giant Strength +6",
    ciri: "Robe of the Magi +6",
    lhst: "Lion Horn of Stormwind",
    afac: "Alleria's Flute of Accuracy",
    sbch: "Scourge Bone Chimes",
    brac: "Runed Bracers",
    rwiz: "Sobi Mask",
    pghe: "potion of greater healing",
    pgma: "Potion of Greater Mana",
    pnvu: "potion of invulnerability",
    sror: "Scroll of the Beast",
    woms: "Wand of Mana Stealing",
    crys: "Crystal Ball",
    evtl: "Talisman of Evasion",
    penr: "Pendant of Energy",
    prvt: "Periapt of Vitality",
    rat9: "Claws of Attack +9",
    rde3: "Ring of Protection +4",
    rlif: "Ring of regeneration",
    bspd: "Boots of Speed",
    rej3: "Replenishment Potion",
    will: "Wand of Illusion",
    wlsd: "Wand of Lightning Shield",
    wswd: "Sentry Wards",
    cnob: "Circlet of Nobility",
    gcel: "Gloves of Haste",
    rat6: "Claws of Attack +6",
    rde2: "Ring of Protection +3",
    tdx2: "Tome of Agility +2",
    tin2: "Tome of Intelligence +2",
    tpow: "Tome of Knowledge",
    tst2: "Tome of Strength +2",
    pnvl: "Potion of Lesser Invulnerability",
    clsd: "Cloak of Shadows",
    rag1: "Slippers of Agility +3",
    rin1: "Mantle of Intelligence +3",
    rst1: "Gauntlets of Ogre Strength +3",
    manh: "Manual of Health",
    tdex: "Tome of Agility +1",
    tint: "Tome of Intelligence",
    tstr: "Tome of Strength +1",
    pomn: "Potion of Omniscience",
    wshs: "Wand of Shadowsight",
    rej6: "Greater Scroll of Replenishment",
    rej5: "Lesser Scroll of Replenishment",
    rej4: "Greater Replenishment Potion",
    ram4: "Fourth Ring of the Archmagi",
    dsum: "Diamond of Summoning",
    ofir: "Orb of Fire",
    ocor: "Orb of Corruption",
    oli2: "Orb of Lightning",
    oven: "Orb of Venom",
    ram3: "Third Ring of the Archmagi",
    tret: "Tome of Retraining",
    tgrh: "Tiny Great Hall",
    rej2: "Lesser Replenishment Potion",
    gemt: "Gem of True Seeing",
    ram2: "Second Ring of the Archmagi",
    stel: "Staff of Teleportation",
    stwp: "Scroll of Town Portal",
    wneg: "Wand of Negation",
    sneg: "Staff of Negation",
    wneu: "Wand of Neutralization",
    shea: "Scroll of Healing",
    sman: "Scroll of Mana",
    rej1: "Minor Replenishment Potion",
    pspd: "Potion of Speed",
    dust: "Dust of Appearance",
    ram1: "First Ring of the Archmagi",
    pinv: "potion of invisibility",
    phea: "potion of healing",
    pman: "Potion of Mana",
    spro: "Scroll of Protection",
    hslv: "Healing Salve",
    moon: "Moonstone",
    shas: "Scroll of Speed",
    skul: "Sacrificial Skull",
    mcri: "Mechanical Critter",
    rnec: "Rod of Necromancy",
    ritd: "Ritual Dagger",
    tsct: "Ivory Tower",
    azhr: "Heart of Aszune",
    bzbe: "Empty Vial",
    bzbf: "Full Vial",
    ches: "Cheese",
    cnhn: "Horn of Cenarius",
    glsk: "Guldan's Skull",
    gopr: "Glyph of Purification",
    k3m1: "Key of 3 Moons - 1",
    k3m2: "Key of 3 Moons - 2",
    k3m3: "Key of 3 Moons - 3",
    ktrm: "Urn of Kel'Thuzad",
    kybl: "bloody key",
    kygh: "ghost key",
    kymn: "moon key",
    kysn: "sun key",
    ledg: "Gerard's Lost Ledger",
    phlt: "Phat Lewt",
    sehr: "Searinox's Heart",
    engs: "Enchanted Gemstone",
    sorf: "Shadow Orb Fragment",
    gmfr: "Gem Fragment",
    jpnt: "note to jaina proudmoore",
    shwd: "shimmerweed",
    skrt: "Skeletal Artifact",
    thle: "thunder lizard egg",
    sclp: "secret level powerup",
    wtlg: "Wirt's Leg",
    wolg: "Wirt's Other Leg",
    mgtk: "Magtheridon's Keys",
    mort: "Mogrin's Report",
    dphe: "Thunder Hawk Egg",
    dkfw: "Keg of Thunderwater",
    dthb: "Thunderbloom Bulb",
    fgun: "Flare Gun",
    lure: "Monster Lure",
    olig: "Orb of Lightning(old)",
    amrc: "Amulet of Recall",
    flag: "human flag",
    gobm: "Goblin Land Mine",
    gsou: "Soul Gem",
    nflg: "NightElf flag",
    nspi: "Necklace of Spell Immunity",
    oflg: "Orc flag",
    pams: "Anti-Magic Potion",
    pgin: "potion of greater invisibility",
    rat3: "Claws of Attack +3",
    rde0: "Ring of Protection +1",
    rde1: "Ring of Protection +2",
    rnsp: "Ring of Superiority",
    soul: "Soul",
    tels: "Goblin Night Scope",
    tgxp: "Tome of Greater Experience",
    uflg: "Undead flag",
    anfg: "Ancient Figurine",
    brag: "Bracer of Agility",
    drph: "Druid Pouch",
    iwbr: "Ironwood Branch",
    jdrn: "Jade Ring",
    lnrn: "Lion's Ring",
    mlst: "Maul of Strength",
    oslo: "Orb of Slow",
    sbok: "Spell Book",
    sksh: "Skull Shield",
    sprn: "Spider Ring",
    tmmt: "Totem of Might",
    vddl: "Voodoo Doll",
    spre: "Staff of Preservation",
    sfog: "Horn of the Clouds",
    sor1: "Shadow Orb +1",
    sor2: "Shadow Orb +2",
    sor3: "Shadow Orb +3",
    sor4: "Shadow Orb +4",
    sor5: "Shadow Orb +5",
    sor6: "Shadow Orb +6",
    sor7: "Shadow Orb +7",
    sor8: "Shadow Orb +8",
    sor9: "Shadow Orb +9",
    sora: "Shadow Orb +10",
    fwss: "Frostwyrm Skull Shield",
    shtm: "Shamanic Totem",
    esaz: "Essence of Aszune",
    btst: "orcish battle standard",
    tbsm: "Tiny Blacksmith",
    tfar: "Tiny Farm",
    tlum: "Tiny Lumber Mill",
    tbar: "Tiny Barracks",
    tbak: "Tiny Altar of Kings",
    gldo: "Orb of Kil'jaeden",
    stre: "Staff of Reanimation",
    horl: "Holy Relic",
    hbth: "Helm of Battlethirst",
    blba: "Bladebane Armor",
    rugt: "Runed Gauntlets",
    frhg: "Firehand Gauntlets",
    gvsm: "Gloves of Spell Mastery",
    crdt: "Crown of the Deathlord",
    arsc: "Arcane Scroll",
    scul: "Scroll of the Unholy Legion",
    tmsc: "Tome of Sacrifices",
    dtsb: "Drek'thar's Spellbook",
    grsl: "Grimoire of Souls",
    arsh: "Arcanite Shield",
    shdt: "Shield of the Deathlord",
    shhn: "Shield of Honor",
    shen: "Enchanted Shield",
    thdm: "Thunderlizard Diamond",
    stpg: "Stuffed Penguin",
    shrs: "Shimmerglaze Roast",
    bfhr: "Bloodfeather's Heart",
    cosl: "Celestial Orb of Souls",
    shcw: "Shaman Claws",
    srbd: "Searing Blade",
    frgd: "Frostguard",
    envl: "Enchanted Vial",
    rump: "Rusty Mining Pick",
    srtl: "Serathil",
    stwa: "Sturdy War Axe",
    klmm: "Killmaim",
    rots: "Rod of the Sea",
    axas: "Ancestral Staff",
    mnsf: "Mindstaff",
    schl: "Scepter of Healing",
    asbl: "Assassin's Blade",
    kgal: "Keg of Ale",
    ward: "Warsong Battle Drums",
    gold: "Chest of Gold",
    lmbr: "Bundle of Lumber",
    gfor: "Glyph of Fortification",
    guvi: "Glyph of UltraVision",
    rspl: "Rune of Spirit Link",
    rre1: "Rune of Lesser Resurrection",
    rre2: "Rune of Greater Resurrection",
    gomn: "Glyph of Omniscience",
    rsps: "Rune of Shielding",
    rspd: "Rune of Speed",
    rman: "Rune of Mana(Lesser)",
    rma2: "Rune of Mana(Greater)",
    rres: "Rune of Restoration",
    rreb: "Rune of Rebirth",
    rhe1: "Rune of Lesser Healing",
    rhe2: "Rune of Healing",
    rhe3: "Rune of Greater Healing",
    rdis: "Rune of Dispel Magic",
    texp: "Tome of Experience",
    rwat: "Rune of the Watcher",
    pclr: "Clarity Potion",
    plcl: "Lesser Clarity Potion",
    silk: "Spider Silk",
    vamp: "Potion of Vampirism",
    sreg: "Scroll of Regeneration",
    tcas: "Tiny Castle",
    ssan: "Staff of Sanctuary",
    ofr2: "Orb of Fire v2",
    sxpl: "Seed of Expulsion",
    vpur: "Vine of Purification",
    pdiv: "Potion of Divinity (Divine Shield)",
    fgrd: "Red Drake Egg",
    totw: "talisman of the wild",
    sand: "Scroll of Animate Dead",
    srrc: "Scroll of Resurrection",
}