// exported from destructibles.slk
export const destructibleCodes = {
    ATtr: "Tree Wall",
    BTtw: "Tree Wall",
    CTtr: "Tree Wall",
    FTtw: "Tree Wall",
    LOcg: "Cage",
    LTba: "Barricade",
    LTcr: "Crates",
    LTbr: "Barrel",
    LTbx: "Barrel",
    LTbs: "Barrel",
    LTex: "Barrel",
    LTg1: "Gate",
    LTg2: "Gate",
    LTg3: "Gate",
    LTg4: "Gate",
    LTe1: "Elven Gate",
    LTe2: "Elven Gate",
    LTe3: "Elven Gate",
    LTe4: "Elven Gate",
    ATg1: "Iron Gate",
    ATg2: "Iron Gate",
    ATg3: "Iron Gate",
    ATg4: "Iron Gate",
    DTg5: "Iron Gate",
    DTg6: "Iron Gate",
    DTg7: "Iron Gate",
    DTg8: "Iron Gate",
    DTg1: "DungeonGate",
    DTg2: "DungeonGate",
    DTg3: "DungeonGate",
    DTg4: "DungeonGate",
    LTlt: "Tree Wall",
    NTtw: "Tree Wall",
    WTtw: "Tree Wall",
    WTst: "Tree Wall",
    YTct: "Tree Wall",
    YTwt: "Tree Wall",
    YTst: "Tree Wall",
    YTft: "Tree Wall",
    VTlt: "Tree Wall",
    LTw0: "Stone Wall 0",
    LTw1: "Stone Wall 45",
    LTw2: "Stone Wall 90",
    LTw3: "Stone Wall 135",
    YT00: "Small Bridge 0 0",
    YT01: "Small Bridge 45 0",
    YT02: "Small Bridge 90 0",
    YT03: "Small Bridge 135 0",
    YT04: "Large Bridge 0 0",
    YT05: "Large Bridge 45 0",
    YT06: "Large Bridge 90 0",
    YT07: "Large Bridge 135 0",
    YT08: "Extra Large Bridge 0 0",
    YT09: "Extra Large Bridge 45 0",
    YT10: "Extra Large Bridge 90 0",
    YT11: "Extra Large Bridge 135 0",
    YT12: "Small Bridge 0 1",
    YT13: "Small Bridge 45 1",
    YT14: "Small Bridge 90 1",
    YT15: "Small Bridge 135 1",
    YT16: "Large Bridge 0 1",
    YT17: "Large Bridge 45 1",
    YT18: "Large Bridge 90 1",
    YT19: "Large Bridge 135 1",
    YT20: "Extra Large Bridge 0 1",
    YT21: "Extra Large Bridge 45 1",
    YT22: "Extra Large Bridge 90 1",
    YT23: "Extra Large Bridge 135 1",
    LT00: "Small Bridge 0 0",
    LT01: "Small Bridge 45 0",
    LT02: "Small Bridge 90 0",
    LT03: "Small Bridge 135 0",
    LT04: "Large Bridge 0 0",
    LT05: "Large Bridge 45 0",
    LT06: "Large Bridge 90 0",
    LT07: "Large Bridge 135 0",
    LT08: "Extra Large Bridge 0 0",
    LT09: "Extra Large Bridge 45 0",
    LT10: "Extra Large Bridge 90 0",
    LT11: "Extra Large Bridge 135 0",
    XTbd: "Building",
    XTvt: "Large Building",
    LTr1: "Small Bridge Ramp 135",
    LTr2: "Small Bridge Ramp 225",
    LTr3: "Small Bridge Ramp 315",
    LTr4: "Small Bridge Ramp 45",
    LTr5: "Small Bridge Ramp 135",
    LTr6: "Small Bridge Ramp 225",
    LTr7: "Small Bridge Ramp 315",
    LTr8: "Small Bridge Ramp 45",
    NTbd: "Ship",
    DTes: "Egg Sack",
    DTsh: "Tree Wall",
    YSdb: "destroyed bridge 45",
    YSdc: "destroyed bridge 135",
    XOkt: "_",
    XOk1: "_",
    XOk2: "_",
    DTc1: "CaveGate1",
    DTc2: "CaveGate2",
    DTsp: "Spikes",
    DTrc: "rock chunks",
    DTs0: "Large Force Bridge 0",
    DTs1: "Large Force Bridge 45",
    DTs2: "Large Force Bridge 90",
    DTs3: "Large Force Bridge 135",
    Dofw: "Forcewall",
    Dofv: "Forcewall45",
    YT24: "Small Bridge 0 1",
    YT25: "Small Bridge 45 1",
    YT26: "Small Bridge 90 1",
    YT27: "Small Bridge 135 1",
    YT28: "Large Bridge 0 1",
    YT29: "Large Bridge 45 1",
    YT30: "Large Bridge 90 1",
    YT31: "Large Bridge 135 1",
    YT32: "Extra Large Bridge 0 1",
    YT33: "Extra Large Bridge 45 1",
    YT34: "Extra Large Bridge 90 1",
    YT35: "Extra Large Bridge 135 1",
    YT36: "Small Bridge 0 0",
    YT37: "Small Bridge 45 0",
    YT38: "Small Bridge 90 0",
    YT39: "Small Bridge 135 0",
    YT40: "Large Bridge 0 0",
    YT41: "Large Bridge 45 0",
    YT42: "Large Bridge 90 0",
    YT43: "Large Bridge 135 0",
    YT44: "Extra Large Bridge 0 0",
    YT45: "Extra Large Bridge 45 0",
    YT46: "Extra Large Bridge 90 0",
    YT47: "Extra Large Bridge 135 0",
    ZTr0: "NagaRampSmall0",
    ZTr1: "NagaRampSmall90",
    ZTr2: "NagaRampSmall180",
    ZTr3: "NagaRampSmall270",
    ZTtw: "Tree Wall",
    ZTw0: "Stone Wall 0",
    ZTw1: "Stone Wall 45",
    ZTw2: "Stone Wall 90",
    ZTw3: "Stone Wall 135",
    ZTg1: "Gate",
    ZTg2: "Gate",
    ZTg3: "Gate",
    ZTg4: "Gate",
    ITtw: "Tree Wall",
    ZTd1: "RoundDoor",
    ZTd2: "RoundDoor",
    ZTd3: "RoundDoor",
    ZTd4: "RoundDoor",
    ZTd5: "RoundDoor",
    ZTd6: "RoundDoor",
    ZTd7: "RoundDoor",
    ZTd8: "RoundDoor",
    ITib: "Ice Bridge",
    ITi2: "Ice Bridge 45",
    ITi3: "Ice Bridge",
    ITi4: "Ice Bridge 45",
    ITg1: "Gate",
    ITg2: "Gate",
    ITg3: "Gate",
    ITg4: "Gate",
    ITw0: "Stone Wall 0",
    ITw1: "Stone Wall 45",
    ITw2: "Stone Wall 90",
    ITw3: "Stone Wall 135",
    LTt0: "Tree Bridge",
    LTt1: "Tree Bridge",
    LTt2: "Tree Bridge",
    LTt3: "Tree Bridge",
    LTt4: "Tree Bridge",
    ATt0: "Tree Bridge",
    ATt1: "Tree Bridge",
    LTt5: "Tree Bridge",
    ZTnc: "Ruins Naga Circle",
    ITf1: "Ice Floe",
    ITf2: "Ice Floe",
    ITf3: "Ice Floe",
    ITf4: "Ice Floe",
    ITx1: "Gate",
    ITx2: "Gate",
    ITx3: "Gate",
    ITx4: "Gate",
    ATtc: "Canopy Tree",
    OTtw: "Tree Wall",
    KTtw: "Tree Wall",
    ITig: "Igloo",
    DTrf: "Elevator",
    DTrx: "Elevator",
    XTmp: "magical pen",
    XTm5: "angled magical pen",
    XTmx: "magical pen wall",
    XTx5: "angled magical pen wall",
    ITcr: "Icey Rock",
    DTep: "elevator pathing block",
    ATwf: "Wharf",
    YTfb: "pathing blocker both",
    YTfc: "large pathing blocker both",
    YTlb: "line of sight blocker",
    Ytlc: "large line of sight blocker",
    YTpb: "pathing blocker ground",
    YTpc: "large pathing blocker ground",
    YTab: "pathing blocker air",
    YTac: "large pathing blocker air",
    ZTsg: "Gate to the Tomb of Sargeras",
    ZTsx: "Gate to the Tomb of Sargeras",
    DTfp: "Small Elevator",
    DTfx: "Small Elevator",
    DTlv: "Lever",
    YTce: "City Entrance",
    YTcx: "City Entrance",
    LTtc: "Large Bridge 0 0",
    LTtx: "Large Bridge 90 0",
    JTct: "Tree Wall",
    JTtw: "Tree Wall",
    ITtg: "Frozen Throne Gate",
    GTsh: "Tree Wall",
    BTrs: "Res Stone",
    BTrx: "Res Stone",
    OTsp: "Shimmering Portal",
    OTip: "Invisible Platform",
    OTis: "Invisible Platform Small",
    BTtc: "Canopy Tree",
    CTtc: "Canopy Tree",
    NTtc: "Canopy Tree",
    ZTtc: "Canopy Tree",
    ITtc: "Canopy Tree",
    IOt0: "_",
    IOt1: "_",
    IOt2: "_",
    LTrc: "rock chunks",
    LTrt: "rock chunks",
    YT48: "Extra Large Bridge 0 1",
    YT49: "Extra Large Bridge 45 1",
    YT50: "Extra Large Bridge 90 1",
    YT51: "Extra Large Bridge 135 1",
    OTds: "Demon Storm",
    ITag: "Rockin' Arthas",
    BTsc: "Support Column",
    LTs1: "Small Bridge Ramp 135",
    LTs2: "Small Bridge Ramp 225",
    LTs3: "Small Bridge Ramp 315",
    LTs4: "Small Bridge Ramp 45",
    LTs5: "Small Bridge Ramp 135",
    LTs6: "Small Bridge Ramp 225",
    LTs7: "Small Bridge Ramp 315",
    LTs8: "Small Bridge Ramp 45",
    Volc: "Volcano",
    Yts1: "Tree Wall",
    YTc1: "City Entrance",
    YTc2: "City Entrance",
    BTsk: "Support Column",
    YTc4: "City Entrance",
    BTs1: "Support Column",
    BTs2: "Statue",
    BTs3: "Statue",
    BTs4: "Statue",
    BTs5: "Statue",
    XTv1: "Large Building",
    XTv2: "Large Building",
    XTv3: "Large Building",
    XTv4: "Large Building",
    XTv5: "Large Building",
    XTv6: "Large Building",
    XTv7: "Large Building",
    XTv8: "Large Building",
    YTcn: "City Entrance",
    YT66: "Extra Large Bridge 0 1",
    YT67: "Extra Large Bridge 0 1",
    YY12: "Small Bridge 0 1",
    YY13: "Small Bridge 45 1",
    YY14: "Small Bridge 90 1",
    YY15: "Small Bridge 135 1",
    YY16: "Large Bridge 0 1",
    YY17: "Large Bridge 45 1",
    YY18: "Large Bridge 90 1",
    YY19: "Large Bridge 135 1",
    YY20: "Extra Large Bridge 0 1",
    YY21: "Extra Large Bridge 45 1",
    YY22: "Extra Large Bridge 90 1",
    YY23: "Extra Large Bridge 135 1",
    OG00: "Small Bridge 0 0",
    OG01: "Small Bridge 45 0",
    OG02: "Small Bridge 90 0",
    OG03: "Small Bridge 135 0",
    OG04: "Large Bridge 0 0",
    OG05: "Large Bridge 45 0",
    OG06: "Large Bridge 90 0",
    OG07: "Large Bridge 135 0",
    OG08: "Extra Large Bridge 0 0",
    OG09: "Extra Large Bridge 45 0",
    OG10: "Extra Large Bridge 90 0",
    OG11: "Extra Large Bridge 135 0",
    RW00: "Small Bridge 0 0",
    RW01: "Small Bridge 45 0",
    RW02: "Small Bridge 90 0",
    RW03: "Small Bridge 135 0",
    RW04: "Large Bridge 0 0",
    RW05: "Large Bridge 45 0",
    RW06: "Large Bridge 90 0",
    RW07: "Large Bridge 135 0",
    RW08: "Extra Large Bridge 0 0",
    RW09: "Extra Large Bridge 45 0",
    RW10: "Extra Large Bridge 90 0",
    RW11: "Extra Large Bridge 135 0",
    EB00: "Small Bridge 0 0",
    EB01: "Small Bridge 45 0",
    EB02: "Small Bridge 90 0",
    EB03: "Small Bridge 135 0",
    EB04: "Large Bridge 0 0",
    EB05: "Large Bridge 45 0",
    EB06: "Large Bridge 90 0",
    EB07: "Large Bridge 135 0",
    EB08: "Extra Large Bridge 0 0",
    EB09: "Extra Large Bridge 45 0",
    EB10: "Extra Large Bridge 90 0",
    EB11: "Extra Large Bridge 135 0",
    NB00: "Small Bridge 0 0",
    NB01: "Small Bridge 45 0",
    NB02: "Small Bridge 90 0",
    NB03: "Small Bridge 135 0",
    NB04: "Large Bridge 0 0",
    NB05: "Large Bridge 45 0",
    NB06: "Large Bridge 90 0",
    NB07: "Large Bridge 135 0",
    NB08: "Extra Large Bridge 0 0",
    NB09: "Extra Large Bridge 45 0",
    NB10: "Extra Large Bridge 90 0",
    NB11: "Extra Large Bridge 135 0",
    Ytsc: "Tree Wall",
    ITd1: "RoundDoor",
    ITd2: "RoundDoor",
    ITd3: "RoundDoor",
    ITd4: "RoundDoor",
    WGTR: "WayGate Ramp",
    NTiw: "Tree Wall",
}