export const itemCodes = {
    LTlt: 'Tree',
    nmer: 'Merchant',
    ntav: 'Tavern',
    ngol: 'Goldmine',
    amrc: 'Amulet of Recall',
    ankh: 'Ankh of Reincarnation',
    belv: 'Boots of Quel\'Thalas +6',
    bgst: 'Belt of Giant Strength +6',
    bspd: 'Boots of Speed',
    ccmd: 'Scepter of Mastery',
    ciri: 'Robe of the Magi +6',
    ckng: 'Crown of Kings +5',
    clsd: 'Cloak of Shadows',
    crys: 'Crystal Ball',
    desc: 'Kelen\'s Dagger of Escape',
    gemt: 'Gem of True Seeing',
    gobm: 'Goblin Land Mines',
    gsou: 'Soul Gem',
    guvi: 'Glyph of Ultravision',
    gfor: 'Glyph of Fortification',
    soul: 'Soul',
    mdpb: 'Medusa Pebble',
    rag1: 'Slippers of Agility +3',
    rat3: 'Claws of Attack +3',
    rin1: 'Mantle of Intelligence +3',
    rde1: 'Ring of Protection +2',
    rde2: 'Ring of Protection +3',
    rde3: 'Ring of Protection +4',
    rhth: 'Khadgar\'s Gem of Health',
    rst1: 'Gauntlets of Ogre Strength +3',
    ofir: 'Orb of Fire',
    ofro: 'Orb of Frost',
    olig: 'Orb of Lightning',
    oli2: 'Orb of Lightning',
    oven: 'Orb of Venom',
    odef: 'Orb of Darkness',
    ocor: 'Orb of Corruption',
    pdiv: 'Potion of Divinity',
    phea: 'Potion of Healing',
    pghe: 'Potion of Greater Healing',
    pinv: 'Potion of Invisibility',
    pgin: 'Potion of Greater Invisibility',
    pman: 'Potion of Mana',
    pgma: 'Potion of Greater Mana',
    pnvu: 'Potion of Invulnerability',
    pnvl: 'Potion of Lesser Invulnerability',
    pres: 'Potion of Restoration',
    pspd: 'Potion of Speed',
    rlif: 'Ring of Regeneration',
    rwiz: 'Sobi Mask',
    sfog: 'Horn of the Clouds',
    shea: 'Scroll of Healing',
    sman: 'Scroll of Mana',
    spro: 'Scroll of Protection',
    sres: 'Scroll of Restoration',
    ssil: 'Staff of Silence',
    stwp: 'Scroll of Town Portal',
    tels: 'Goblin Night Scope',
    tdex: 'Tome of Agility',
    texp: 'Tome of Experience',
    tint: 'Tome of Intelligence',
    tkno: 'Tome of Power',
    tstr: 'Tome of Strength',
    ward: 'Warsong Battle Drums',
    will: 'Wand of Illusion',
    wneg: 'Wand of Negation',
    rdis: 'Rune of Dispel Magic',
    rwat: 'Rune of the Watcher',
    fgrd: 'Red Drake Egg',
    fgrg: 'Stone Token',
    fgdg: 'Demonic Figurine',
    fgfh: 'Spiked Collar',
    fgsk: 'Book of the Dead',
    engs: 'Enchanted Gemstone',
    k3m1: 'Mooncrystal',
    modt: 'Mask of Death',
    sand: 'Scroll of Animate Dead',
    srrc: 'Scroll of Resurrection',
    sror: 'Scroll of the Beast',
    infs: 'Inferno Stone',
    shar: 'Ice Shard',
    wild: 'Amulet of the Wild',
    wswd: 'Sentry Wards',
    whwd: 'Healing Wards',
    wlsd: 'Wand of Lightning Shield',
    wcyc: 'Wand of the Wind',
    rnec: 'Rod of Necromancy',
    pams: 'Anti-magic Potion',
    clfm: 'Cloak of Flames',
    evtl: 'Talisman of Evasion',
    nspi: 'Necklace of Spell Immunity',
    lhst: 'The Lion Horn of Stormwind',
    kpin: 'Khadgar\'s Pipe of Insight',
    sbch: 'Scourge Bone Chimes',
    afac: 'Alleria\'s Flute of Accuracy',
    ajen: 'Ancient Janggo of Endurance',
    lgdh: 'Legion Doom-Horn',
    hcun: 'Hood of Cunning',
    mcou: 'Medallion of Courage',
    hval: 'Helm of Valor',
    cnob: 'Circlet of Nobility',
    prvt: 'Periapt of Vitality',
    tgxp: 'Tome of Greater Experience',
    mnst: 'Mana Stone',
    hlst: 'Health Stone',
    tpow: 'Tome of Knowledge',
    tst2: 'Tome of Strength +2',
    tin2: 'Tome of Intelligence +2',
    tdx2: 'Tome of Agility +2',
    rde0: 'Ring of Protection +1',
    rde4: 'Ring of Protection +5',
    rat6: 'Claws of Attack +6',
    rat9: 'Claws of Attack +9',
    ratc: 'Claws of Attack +12',
    ratf: 'Claws of Attack +15',
    manh: 'Manual of Health',
    pmna: 'Pendant of Mana',
    penr: 'Pendant of Energy',
    gcel: 'Gloves of Haste',
    totw: 'Talisman of the Wild',
    phlt: 'Phat Lewt',
    gopr: 'Glyph of Purification',
    ches: 'Cheese',
    mlst: 'Maul of Strength',
    rnsp: 'Ring of Superiority',
    brag: 'Bracer of Agility',
    sksh: 'Skull Shield',
    vddl: 'Voodoo Doll',
    sprn: 'Spider Ring',
    tmmt: 'Totem of Might',
    anfg: 'Ancient Figurine',
    lnrn: 'Lion\'s Ring',
    iwbr: 'Ironwood Branch',
    jdrn: 'Jade Ring',
    drph: 'Druid Pouch',
    hslv: 'Healing Salve',
    pclr: 'Clarity Potion',
    plcl: 'Lesser Clarity Potion',
    rej1: 'Minor Replenishment Potion',
    rej2: 'Lesser Replenishment Potion',
    rej3: 'Replenishment Potion',
    rej4: 'Greater Replenishment Potion',
    rej5: 'Lesser Scroll of Replenishment',
    rej6: 'Greater Scroll of Replenishment',
    sreg: 'Scroll of Regeneration',
    gold: 'Gold Coins',
    lmbr: 'Bundle of Lumber',
    fgun: 'Flare Gun',
    pomn: 'Potion of Omniscience',
    gomn: 'Glyph of Omniscience',
    wneu: 'Wand of Neutralization',
    silk: 'Spider Silk Broach',
    lure: 'Monster Lure',
    skul: 'Sacrificial Skull',
    moon: 'Moonstone',
    brac: 'Runed Bracers',
    vamp: 'Vampiric Potion',
    woms: 'Wand of Mana Stealing',
    tcas: 'Tiny Castle',
    tgrh: 'Tiny Great Hall',
    tsct: 'Ivory Tower',
    wshs: 'Wand of Shadowsight',
    tret: 'Tome of Retraining',
    sneg: 'Staff of Negation',
    stel: 'Staff of Teleportation',
    spre: 'Staff of Preservation',
    mcri: 'Mechanical Critter',
    spsh: 'Amulet of Spell Shield',
    sbok: 'Spell Book',
    ssan: 'Staff of Sanctuary',
    shas: 'Scroll of Speed',
    dust: 'Dust of Appearance',
    oslo: 'Orb of Slow',
    dsum: 'Diamond of Summoning',
    sor1: 'Shadow Orb +1',
    sor2: 'Shadow Orb +2',
    sor3: 'Shadow Orb +3',
    sor4: 'Shadow Orb +4',
    sor5: 'Shadow Orb +5',
    sor6: 'Shadow Orb +6',
    sor7: 'Shadow Orb +7',
    sor8: 'Shadow Orb +8',
    sor9: 'Shadow Orb +9',
    sora: 'Shadow Orb +10',
    sorf: 'Shadow Orb Fragment',
    fwss: 'Frost Wyrm Skull Shield',
    ram1: 'Ring of the Archmagi',
    ram2: 'Ring of the Archmagi',
    ram3: 'Ring of the Archmagi',
    ram4: 'Ring of the Archmagi',
    shtm: 'Shamanic Totem',
    shwd: 'Shimmerweed',
    btst: 'Battle Standard',
    skrt: 'Skeletal Artifact',
    thle: 'Thunder Lizard Egg',
    sclp: 'Secret Level Powerup',
    gldo: 'Orb of Kil\'jaeden',
    tbsm: 'Tiny Blacksmith',
    tfar: 'Tiny Farm',
    tlum: 'Tiny Lumber Mill',
    tbar: 'Tiny Barracks',
    tbak: 'Tiny Altar of Kings',
    mgtk: 'Magic Key Chain',
    stre: 'Staff of Reanimation',
    horl: 'Sacred Relic',
    hbth: 'Helm of Battlethirst',
    blba: 'Bladebane Armor',
    rugt: 'Runed Gauntlets',
    frhg: 'Firehand Gauntlets',
    gvsm: 'Gloves of Spell Mastery',
    crdt: 'Crown of the DeathLord',
    arsc: 'Arcane Scroll',
    scul: 'Scroll of the Unholy Legion',
    tmsc: 'Tome of Sacrifices',
    dtsb: 'Drek\'thar\'s Spellbook',
    grsl: 'Grimoire of Souls',
    arsh: 'Arcanite Shield',
    shdt: 'Shield of the DeathLord',
    shhn: 'Shield of Honor',
    shen: 'Enchanted Shield',
    thdm: 'Thunderlizard Diamond',
    stpg: 'Clockwork Penguin',
    shrs: 'Shimmerglaze Roast',
    bfhr: 'Bloodfeather\'s Heart',
    cosl: 'Celestial Orb of Souls',
    shcw: 'Shaman Claws',
    srbd: 'Searing Blade',
    frgd: 'Frostguard',
    envl: 'Enchanted Vial',
    rump: 'Rusty Mining Pick',
    mort: 'Mogrin\'s Report',
    srtl: 'Serathil',
    stwa: 'Sturdy War Axe',
    klmm: 'Killmaim',
    rots: 'Scepter of the Sea',
    axas: 'Ancestral Staff',
    mnsf: 'Mindstaff',
    schl: 'Scepter of Healing',
    asbl: 'Assassin\'s Blade',
    kgal: 'Keg of Ale',
    dphe: 'Thunder Phoenix Egg',
    dkfw: 'Keg of Thunderwater',
    dthb: 'Thunderbloom Bulb',
}