//exported from upgradedata.slk
export const upgradeCodes = {
    Rhme: "human melee attack",
    Rhra: "human ranged attack",
    Rhhb: "human hammer bounce",
    Rhar: "human armor",
    Rhgb: "human gyro bombs",
    Rhac: "human architecture",
    Rhde: "human footman defend",
    Rhan: "human animal breeding",
    Rhpt: "human priest training",
    Rhst: "human sorceress training",
    Rhla: "human leather armor",
    Rhri: "human rifleman plus range",
    Rhlh: "human lumber harvesting",
    Rhse: "human magical sentinal",
    Rhfl: "human flare",
    Rhss: "human control magic",
    Rhrt: "human rocket tank",
    Rhpm: "human backpack",
    Rhfc: "human flak cannon",
    Rhfs: "human frag shards",
    Rhcd: "human cloud research",
    Rhsb: "human sundering blades",
    Rome: "orc melee attack",
    Rora: "orc ranged attack",
    Roar: "orc armor",
    Rwdm: "orc war drums damage",
    Ropg: "orc pillage",
    Robs: "orc grunt berserk",
    Rows: "orc tauren smash",
    Roen: "orc raider ensare",
    Rovs: "orc wyvern venom spear",
    Rowd: "orc witch doctor training",
    Rost: "orc shaman training",
    Rosp: "orc spiked barricade",
    Rotr: "orc troll regeneration",
    Rolf: "orc liquid fire",
    Roch: "orc chaos conversion",
    Rowt: "orc spiritwalker training",
    Rorb: "orc reinforced defense",
    Robk: "orc berserkers",
    Ropm: "orc backpack",
    Robf: "orc naptha",
    Rume: "undead unholy strength",
    Rura: "undead creature attack",
    Ruar: "undead unholy armor",
    Ruac: "undead ghoul cannibalize",
    Rugf: "undead ghoul frenzy",
    Ruwb: "undead fiend web",
    Rusf: "undead gargoyle stone",
    Rune: "undead necromancer training",
    Ruba: "undead banshee training",
    Rufb: "undead frost wyrm breath",
    Rusl: "undead skeleton life span",
    Rucr: "undead creature armor",
    Rupc: "undead plague cloud",
    Rusm: "undead skeletal mastery",
    Rubu: "undead burrowing",
    Rusp: "undead avenger transform",
    Ruex: "undead exhume corpses",
    Rupm: "undead backpack",
    Resm: "nightelf strength of moon",
    Resw: "nightelf strength of wild",
    Rema: "nightelf moon armor",
    Rerh: "nightelf reinforced hides",
    Reuv: "nightelf ultravision",
    Renb: "nightelf nature's blessing",
    Resc: "nightelf scout",
    Remg: "nightelf moon glaive upgrade",
    Reib: "nightelf improved bows",
    Remk: "nightelf marksmanship",
    Redt: "nightelf DoT training",
    Redc: "nightelf DoC training",
    Resi: "nightelf abolish magic",
    Recb: "nightelf corrosive breath",
    Reht: "nightelf hippogryph taming",
    Repb: "nightelf impaling bolt",
    Rers: "nightelf resistant skin",
    Rehs: "nightelf hardened skin",
    Reeb: "nightelf enchanted bears",
    Reec: "nightelf enchanted crows",
    Rews: "nightelf well spring",
    Repm: "nightelf backpack",
    Rgfo: "glyph of fortification",
    Rguv: "glyph of ultravision",
    Rnen: "naga myrmidon ensnare",
    Rnsw: "naga sea witch training",
    Rnsi: "naga abolish magic",
    Rnat: "naga attack",
    Rnam: "naga armor",
    Rnsb: "naga submerge",
}