export const itemCodes = {
    ward: 'Warsong Battle Drums',
    wcyc: 'Wand of the Wind',
    wshs: 'Wand of Shadowsight',
    wneu: 'Wand of Neutralization',
    wneg: 'Wand of Negation',
    woms: 'Wand of Mana Stealing',
    wlsd: 'Wand of Lightning Shield',
    will: 'Wand of Illusion',
    vddl: 'Voodoo Doll',
    vamp: 'Vampiric Potion',
    ktrm: 'Urn of King Terenas',
    uflg: 'Undead Flag',
    tmmt: 'Totem of Might',
    tstr: 'Tome of Strength',
    tmsc: 'Tome of Sacrifices',
    tret: 'Tome of Retraining',
    tkno: 'Tome of Power',
    tpow: 'Tome of Knowledge',
    tint: 'Tome of Intelligence',
    tgxp: 'Tome of Greater Experience',
    texp: 'Tome of Experience',
    tdex: 'Tome of Agility',
    tlum: 'Tiny Lumber Mill',
    tgrh: 'Tiny Great Hall',
    tfar: 'Tiny Farm',
    tcas: 'Tiny Castle',
    tbsm: 'Tiny Blacksmith',
    tbar: 'Tiny Barracks',
    tbak: 'Tiny Altar of Kings',
    thdm: 'Thunderlizard Diamond',
    dthb: 'Thunderbloom Bulb',
    dphe: 'Thunder Phoenix Egg',
    thle: 'Thunder Lizard Egg',
    lhst: 'The Lion Horn of Stormwind',
    sehr: 'The Heart of Searinox',
    totw: 'Talisman of the Wild',
    evtl: 'Talisman of Evasion',
    kysn: 'Sun Key',
    stwa: 'Sturdy War Axe',
    fgrg: 'Stone Token',
    stel: 'Staff of Teleportation',
    ssil: 'Staff of Silence',
    ssan: 'Staff of Sanctuary',
    stre: 'Staff of Reanimation',
    spre: 'Staff of Preservation',
    sneg: 'Staff of Negation',
    fgfh: 'Spiked Collar',
    silk: 'Spider Silk Broach',
    sprn: 'Spider Ring',
    sbok: 'Spell Book',
    gsou: 'Soul Gem',
    soul: 'Soul',
    rwiz: 'Sobi Mask',
    sksh: 'Skull Shield',
    skrt: 'Skeletal Artifact',
    shwd: 'Shimmerweed',
    shrs: 'Shimmerglaze Roast',
    shdt: 'Shield of the Deathlord',
    shhn: 'Shield of Honor',
    shtm: 'Shamanic Totem',
    shcw: 'Shaman Claws',
    sorf: 'Shadow Orb Fragment',
    srtl: 'Serathil',
    wswd: 'Sentry Wards',
    sclp: 'Secret Level Powerup',
    srbd: 'Searing Blade',
    scul: 'Scroll of the Unholy Legion',
    sror: 'Scroll of the Beast',
    stwp: 'Scroll of Town Portal',
    shas: 'Scroll of Speed',
    srrc: 'Scroll of Resurrection',
    sres: 'Scroll of Restoration',
    sreg: 'Scroll of Regeneration',
    spro: 'Scroll of Protection',
    sman: 'Scroll of Mana',
    shea: 'Scroll of Healing',
    sand: 'Scroll of Animate Dead',
    sbch: 'Scourge Bone Chimes',
    rots: 'Scepter of the Sea',
    ccmd: 'Scepter of Mastery',
    schl: 'Scepter of Healing',
    skul: 'Sacrificial Skull',
    horl: 'Sacred Relic',
    rump: 'Rusty Mining Pick',
    rugt: 'Runed Gauntlets',
    brac: 'Runed Bracers',
    rwat: 'Rune of the Watcher',
    rspl: 'Rune of Spirit Link',
    rspd: 'Rune of Speed',
    rsps: 'Rune of Shielding',
    rres: 'Rune of Restoration',
    rreb: 'Rune of Rebirth',
    rman: 'Rune of Mana',
    rre1: 'Rune of Lesser Resurrection',
    rhe1: 'Rune of Lesser Healing',
    rhe2: 'Rune of Healing',
    rre2: 'Rune of Greater Resurrection',
    rma2: 'Rune of Greater Mana',
    rhe3: 'Rune of Greater Healing',
    rdis: 'Rune of Dispel Magic',
    rnec: 'Rod of Necromancy',
    ram4: 'Ring of the Archmagi',
    ram3: 'Ring of the Archmagi',
    ram2: 'Ring of the Archmagi',
    ram1: 'Ring of the Archmagi',
    rnsp: 'Ring of Superiority',
    rlif: 'Ring of Regeneration',
    rej3: 'Replenishment Potion',
    fgrd: 'Red Drake Egg',
    pspd: 'Potion of Speed',
    pres: 'Potion of Restoration',
    pomn: 'Potion of Omniscience',
    pman: 'Potion of Mana',
    pnvl: 'Potion of Lesser Invulnerability',
    pnvu: 'Potion of Invulnerability',
    pinv: 'Potion of Invisibility',
    phea: 'Potion of Healing',
    pgma: 'Potion of Greater Mana',
    pgin: 'Potion of Greater Invisibility',
    pghe: 'Potion of Greater Healing',
    pdiv: 'Potion of Divinity',
    phlt: 'Phat Lewt',
    prvt: 'Periapt of Vitality',
    pmna: 'Pendant of Mana',
    penr: 'Pendant of Energy',
    k3m2: 'Partial Key of the Three Moons',
    oflg: 'Orc Flag',
    oven: 'Orb of Venom',
    oslo: 'Orb of Slow',
    olig: 'Orb of Lightning',
    oli2: 'Orb of Lightning',
    ofro: 'Orb of Frost',
    ofir: 'Orb of Fire',
    odef: 'Orb of Darkness',
    ocor: 'Orb of Corruption',
    jpnt: 'Note to Jaina Proudmoore',
    nflg: 'Night Elf Flag',
    nspi: 'Necklace of Spell Immunity',
    moon: 'Moonstone',
    k3m1: 'Mooncrystal',
    kymn: 'Moon Key',
    lure: 'Monster Lure',
    rej1: 'Minor Replenishment Potion',
    mnsf: 'Mindstaff',
    mcou: 'Medallion of Courage',
    mcri: 'Mechanical Critter',
    mlst: 'Maul of Strength',
    modt: 'Mask of Death',
    manh: 'Manual of Health',
    mnst: 'Mana Stone',
    mgtk: 'Magic Key Chain',
    rej5: 'Lesser Scroll of Replenishment',
    rej2: 'Lesser Replenishment Potion',
    plcl: 'Lesser Clarity Potion',
    lgdh: 'Legion Doom-Horn',
    klmm: 'Killmaim',
    k3m3: 'Key of Three Moons',
    dkfw: 'Keg of Thunderwater',
    kgal: 'Keg of Ale',
    jdrn: 'Jade Ring',
    tsct: 'Ivory Tower',
    iwbr: 'Ironwood Branch',
    infs: 'Inferno Stone',
    shar: 'Ice Shard',
    flag: 'Human Flag',
    sfog: 'Horn of the Clouds',
    cnhn: 'Horn of Cenarius',
    hcun: 'Hood of Cunning',
    hval: 'Helm of Valor',
    hbth: 'Helm of Battlethirst',
    azhr: 'Heart of Aszune',
    hlst: 'Health Stone',
    whwd: 'Healing Wards',
    hslv: 'Healing Salve',
    grsl: 'Grimoire of Souls',
    rej6: 'Greater Scroll of Replenishment',
    rej4: 'Greater Replenishment Potion',
    gold: 'Gold Coins',
    tels: 'Goblin Night Scope',
    gobm: 'Goblin Land Mines',
    guvi: 'Glyph of Ultravision',
    gopr: 'Glyph of Purification',
    gomn: 'Glyph of Omniscience',
    gfor: 'Glyph of Fortification',
    gvsm: 'Gloves of Spell Mastery',
    gcel: 'Gloves of Haste',
    kygh: 'Ghost Key',
    gemt: 'Gem of True Seeing',
    gmfr: 'Gem Fragment',
    bzbf: 'Full Vial',
    frgd: 'Frostguard',
    fwss: 'Frost Wyrm Skull Shield',
    fgun: 'Flare Gun',
    frhg: 'Firehand Gauntlets',
    esaz: 'Essence of Aszune',
    envl: 'Enchanted Vial',
    shen: 'Enchanted Shield',
    engs: 'Enchanted Gemstone',
    bzbe: 'Empty Vial',
    dust: 'Dust of Appearance',
    drph: 'Druid Pouch',
    dsum: 'Diamond of Summoning',
    fgdg: 'Demonic Figurine',
    crys: 'Crystal Ball',
    crdt: 'Crown of the Deathlord',
    stpg: 'Clockwork Penguin',
    clsd: 'Cloak of Shadows',
    clfm: 'Cloak of Flames',
    pclr: 'Clarity Potion',
    cnob: 'Circlet of Nobility',
    ches: 'Cheese',
    cosl: 'Celestial Orb of Souls',
    lmbr: 'Bundle of Lumber',
    brag: 'Bracer of Agility',
    bspd: 'Boots of Speed',
    fgsk: 'Book of the Dead',
    kybl: 'Blood Key',
    blba: 'Bladebane Armor',
    btst: 'Battle Standard',
    arsh: 'Arcanite Shield',
    arsc: 'Arcane Scroll',
    pams: 'Anti-magic Potion',
    ankh: 'Ankh of Reincarnation',
    ajen: 'Ancient Janggo of Endurance',
    anfg: 'Ancient Figurine',
    axas: 'Ancestral Staff',
    wild: 'Amulet of the Wild',
    spsh: 'Amulet of Spell Shield',
    amrc: 'Amulet of Recall',
}