export const abilityCodes = {
    Aamk: "Attribute Bonus",
    ACs7: "Feral Spirit",
    ACtn: "Serpent Ward (Tentacles)",
    ANav: "Avatar (garithos)",
    ANha: "aga harvest",
    ANsh: "Shockwave",
    ACs8: "Spirit Beast",
    ANr2: "Reincarnation (akama)",
    Afbb: "Feedback",
    AGbu: "Naga Build",
    Acny: "Cyclone (naga)",
    Asb1: "Submerge",
    Asb2: "Submerge",
    Asb3: "Submerge",
    ANen: "Ensnare (Naga)",
    Andm: "Auto-Dispel Magic",
    ACfu: "Frost Armor (Autocast, Naga)",
    ANpa: "Parasite",
    Ahnl: "naga summoner null aoe roar",
    ANcl: "Channel",
    AOw2: "War Stomp (Cairn)",
    AOs2: "Shockwave (Cairne)", 
    AOr2: "Endurance Aura (Cairne)",
    AOr3: "Reincarnation (Cairne)",
    ANhw: "Healing Wave (rokhan)",
    ANhx: "Hex (rokhan)",
    Arsw: "Serpent Ward (rokhan)",
    AOls: "Voodoo Spirits (rokhan)",
    Arsq: "Summon Quillbeast (Rexxar)",
    Arsp: "Stampede (Rexxar)",
    ANbr: "Battle Roar",
    Arsg: "Summon Grizzly (campaign)",
    ANsb: "Storm Bolt (campaign)",
    ANcf: "Breath of Fire (Chen)",
    Acdb: "Drunken Brawler (Chen)",
    Acdh: "Drunken Haze (Chen)",
    Acef: "Earth, Storm, and Fire (Chen)",
    AOls: "Voodoo Spirits (Rokhan)",
    Aall: "llied building",
    Apit: "urchase item",
    Abdt: "urrow Detection (Fliers)",
    Aawa: "Lumber Harvest uses button art and position from the [Ahar] Harvest ability.",
    Adet: "passive detector ability",
    Arep: "peon/peasant repair ability",
    BSTN: "Stun buff",
    BPSE: "Pause buff",
    Amls: "Aerial Shackles",
    Bmlc: "Aerial Shackles Caster",
    Bmlt: "Aerial Shackles Target",
    AHta: "area of effect detection (scry)",
    Afbk: "Feedback",
    Afbt: "Feedback",
    Acmg: "Control Magic",
    AHdr: "Siphon Mana",
    Aflk: "Flak Cannons",
    Afsh: "Frag Shards",
    Aroc: "Rocket Attack",
    Amdf: "Magic Defense",
    AHbu: "Human Build",
    Asph: "Sphere",
    Asps: "Spell Steal",
    Aclf: "Cloud of Fog",
    AHfs: "Flame Strike",
    BHfs: "Impact art",
    XHfs: "Burning art",
    AHbn: "Banish",
    AHpx: "Summon Phoenix",
    Aphx: "Phoenix (morph)",
    Bphx: "Phoenix (progress bar)",
    Apxf: "Phoenix Fire",
    Bpxf: "Phoenix Fire",
    Agyb: "Flying Machine Bombs",
    Asth: "Storm Hammers",
    Agyv: "flying machine detection",
    Adef: "Defend",
    Afla: "Flare",
    Adts: "Magic Sentry (passive)",
    Ainf: "Inner Fire",
    Binf: "example of multiple attachment",
    Adis: "Dispel Magic",
    Ahea: "Heal",
    Aslo: "Slow",
    Aivs: "Invisibility",
    Aply: "Polymorph art notes:",
    AHbz: "Blizzard",
    AHwe: "Summon Water Elemental",
    AHab: "Brilliance Aura",
    AHmt: "Mass Teleport",
    AHtb: "Storm Bolt",
    AHtc: "Thunder Clap",
    AHbh: "Bash",
    AHav: "Avatar",
    AHhb: "Holy Light",
    AHds: "Divine Shield",
    AHad: "Devotion Aura",
    AHre: "Resurrection",
    Amil: "Militia",
    Amic: "Militia Conversion",
    Ahsb: "Sundering Blades",
    Xfhs: "damaged attachment effect, small",
    Xfhm: "medium",
    Xfhl: "large",
    Ahri: "assive - human rifleman plus range (Rhri)",
    Ahan: "assive - human animal breeding (Rhan)",
    Ahpe: "assive - phoenix (Fire and Egg)",
    Ahlh: "assive - human lumber harvesting (Rhlh)",
    APwt: "Rune of the Watcher",
    AIgf: "glyph of fortification",
    AIgu: "glyph of ultravision",
    AIbk: "Blink (item)",
    AIdm: "area of effect damage of destructables",
    AIem: "One time permanent hero experience gain, usually on a tome",
    AIfg: "Cloud of Fog",
    AIfl: "Flag ability",
    AIfm: "human flag",
    AIfn: "night elf flag",
    AIfo: "orc flag",
    AIfe: "undead flag",
    AIlm: "One time permanent hero level gain, usually on a tome",
    AIim: "One time permanent intelligence gain, usually on a Tome",
    AIxm: "One time permanent agi/int/str gain",
    AIhe: "single shot one target healing (potions, typically)",
    AIha: "single shot group area effect healing (scrolls, typically)",
    APh1: "single shot group area effect healing (powerup, lesser)",
    APh2: "single shot group area effect healing (powerup)",
    APh3: "single shot group area effect healing (powerup, greater)",
    AIvi: "short duration single target invisibility (potion)",
    AIpi: "continuous invisibility (ring)",
    AIvu: "brings up the invulnerability buff from CommonAbility",
    AIma: "single shot one target mana regain (potions, typically)",
    AImr: "single shot group area effect mana regain (scrolls, typically)",
    APmr: "single shot group area effect mana regain (rune)",
    APmg: "single shot group area effect mana regain (rune, greater)",
    AIre: "single shot one target life/mana restore (potion)",
    AIra: "single shot group area effect life/mana restore (scroll)",
    APra: "single shot group area effect life/mana restore (rune)",
    AIda: "area of effect application of a defensive buff (scroll of protection)",
    AIdb: "area of effect application of a defensive buff (scroll of protection) (with healing)",
    Bdef: "buff that AIda applies",
    AIta: "area of effect detection (crystal ball)",
    AItb: "area of effect application of a detected buff (dust of appearance)",
    AIrm: "continuous Mana regeneration (ring)",
    AIil: "Illusion generator",
    APdi: "Dispel effect (powerup)",
    AIdi: "Dispel effect",
    AIds: "dispel w/ cooldown",
    AIfb: "Hero attacks get fire damage bonus, persistent, Orb of Fire",
    AIf2: "Hero attacks get fire damage bonus, persistent, Orb of Fire",
    AIll: "Hero attacks get lightning damage bonus, persistent, Orb of Lightning",
    AIlb: "Hero attacks get lightning damage bonus, persistent, Orb of Lightning",
    AIob: "Hero attacks get frost damage bonus, persistent, Orb of Frost",
    AIpb: "Hero attacks get poison damage bonus, persistent, Orb of Venom",
    AIcb: "Hero attacks get corruption damage bonus, persistent, Orb of Corruption",
    AIdf: "Hero attacks get defilement/BA damage bonus, persistent, Orb of Defilement",
    AIsi: "Hero sight range increase, persistent, Telescope",
    AIso: "Soul Gem Hero soul theft ability",
    Asou: "Soul Gem Hero soul-carying ability - remove this to release the soul",
    BIsv: "caster buff for AIso",
    AIto: "daystone/nightstone",
    AIga: "magical acorn (tree restorer)",
    AIrc: "reincarnation (ankh)",
    AIrt: "recall (amulet)",
    AIte: "teleport for items",
    AItp: "town portal (scroll)",
    AIco: "scepter of mastery, command ability",
    AIts: "scepter of avarice, Transmute ability",
    AIfd: "figurine unit summon ability - red drake",
    AIbd: "blue drake",
    AIff: "furbolg",
    AIut: "furbolg tracker",
    AIfr: "rock golem",
    AIfu: "doom guard",
    AIfh: "felhound",
    AIfs: "skeleton",
    AIir: "Frost Revenant",
    AIuw: "Ursa Warrior",
    AIes: "Blue Dragonspawn Overseer",
    AIin: "infernal",
    AIpm: "place goblin land mine",
    AImn: "permanent mana bonus",
    AImm: "temporary max mana bonus",
    AIas: "temporary attack speed increase",
    AIs2: "mproved attack speed",
    AIva: "vampiric life steal ability",
    AIcf: "cloak of flames",
    BIcf: "Cloak of flames immolation buff",
    Arel: "regen",
    Arll: "regen lesser",
    AIhw: "item healing wards",
    AIsw: "item sentry wards",
    AIrr: "item roar",
    AIev: "item evasion",
    AImx: "item magic immunity",
    AIaa: "One time permanent attack damage gain",
    AImi: "One time permanent life gain",
    AIfc: "Flying Carpet",
    AIba: "Brilliance Aura (Item)",
    AIad: "Devotion Aura (Item)",
    AIcd: "Command Aura (Item)",
    AIwd: "War Drums Aura (Item)",
    AIar: "Trueshot Aura (Item)",
    AIae: "Endurance Aura (Item)",
    AIau: "Unholy Aura (Item)",
    AIav: "Vampiric Aura (Item)",
    AIrl: "Healing Salve",
    AIpr: "Clarity Potion",
    AIp1: "Generic Rejuv scroll/potion base uberalias",
    AIsl: "Scroll of Regeneration",
    BIrl: "Regeneration (Life)",
    BIrm: "Regeneration (Mana)",
    BIrg: "Regeneration (Life & Mana)",
    AIgo: "One time permanent gold gain",
    AIlu: "One time permanent lumber gain",
    AIfa: "Flare Gun",
    AIrv: "Potion of Omniscience",
    AIdc: "Wand of Neutralization",
    AIwb: "Spider Silk",
    AImo: "Monster Lure",
    AIri: "Random Item",
    Ablp: "Blight Placement",
    Aste: "mana steal",
    AIct: "Change TOD",
    AIpv: "Vampiric Potion",
    AIsr: "Spell Damage Reduction",
    AIbl: "Build Tiny Castle",
    AIbh: "Build Tiny Altar",
    AIbg: "Build Tiny Great Hall",
    AIbt: "Build Tiny Scout Tower",
    Ashs: "Shadowsight",
    Aret: "Tome of Retraining",
    AImt: "Staff of Teleportation",
    ANpr: "Staff of Preservation",
    Amec: "Mechanical Critter",
    ANss: "Spell Shield",
    ANse: "Spell Shield (AOE)",
    Aspb: "Spell book",
    AIrd: "Raise Dead",
    ANsa: "Staff of Sanctuary",
    AIsa: "Scroll of Haste",
    APsa: "Rune of Speed",
    AIsb: "Orb of Slow",
    AIos: "pecialart=",
    ANbs: "Orb of Darkness",
    Aspp: "Spirit Link (AOE)",
    AIrb: "Rebirth",
    AUds: "Dark Summoning",
    AIxs: "anti-magic shield",
    AIdv: "item divine shield",
    AIse: "item silence",
    AIpg: "item purge",
    AIps: "item purge (shamanistic totem)",
    AItg: "RESTNOBETA",
    AIfx: "orcish battle standard",
    AIgd: "Hero attacks get fire damage bonus, persistent, Orb of Gul'dan",
    AIbb: "tiny blacksmith",
    AIbr: "tiny lumber mill",
    AIbf: "tiny farm",
    AIbs: "tiny barracks",
    AInd: "campaign item reanimation",
    AIuf: "item unholy frenzy",
    AIcm: "item control magic",
    AIfz: "item death finger",
    AIdp: "item death pact",
    AIdd: "item defend",
    AIbx: "item Bash",
    AIwm: "item watery minion",
    AIsh: "item summon headhunter",
    AIgx: "item regen aura",
    AIhl: "item holy light",
    AIsz: "item slow poison",
    AIpz: "penguin squeek",
    AIfw: "item fire bonus",
    AIft: "item cold bonus",
    AIlx: "item lightning bonus",
    AIlp: "purge part of lightning orb",
    AIcs: "item critical strike",
    AIdd: "Passive Defense",
    AIcl: "item chain lightning",
    AIxk: "item berserk",
    AIdg: "Ritual Dagger (Instant)",
    AIg2: "Ritual Dagger (Regen)",
    ANic: "Incinerate",
    ANia: "Incinerate (Arrow)",
    ANso: "Soul Burn",
    ANlm: "Summon Lava Spawn",
    ANvc: "Volcano",
    ANsy: "Summon Factory 0",
    ANs1: "Summon Factory 1",
    ANs2: "Summon Factory 2",
    ANs3: "Summon Factory 3",
    ANcs: "Cluster Rockets 0",
    ANc1: "Cluster Rockets 1",
    ANc2: "Cluster Rockets 2",
    ANc3: "Cluster Rockets 3",
    ANeg: "Engineering Upgrade",
    ANrg: "Robo-Goblin 0",
    ANg1: "Robo-Goblin 1",
    ANg2: "Robo-Goblin 2",
    ANg3: "Robo-Goblin 3",
    ANde: "Demolish 0",
    ANd1: "Demolish 1",
    ANd2: "Demolish 2",
    ANd3: "Demolish 3",
    ANfy: "Factory 0",
    ANf1: "Factory 1",
    ANf2: "Factory 2",
    ANf3: "Factory 3",
    ANhs: "Healing Spray",
    ANab: "Acid Bomb",
    ANcr: "Chemical Rage",
    ANtm: "Transmute",
    AIgf: "lyph of foritifaciton",
    AIgu: "lyph of Ultravision",
    Aasl: "low on tornado",
    Atdg: "ornado damage",
    Atsp: "ornado Spin",
    Atwa: "ornado Wander",
    Asod: "pawn skeleton",
    ANak: "Orb of Annihilation",
    ANbl: "Blink (beastmaster bear)",
    Abu5: "Burrow (Barbed Arachnathid)",
    ACpa: "Parasite (Eredar)",
    ACsm: "Siphon Mana (Creep)",
    ACbn: "Banish",
    ACde: "Devour Magic (Creep)",
    Ache: "Chain Dispel",
    Ansk: "Hardened Skin",
    ANms: "Mana Shield",
    ANrf: "Rain of Fire",
    ACrg: "Rain of Fire (creep, greater)",
    ANfa: "Frost Arrows",
    AHca: "Cold Arrows",
    BHca: "Cold Arrow Buff (Non-Stacking)",
    Bcsd: "Cold Arrow Buff (Stacking)",
    Bcsi: "Cold Arrow Buff (Stack Info)",
    ANca: "Cleaving Attack",
    ACce: "Cleaving Attack (creep)",
    ANht: "Howl of Terror",
    Acht: "Howl of Terror",
    ANdo: "Doom",
    ANef: "Earth, Storm, and Fire",
    ANwk: "Wind Walk (Creep)",
    ANta: "Taunt (neutral)",
    ANdr: "Life Drain",
    ACdr: "Life Drain(Creep)",
    Aiun: "undead",
    Aion: "orc",
    Aihn: "human",
    Aien: "night elf",
    ANsg: "Summon Grizzly",
    ANsq: "Summon Quillbeast",
    ANsw: "Summon War Eagle",
    ANst: "Stampede",
    AChx: "Hex  (Creep)",
    Aenw: "Entangling Roots Seaweed Version (Creep)",
    AChV: "Healing Wave (creep)",
    ACsi: "Silence (Creep)",
    ACmf: "Mana Shield(Creep)",
    ACss: "Shadow Strike",
    ACcb: "Frost Bolt",
    ACbf: "Breath of Frost (creep)",
    ACbc: "Breath of Fire (creep)",
    ACfs: "Flame Strike",
    ANfs: "Flame Strike (improved creep)",
    ACmp: "Impale",
    ANbu: "Neutral Build",
    AInv: "Inventory",
    ANth: "Thorns",
    ANt2: "Thorns, dragon turtle, 2,2 button pos",
    ANmr: "Mind Rot",
    ANpr: "Preservation",
    ACpv: "Pulverize (sea giant)",
    ANss: "Spell Shield",
    ANbf: "Breath of Fire",
    ANdb: "Drunken Brawler",
    ANdh: "Drunken Haze",
    ANsi: "Silence",
    ANba: "Black Arrow",
    ACbk: "Black Arrow",
    ACch: "Charm (Creep)",
    ANch: "Charm",
    ANmo: "Monsoon",
    ACmo: "creep monsoon",
    ANwm: "Watery Minion",
    Aslp: "watery minion makrura",
    ANto: "Tornado",
    Basl: "Tornado - Slow Aura",
    Btsp: "Tornado - Spin",
    AChw: "Healing Ward (Creep)",
    ACr2: "Rejuvenation (Furbolg)",
    ACmi: "magic immunity (creep)",
    ACm2: "Magic Immunity (Archimonde)",
    ACm3: "Magic Immunity (Dragons)",
    ACpy: "creep polymorph",
    ACps: "creep possession",
    ACpu: "creep purge",
    Adtg: "general detect invis",
    ANtr: "general detect invis",
    Arng: "Revenge",
    ANdc: "Dark Conversion",
    SNdc: "Dark Conversion (Fast)",
    ANsl: "Soul Preservation",
    SNin: "Inferno (Tichondrius)",
    ANdp: "Dark Portal",
    ANrc: "Rain of Chaos",
    ANr3: "Rain of Chaos (modified button pos)",
    ANfd: "Finger of Death",
    ACfd: "Finger of Pain",
    ACf3: "Finger of Pain",
    Afod: "Finger of Death",
    Achd: "Cargo Hold Death",
    ANpi: "permanent immolation",
    BNpi: "Permanent immolation buff",
    Abun: "Bunker",
    Acar: "Cargo Hold",
    Aloa: "Cargo Load",
    Adro: "Cargo Unload",
    Adri: "Cargo Unload (Instant)",
    AAns: "Neutral Spell",
    Andt: "Reveal",
    ANgl: "Neutral G2L Exchange",
    ANlg: "Neutral L2G Exchange",
    ANre: "imparts ANrl, life regeneration, on nearby units, this ability is on Fountain of Life (nmoo)",
    ANrl: "persistent life regeneration, per unit",
    ANrm: "persistent mana regeneration, per unit",
    Sch2: "cargo hold meat wagon",
    Sch3: "cargo hold transport",
    Sch4: "cargo hold tank",
    Sch5: "cargo hold ship",
    Aneu: "'select hero to use' ability for neutral buildings",
    Ane2: "select any unit",
    Aall: "'select hero to use' ability for allied buildings",
    ANin: "Inferno",
    ANsp: "Spy",
    Asds: "Kaboom!",
    Asdg: "Kaboom! (clockwerk, level 1)",
    Asd2: "Kaboom! (clockwerk, level 2)",
    Asd3: "Kaboom! (clockwerk, level 3)",
    Amrf: "Medivh Crow Form",
    Anhe: "Neutral Unit Healing",
    ACsw: "Creep slow",
    ACtc: "Creep Thunder Clap",
    ACt2: "Creep Thunder Clap (Thunder Lizard)",
    ACtb: "Creep Storm Bolt",
    ACbb: "creep bloodlust (B hotkey version)",
    Afzy: "Quill Beast Frenzy (beastmaster)",
    ACbl: "creep bloodlust",
    ACcn: "creep cannibalize",
    ACdv: "Dragon Creep Devour",
    ANrn: "demon reincarnation",
    ANfb: "Creep Firebolt",
    Assp: "spawn spiderlings on death",
    Aspd: "spawn spiders on death",
    Aspy: "spawn hydra on death",
    Aspt: "spawn hydra hatchling on death",
    Ambd: "demon mana burn",
    Amnb: "version 2 mana burn",
    Ambb: "version 2 mana burn",
    ACsl: "creep sleep",
    Asla: "Sleep always",
    ACsp: "creeps sleeping",
    ACba: "creep brilliance aura",
    ACat: "creep trueshot aura",
    ACam: "anti magic shell",
    ACbh: "creep bash",
    ANbh: "beastmaster bash",
    ANb2: "beastmaster maul",
    ACbz: "creep blizzard",
    ACca: "creep carrion swarm",
    ACcl: "creep chain lightning",
    ACcw: "creep cold arrows",
    ACcr: "creep cripple",
    ACct: "creep critical strike",
    ACcs: "creep curse",
    ACcy: "creep cyclone",
    SCc1: "cenarius' cyclone",
    ACdc: "creep death coil",
    ACds: "creep divine shield",
    Aenr: "creep entangling roots",
    ACev: "creep evasion",
    ACes: "creep evasion 100%",
    ACff: "creep faerie fire",
    ACsf: "creep feral spirit",
    ACs9: "creep spirit pig",
    ACfb: "creep fire bolt",
    ACfr: "creep force of nature",
    ACfa: "creep frost armor (old)",
    ACf2: "creep frost armor (new, autocast)",
    ACfn: "creep frost nova",
    Ahr2: "archimonde's ghoul's lumber",
    Ahr3: "goblin shredders lumber",
    Anh1: "creep heal normal",
    Anh2: "creep heal high",
    ACim: "creep immolation",
    ACif: "creep inner fire",
    ACls: "creep lightning shield",
    Sloa: "burrow load",
    Slo3: "ship load",
    ACrf: "creep rain of fire",
    ACrd: "creep raise dead",
    ACrj: "creep rejuvenation",
    Ahrp: "human repair",
    ACro: "creep roar",
    ACr1: "skeletal orc champion roar",
    Aro1: "root Ancients",
    Aro2: "root ancient protector",
    ACsa: "creep searing arrows",
    Asid: "sell items",
    Asud: "sell units",
    ACsh: "creep shockwave",
    ACst: "trap shockwave",
    ACah: "creep thorns aura",
    ACua: "creep unholy aura",
    ACuf: "creep unholy frenzy",
    SCva: "vampiric attack",
    ACvp: "creep vampiric aura",
    Awrs: "generic creep war stomp",
    Awrh: "hydra creep war stomp",
    Awrg: "Sea Giant creep war stomp",
    ACav: "creep devotion aura",
    ACvs: "creep envenomed spears",
    ACwb: "creep web",
    Aarm: "mana regeneration aura",
    ACnr: "life regeneration aura creep",
    SNdd: "super death and decay",
    Adsm: "dispel magic",
    ACdm: "creep auto-dispel",
    ACd2: "creep auto-dispel (button pos 1,2)",
    SNeq: "super earthquake",
    SCae: "endurance aura",
    ACen: "ensnare",
    ACcv: "Crushing Wave",
    ACc2: "Crushing Wave (Dragon Turtle, 1,2 UI position)",
    ACc3: "Crushing Wave (Lesser Version)",
    ACwe: "summon sea elemental",
    Anei: "neutral interact",
    Apmf: "permanent flyer immolation",
    ACrk: "Neutral Resistant Skin",
    ACsk: "Neutral Resistant Skin (altered button pos)",
    ANfl: "Forked Lightning",
    ACfl: "Forked Lightning",
    Avng: "Vengeance",
    Amfl: "Mana Flare",
    Apsh: "Phase Shift",
    Aetl: "Ethereal",
    Asp1: "Sphere",
    Asp2: "Sphere",
    Asp3: "Sphere",
    Asp4: "Sphere",
    Asp5: "Sphere",
    Asp6: "Sphere",
    AEbu: "Night Elf Build",
    Agra: "Grab Tree",
    Assk: "Hardened Skin",
    Arsk: "Resistant Skin",
    Atau: "Taunt",
    AEbl: "Blink",
    AEfk: "Fan of Knives",
    AEsh: "Shadow Strike",
    BEsh: "Shadow Strike Non Stack Buff",
    BEsi: "Shadow Strike Stack Buff",
    AEsv: "Spirit of Vengeance",
    Slo2: "Cargo Load entangled mine",
    Aimp: "uttonpos=0,2",
    Amgl: "Moon Glaive",
    Amgi: "Moon Glaive",
    Amgr: "Moon Glaive",
    Aspo: "Slow poison",
    Bspo: "Slow Poison Non Stack Buff",
    Bssd: "Slow Poison Stack Buff",
    Ashm: "Shadow Meld passive nighttime cloaking ability, with its 'Hide' button",
    AIhm: "Shadow Meld (Item) passive cloaking ability, with its 'Hide' button",
    Ahid: "Shadow Meld passive nighttime cloaking ability, with its 'Hide' button",
    Sshm: "instant",
    Aesn: "Sentinel",
    Aesr: "Sentinel (no research)",
    Aeat: "Eat Tree",
    Ambt: "Moon pool mana battery",
    Awha: "Wisp Harvest",
    Awh2: "Wisp Harvest (Invulnerable)",
    Adtn: "Detonate",
    Awhe: "Wisp Healing",
    Aent: "Entangle",
    Aenc: "Entangled Gold Mine Cargo",
    Aroo: "Root",
    Abrf: "Bear Form",
    Arav: "Crow Form",
    Aadm: "Auto-Dispel Magic",
    Amim: "Spell Immunity",
    Ault: "Ultravision",
    Aegr: "lune's Grace",
    Acoa: "Couple",
    Aco2: "Couple (Archer)",
    Acoh: "rder=??",
    Aco3: "Couple (Hippo)",
    Adec: "Decouple",
    Acor: "Corrosive Breath",
    AEmb: "Mana Burn",
    AEim: "Immolation",
    AEev: "Evasion",
    AEme: "Metamorphosis",
    AEIl: "Illidan Metamorphosis",
    AEvi: "Evil Illidan Metamorphosis",
    AEer: "Entangling Roots",
    AEfn: "Force of Nature",
    AEah: "Thorns Aura",
    AEtq: "Tranquility",
    AEtr: "Tranquility life regeneration",
    AEst: "Scout",
    AHfa: "Searing Arrows",
    AEar: "Trueshot Aura",
    AEsf: "Starfall",
    AEsd: "Starfall life drain",
    AEsb: "beefy starfall - campaign spell",
    Afae: "Faerie Fire",
    Afa2: "Faerie Fire (storm crow form)",
    Acyc: "Cyclone",
    Arej: "Rejuvenation",
    Aren: "Renew",
    Aroa: "Roar",
    Ara2: "Roar (bear form)",
    Alit: "Lightning attack",
    Atol: "tree of life upgrade ability",
    Bbar: "used by creep ability",
    Xfns: "'damaged' attachment effect, small",
    Xfnm: "medium",
    Xfnl: "large",
    Aeib: "assive - nightelf improved bows (Reib)",
    Aemk: "assive - nightelf marksmanship (Remk)",
    Aews: "assive - nightelf well spring (Rews)",
    Abof: "Balls of Fire",
    Absk: "Berserk",
    Sbsk: "Berserker Upgrade",
    Arbr: "Reinforced Burrows Upgrade",
    Aast: "Ancestral Spirit",
    Adch: "Disenchant",
    Adcn: "Disenchant (new)",
    Acpf: "Corporeal Form",
    Aetf: "Ethereal Form",
    Aspl: "Spirit Link",
    Apak: "Pack Mule",
    Aliq: "Liquid Fire",
    Auco: "Unstable Concoction",
    AObu: "Orc Build",
    AOhw: "Healing Wave",
    AOhx: "Hex",
    AOsw: "Serpent Ward",
    AOvd: "Voodoo",
    Awfb: "Warlock Firebolt",
    Acha: "Chaos conversion",
    Abtl: "battle stations, load all peons into a bunker",
    Astd: "stand down, send peons back to work",
    Aens: "Ensnare",
    Bens: "Ensnare buff",
    Beng: "Ensnare buff on ground units",
    Bena: "Ensnare buff on air units",
    Awar: "Totem Smash, Pulverize, whatnot",
    Adev: "Devour",
    Bdvv: "Devour buff",
    Aprg: "Purge (classic)",
    Apg2: "Purge (expansion melee)",
    Alsh: "Lightning Shield",
    Ablo: "Bloodlust",
    Aeye: "Sentry Ward",
    Asta: "Stasis Trap spell",
    Bstt: "Stasis Trap trigger buff",
    Bsta: "Stasis Trap effect buff",
    Ahwd: "Healing Ward",
    Aoar: "Healing Ward Regeneration Aura",
    Aven: "Envenomed Spears",
    Apoi: "Poison Sting",
    Apo2: "Poison Sting (Orb of Venom)",
    Bpoi: "Poison Sting Non Stack Buff",
    Bpsd: "Poison Sting Stack Buff",
    BIpb: "Venom Non Stack Buff",
    BIpd: "Venom Stack Buff",
    Anit: "Tracking (Passive)",
    Asal: "Pillage (Passive)",
    Aspi: "Spiked Barricades (Passive)",
    Aakb: "War Drums Aura",
    AOwk: "Wind Walk",
    AOmi: "Mirror Image",
    AOcr: "Critical Strike",
    AOww: "Bladestorm",
    AOcl: "Chain Lightning",
    AOfs: "Far Sight",
    AOeq: "Earthquake",
    AOsh: "Shockwave",
    AOae: "Endurance Aura",
    AOre: "Reincarnation",
    AOsf: "Feral Spirit",
    AOws: "War Stomp (Chieftan)",
    Xfos: "'damaged' attachment effect, small",
    Xfom: "medium",
    Xfol: "large",
    Aobs: "assive - orc grunt berserk (Robs)",
    Aobk: "assive - orc berserkers (Robk)",
    Aorb: "assive - orc reinforced defense (Rorb)",
    Aosp: "assive - orc spiked barricade (Rosp)",
    Aoth: "assive - orc Ghost(icon only, orc, Aeth, unused)",
    Aotr: "assive - orc troll regeneration (Rotr)",
    AIpw: "item purge (wand of negation)",
    Bson: "rb of slow buff",
    AIno: "orb of slow Slow",
}