// ================================================================
// KNOWN FIELD DEFINITIONS   id -> { n: human name, t: default type }
// ================================================================
export const KNOWN = {
  // -- Units/Items --
  isit:{n:"Stock Initial After Start Delay",t:"int",c:"stats"},
  ista:{n:"Max Stacks",t:"int",c:"stats"},
  bdns:{n:"Looping Sound",t:"soundLabel",c:"sound"},

  iabi:{n:"Abilities",t:"abilityList",c:"abilities"},
  iarm:{n:"Armor Type",t:"armorType",c:"combat"},
  icid:{n:"Cooldown Group",t:"abilCode",c:"stats"},
  icla:{n:"Classification",t:"itemClass",c:"stats"},
  iclb:{n:"Tinting Color 3 (Blue)",t:"int",c:"art"},
  iclg:{n:"Tinting Color 2 (Green)",t:"int",c:"art"},
  iclr:{n:"Tinting Color 1 (Red)",t:"int",c:"art"},
  ides:{n:"Description",t:"string",c:"text"},
  idro:{n:"Can Be Dropped",t:"bool",c:"stats"},
  idrp:{n:"Dropped When Carrier Dies",t:"bool",c:"stats"},
  ifil:{n:"Model Used",t:"model",c:"art"},
  igol:{n:"Gold Cost",t:"int",c:"stats"},
  ihtp:{n:"Hit Points",t:"int",c:"stats"},
  iicd:{n:"Ignore Cooldown",t:"bool",c:"stats"},
  iico:{n:"Interface Icon",t:"icon",c:"art"},
  ilev:{n:"Level",t:"int",c:"stats"},
  ilum:{n:"Lumber Cost",t:"int",c:"stats"},
  ilvo:{n:"Level (Unclassified)",t:"int",c:"stats"},
  imor:{n:"Valid Target For Transformation",t:"bool",c:"stats"},
  ipaw:{n:"Can Be Sold To Merchants",t:"bool",c:"stats"},
  iper:{n:"Perishable",t:"bool",c:"stats"},
  ipow:{n:"Use Automatically When Acquired",t:"bool",c:"stats"},
  ipri:{n:"Priority",t:"int",c:"stats"},
  iprn:{n:"Include As Random Choice",t:"bool",c:"stats"},
  isca:{n:"Scaling Value",t:"real",c:"art"},
  isel:{n:"Can Be Sold By Merchants",t:"bool",c:"stats"},
  issc:{n:"Selection Size - Editor",t:"real",c:"art"},
  isst:{n:"Stock Start Delay",t:"int",c:"stats"},
  isto:{n:"Stock Maximum",t:"int",c:"stats"},
  istr:{n:"Stock Replenish Interval",t:"int",c:"stats"},
  iusa:{n:"Actively Used",t:"bool",c:"stats"},
  iuse:{n:"Number of Charges",t:"int",c:"stats"},
  ua1b:{n:"Attack 1 - Damage Base",t:"int",c:"combat"},
  ua1c:{n:"Attack 1 - Cooldown Time",t:"unreal",c:"combat"},
  ua1d:{n:"Attack 1 - Damage Number of Dice",t:"int",c:"combat"},
  ua1f:{n:"Attack 1 - Area of Effect (Full Damage)",t:"int",c:"combat"},
  ua1g:{n:"Attack 1 - Targets Allowed",t:"targetList",c:"combat"},
  ua1h:{n:"Attack 1 - Area of Effect (Medium Damage)",t:"int",c:"combat"},
  ua1m:{n:"Attack 1 - Projectile Art",t:"model",c:"combat"},
  ua1p:{n:"Attack 1 - Area of Effect Targets",t:"targetList",c:"combat"},
  ua1q:{n:"Attack 1 - Area of Effect (Small Damage)",t:"int",c:"combat"},
  ua1r:{n:"Attack 1 - Range",t:"int",c:"combat"},
  ua1s:{n:"Attack 1 - Damage Sides per Die",t:"int",c:"combat"},
  ua1t:{n:"Attack 1 - Attack Type",t:"attackType",c:"combat"},
  ua1w:{n:"Attack 1 - Weapon Type",t:"weaponType",c:"combat"},
  ua1z:{n:"Attack 1 - Projectile Speed",t:"int",c:"combat"},
  ua2b:{n:"Attack 2 - Damage Base",t:"int",c:"combat"},
  ua2c:{n:"Attack 2 - Cooldown Time",t:"unreal",c:"combat"},
  ua2d:{n:"Attack 2 - Damage Number of Dice",t:"int",c:"combat"},
  ua2f:{n:"Attack 2 - Area of Effect (Full Damage)",t:"int",c:"combat"},
  ua2g:{n:"Attack 2 - Targets Allowed",t:"targetList",c:"combat"},
  ua2h:{n:"Attack 2 - Area of Effect (Medium Damage)",t:"int",c:"combat"},
  ua2m:{n:"Attack 2 - Projectile Art",t:"model",c:"combat"},
  ua2p:{n:"Attack 2 - Area of Effect Targets",t:"targetList",c:"combat"},
  ua2q:{n:"Attack 2 - Area of Effect (Small Damage)",t:"int",c:"combat"},
  ua2r:{n:"Attack 2 - Range",t:"int",c:"combat"},
  ua2s:{n:"Attack 2 - Damage Sides per Die",t:"int",c:"combat"},
  ua2t:{n:"Attack 2 - Attack Type",t:"attackType",c:"combat"},
  ua2w:{n:"Attack 2 - Weapon Type",t:"weaponType",c:"combat"},
  ua2z:{n:"Attack 2 - Projectile Speed",t:"int",c:"combat"},
  uaap:{n:"Required Animation Names - Attachments",t:"stringList",c:"art"},
  uabi:{n:"Normal",t:"abilityList",c:"abilities"},
  uabr:{n:"AI Placement Radius",t:"unreal",c:"pathing"},
  uabt:{n:"AI Placement Type",t:"aiBuffer",c:"pathing"},
  uacq:{n:"Acquisition Range",t:"unreal",c:"combat"},
  uaen:{n:"Attacks Enabled",t:"attackBits",c:"combat"},
  uagi:{n:"Starting Agility",t:"int",c:"stats"},
  uagp:{n:"Agility per Level",t:"unreal",c:"stats"},
  ualp:{n:"Required Attachment Link Names",t:"stringList",c:"art"},
  uamn:{n:"Minimum Attack Range",t:"int",c:"combat"},
  uani:{n:"Required Animation Names",t:"stringList",c:"art"},
  uarm:{n:"Armor Type",t:"armorType",c:"combat"},
  uawt:{n:"Tooltip - Awaken",t:"string",c:"text"},
  ubba:{n:"Gold Bounty Awarded - Base",t:"int",c:"stats"},
  ubdg:{n:"Is a Building",t:"bool",c:"stats"},
  ubdi:{n:"Gold Bounty Awarded - Number of Dice",t:"int",c:"stats"},
  ubld:{n:"Build Time",t:"int",c:"stats"},
  uble:{n:"Animation - Blend Time (seconds)",t:"real",c:"art"},
  ubpr:{n:"Required Bone Names",t:"stringList",c:"art"},
  ubpx:{n:"Button Position (X)",t:"int",c:"art"},
  ubpy:{n:"Button Position (Y)",t:"int",c:"art"},
  ubs1:{n:"Attack 1 - Animation Backswing Point",t:"unreal",c:"combat"},
  ubs2:{n:"Attack 2 - Animation Backswing Point",t:"unreal",c:"combat"},
  ubsi:{n:"Gold Bounty Awarded - Sides per Die",t:"int",c:"stats"},
  ubsl:{n:"Construction",t:"soundLabel", c:"sound"},
  ubui:{n:"Structures Built",t:"unitList",c:"techtree"},
  ucam:{n:"Categorization - Campaign",t:"bool",c:"editor"},
  ucar:{n:"Transported Size",t:"int",c:"stats"},
  ucbo:{n:"Can Build On",t:"bool"},
  ucbs:{n:"Animation - Cast Backswing",t:"unreal",c:"art"},
  uclb:{n:"Tinting Color 3 (Blue)",t:"int",c:"art"},
  uclg:{n:"Tinting Color 2 (Green)",t:"int",c:"art"},
  uclr:{n:"Tinting Color 1 (Red)",t:"int",c:"art"},
  ucol:{n:"Collision Size",t:"unreal",c:"pathing"},
  ucpt:{n:"Animation - Cast Point",t:"unreal",c:"art"},
  ucs1:{n:"Attack 1 - Weapon Sound",t:"combatSound",c:"combat"},
  ucs2:{n:"Attack 2 - Weapon Sound",t:"combatSound",c:"combat"},
  ucua:{n:"Caster Upgrade Art",t:"icon",c:"art"},
  ucun:{n:"Caster Upgrade Names",t:"stringList",c:"text"},
  ucut:{n:"Caster Upgrade Tips",t:"stringList",c:"text"},
  udaa:{n:"Default Active Ability",t:"abilCode",c:"abilities"},
  udea:{n:"Death Type",t:"deathType",c:"combat"},
  udef:{n:"Defense Base",t:"int",c:"combat"},
  udep:{n:"Dependency Equivalents",t:"unitList",c:"techtree"},
  udl1:{n:"Attack 1 - Damage Loss Factor",t:"unreal",c:"combat"},
  udl2:{n:"Attack 2 - Damage Loss Factor",t:"unreal",c:"combat"},
  udp1:{n:"Attack 1 - Animation Damage Point",t:"unreal",c:"combat"},
  udp2:{n:"Attack 2 - Animation Damage Point",t:"unreal",c:"combat"},
  udro:{n:"Can Drop Items On Death",t:"bool",c:"editor"},
  udtm:{n:"Death Time (seconds)",t:"unreal",c:"art"},
  udty:{n:"Defense Type",t:"defenseType",c:"combat"},
  udu1:{n:"Attack 1 - Damage Upgrade Amount",t:"int",c:"combat"},
  udu2:{n:"Attack 2 - Damage Upgrade Amount",t:"int",c:"combat"},
  udup:{n:"Defense Upgrade Bonus",t:"int",c:"combat"},
  uept:{n:"Elevation - Sample Points",t:"int",c:"art"},
  uerd:{n:"Elevation - Sample Radius",t:"real",c:"art"},
  ufle:{n:"Can Flee",t:"bool",c:"stats"},
  ufma:{n:"Food Produced",t:"int",c:"stats"},
  ufoo:{n:"Food Cost",t:"int",c:"stats"},
  ufor:{n:"Formation Rank",t:"int",c:"stats"},
  ufrd:{n:"Fog of War - Sample Radius",t:"real",c:"art"},
  ugol:{n:"Gold Cost",t:"int",c:"stats"},
  ugor:{n:"Repair Gold Cost",t:"int",c:"stats"},
  uhab:{n:"Hero",t:"heroAbilityList",c:"abilities"},
  uhas:{n:"Hero Skin",t:"heroAbilityList",c:"abilities"},
  uabs:{n:"Normal Skin",t:"heroAbilityList",c:"abilities"},
  uhd1:{n:"Attack 1 - Damage Factor - Medium",t:"unreal",c:"combat"},
  uhd2:{n:"Attack 2 - Damage Factor - Medium",t:"unreal",c:"combat"},
  uhhb:{n:"Hero - Hide Hero Interface Icon",t:"bool",c:"stats"},
  uhhd:{n:"Hero - Hide Hero Death Message",t:"bool",c:"stats"},
  uhhm:{n:"Hero - Hide Hero Minimap Display",t:"bool",c:"stats"},
  uhom:{n:"Hide Minimap Display",t:"bool",c:"stats"},
  uhos:{n:"Display as Neutral Hostile",t:"bool",c:"editor"},
  uhot:{n:"Hotkey",t:"char",c:"text"},
  uhpm:{n:"Hit Points Maximum (Base)",t:"int",c:"stats"},
  uhpr:{n:"Hit Points Regeneration Rate",t:"unreal",c:"stats"},
  uhrt:{n:"Hit Points Regeneration Type",t:"regenType",c:"stats"},
  uibo:{n:"Can Be Built On",t:"bool"},
  uico:{n:"Icon - Game Interface",t:"icon",c:"art"},
  uimz:{n:"Projectile Impact - Z",t:"unreal",c:"art"},
  uine:{n:"Placeable In Editor",t:"bool",c:"editor"},
  uinp:{n:"Intelligence per Level",t:"unreal",c:"stats"},
  uint:{n:"Starting Intelligence",t:"int",c:"stats"},
  uisz:{n:"Projectile Impact - Z (Swimming)",t:"unreal",c:"art"},
  ulba:{n:"Lumber Bounty Awarded - Base",t:"int",c:"stats"},
  ulbd:{n:"Lumber Bounty Awarded - Number of Dice",t:"int",c:"stats"},
  ulbs:{n:"Lumber Bounty Awarded - Sides per Die",t:"int",c:"stats"},
  ulev:{n:"Level",t:"int",c:"stats"},
  ulfi:{n:"Looping Fade In Rate",t:"int",c:"sound"},
  ulfo:{n:"Looping Fade Out Rate",t:"int",c:"sound"},
  ulos:{n:"Use Extended Line of Sight",t:"bool",c:"art"},
  ulpx:{n:"Projectile Launch - X",t:"unreal",c:"art"},
  ulpy:{n:"Projectile Launch - Y",t:"unreal",c:"art"},
  ulpz:{n:"Projectile Launch - Z",t:"unreal",c:"art"},
  ulsz:{n:"Projectile Launch - Z (Swimming)",t:"unreal",c:"art"},
  ulum:{n:"Lumber Cost",t:"int",c:"stats"},
  ulur:{n:"Repair Lumber Cost",t:"int",c:"stats"},
  uma1:{n:"Attack 1 - Projectile Arc",t:"unreal",c:"combat"},
  uma2:{n:"Attack 2 - Projectile Arc",t:"unreal",c:"combat"},
  umas:{n:"Speed Maximum",t:"int",c:"movement"},
  umdl:{n:"Model File",t:"model",c:"art"},
  upor:{n:"Portrait Model File",t:"model",c:"art"},
  umh1:{n:"Attack 1 - Projectile Homing Enabled",t:"bool",c:"combat"},
  umh2:{n:"Attack 2 - Projectile Homing Enabled",t:"bool",c:"combat"},
  umis:{n:"Speed Minimum",t:"int",c:"movement"},
  umki:{n:"Items Made",t:"itemList",c:"techtree"},
  umpi:{n:"Mana Initial Amount",t:"int",c:"stats"},
  umpm:{n:"Mana Maximum",t:"int",c:"stats"},
  umpr:{n:"Mana Regeneration",t:"unreal",c:"stats"},
  umsl:{n:"Movement",t:"soundLabel",c:"sound"},
  umvf:{n:"Height Minimum",t:"unreal",c:"movement"},
  umvh:{n:"Height",t:"unreal",c:"movement"},
  umvr:{n:"Turn Rate",t:"unreal",c:"movement"},
  umvs:{n:"Speed Base",t:"int",c:"movement"},
  umvt:{n:"Type",t:"moveType",c:"movement"},
  umxp:{n:"Maximum Pitch Angle (degrees)",t:"real",c:"art"},
  umxr:{n:"Maximum Roll Angle (degrees)",t:"real",c:"art"},
  unam:{n:"Name",t:"string",c:"text"},
  unbm:{n:"Neutral Building - Shows Minimap Icon",t:"bool",c:"stats"},
  unbr:{n:"Neutral Building - Valid As Random Building",t:"bool",c:"stats"},
  unsf:{n:"Name - Editor Suffix",t:"string",c:"text"},
  uocc:{n:"Occluder Height",t:"unreal",c:"art"},
  uori:{n:"Orientation Interpolation",t:"int",c:"art"},
  upap:{n:"Placement Requires",t:"pathingListPrevent",c:"pathing"},
  upar:{n:"Placement Prevented By",t:"pathingListRequire",c:"pathing"},
  upat:{n:"Pathing Map",t:"pathingTexture",c:"pathing"},
  upaw:{n:"Placement Requires Water Radius",t:"unreal",c:"pathing"},
  upgr:{n:"Upgrades Used",t:"upgradeList",c:"techtree"},
  upoi:{n:"Point Value",t:"int",c:"stats"},
  upra:{n:"Primary Attribute",t:"attributeType",c:"stats"},
  upri:{n:"Priority",t:"int",c:"stats"},
  upro:{n:"Proper Names",t:"stringList",c:"text"},
  upru:{n:"Proper Names Used",t:"int",c:"text"},
  uprw:{n:"Propulsion Window (degrees)",t:"unreal",c:"art"},
  uqd1:{n:"Attack 1 - Damage Factor - Small",t:"unreal",c:"combat"},
  uqd2:{n:"Attack 2 - Damage Factor - Small",t:"unreal",c:"combat"},
  urac:{n:"Race",t:"unitRace",c:"stats"},
  urb1:{n:"Attack 1 - Range Motion Buffer",t:"unreal",c:"combat"},
  urb2:{n:"Attack 2 - Range Motion Buffer",t:"unreal",c:"combat"},
  ureq:{n:"Requirements",t:"techList",c:"techtree"},
  ures:{n:"Researches Available",t:"upgradeList",c:"techtree"},
  urev:{n:"Revives Dead Heros",t:"bool",c:"techtree"},
  urpg:{n:"Group Separation - Group Number",t:"int",c:"movement"},
  urpo:{n:"Group Separation - Enabled",t:"bool",c:"movement"},
  urpp:{n:"Group Separation - Parameter",t:"int",c:"movement"},
  urpr:{n:"Group Separation - Priority",t:"int",c:"movement"},
  urq1:{n:"Requirements - Tier 2",t:"techList",c:'techtree'},
  urq2:{n:"Requirements - Tier 3",t:"techList",c:'techtree'},
  urq3:{n:"Requirements - Tier 4",t:"techList",c:'techtree'},
  urq4:{n:"Requirements - Tier 5",t:"techList",c:'techtree'},
  urq5:{n:"Requirements - Tier 6",t:"techList",c:'techtree'},
  urq6:{n:"Requirements - Tier 7",t:"techList",c:'techtree'},
  urq7:{n:"Requirements - Tier 8",t:"techList",c:'techtree'},
  urq8:{n:"Requirements - Tier 9",t:"techList",c:'techtree'},
  urqa:{n:"Requirements - Levels",t:"intList",c:"techtree"},
  urqc:{n:"Requirements - Tiers Used",t:"int",c:"techtree"},
  ursl:{n:"Random",t:"soundLabel",c:"sound"},
  urtm:{n:"Repair Time",t:"int",c:"stats"},
  urun:{n:"Animation - Run Speed",t:"real",c:"art"},
  urva:{n:"Hero Revival Locations",t:"unitList"},
  usca:{n:"Scaling Value",t:"real",c:"art"},
  uscb:{n:"Scale Projectiles",t:"bool",c:"art"},
  usd1:{n:"Attack 1 - Damage Spill Distance",t:"unreal",c:"combat"},
  usd2:{n:"Attack 2 - Damage Spill Distance",t:"unreal",c:"combat"},
  usei:{n:"Items Sold",t:"itemList",c:"techtree"},
  useu:{n:"Units Sold",t:"unitList",c:"techtree"},
  usew:{n:"Selection Circle On Water",t:"bool",c:"art"},
  ushb:{n:"Shadow Texture (Building)",t:"shadowTexture",c:"art"},
  ushh:{n:"Shadow Image - Height",t:"real",c:"art"},
  ushr:{n:"Has Water Shadow",t:"bool",c:"art"},
  ushu:{n:"Shadow Image (Unit)",t:"shadowImage",c:"art"},
  ushw:{n:"Shadow Image - Width",t:"real",c:"art"},
  ushx:{n:"Shadow Image - Center X",t:"real",c:"art"},
  ushy:{n:"Shadow Image - Center Y",t:"real",c:"art"},
  usid:{n:"Sight Radius (Day)",t:"int",c:"stats"},
  usin:{n:"Sight Radius (Night)",t:"int",c:"stats"},
  usle:{n:"Sleeps",t:"bool",c:"stats"},
  uslz:{n:"Selection Circle - Height",t:"real",c:"art"},
  usma:{n:"Stock Maximum",t:"int",c:"stats"},
  usit:{n:"Stock Initial After Start Delay",t:"int",c:"stats"},
  usnd:{n:"Unit Sound Set",t:"unitSound",c:"sound"},
  uspa:{n:"Special",t:"modelList",c:"art"},
  uspe:{n:"Categorization - Special",t:"bool",c:"editor"},
  usr1:{n:"Attack 1 - Damage Spill Radius",t:"unreal",c:"combat"},
  usr2:{n:"Attack 2 - Damage Spill Radius",t:"unreal",c:"combat"},
  usrg:{n:"Stock Replenish Interval",t:"int",c:"stats"},
  ussc:{n:"Selection Scale",t:"real",c:"art"},
  ussi:{n:"Icon - Score Screen",t:"icon",c:"art"},
  usst:{n:"Stock Start Delay",t:"int",c:"stats"},
  ustp:{n:"Strength per Level",t:"unreal",c:"stats"},
  ustr:{n:"Starting Strength",t:"int",c:"stats"},
  utaa:{n:"Target",t:"modelList",c:"art"},
  utar:{n:"Targeted as",t:"targetList",c:"combat"},
  utc1:{n:"Attack 1 - Maximum Number of Targets",t:"int",c:"combat"},
  utc2:{n:"Attack 2 - Maximum Number of Targets",t:"int",c:"combat"},
  utcc:{n:"Allow Custom Team Color",t:"bool",c:"art"},
  utco:{n:"Team Color",t:"teamColor",c:"art"},
  util:{n:"Tilesets",t:"tilesetList",c:"editor"},
  utip:{n:"Tooltip - Basic",t:"string",c:"text"},
  utpr:{n:"Tooltip - Revive",t:"string",c:"text"},
  utra:{n:"Units Trained",t:"unitList",c:"techtree"},
  utss:{n:"Has Tileset Specific Data",t:"bool",c:"editor"},
  utub:{n:"Tooltip - Extended",t:"string",c:"text"},
  utyp:{n:"Unit Classification",t:"unitClass",c:"stats"},
  uub1:{n:"Unit Uber Tooltip",t:"string",c:"art"},
  uubs:{n:"Ground Texture",t:"uberSplat",c:"art"},
  uuch:{n:"Use Click Helper",t:"bool",c:"editor"},
  uupt:{n:"Upgrades To",t:"unitList",c:"techtree"},
  uver:{n:"Model File - Extra Versions",t:"versionFlags",c:"art"},
  uwal:{n:"Animation - Walk Speed",t:"real",c:"art"},
  uwu1:{n:"Attack 1 - Show UI",t:"bool",c:"combat"},
  uwu2:{n:"Attack 2 - Show UI",t:"bool",c:"combat"},
  // -- Abilities --
  aaea:{n:"Area Effect",t:"modelList",c:"art"},
  aani:{n:"Animation Names",t:"stringList",c:"art"},
  aare:{n:"Area of Effect",t:"unreal",c:"stats"},
  aart:{n:"Icon - Normal",t:"icon",c:"art"},
  abpx:{n:"Button Position - Normal (X)",t:"int",c:"art"},
  abpy:{n:"Button Position - Normal (Y)",t:"int",c:"art"},
  abs1:{n:"Maximum Life Absorbed",t:"unreal"},
  abs2:{n:"Maximum Mana Absorbed",t:"unreal"},
  abuf:{n:"Buffs",t:"buffList",c:"data"},
  aca1:{n:"Caster Attachment Point 2",t:"stringList",c:"art"},
  acac:{n:"Caster Attachments",t:"int",c:"art"},
  acap:{n:"Caster Attachment Point 1",t:"stringList",c:"art"},
  acas:{n:"Casting Time",t:"unreal",c:"stats"},
  acat:{n:"Caster",t:"modelList",c:"art"},
  acdn:{n:"Cooldown",t:"unreal",c:"stats"},
  achd:{n:"Check Dependencies",t:"bool",c:"techtree"},
  Adm1:{n:"Mana Loss",t:"unreal"},
  Adm2:{n:"Summoned Unit Damage",t:"unreal"},
  adur:{n:"Duration - Normal",t:"unreal",c:"stats"},
  aeat:{n:"Effect",t:"modelList",c:"art"},
  aeff:{n:"Effects",t:"effectList",c:"data"},
  aefl:{n:"Effect Sound (Looping)",t:"soundLabel",c:"sound"},
  aefs:{n:"Effect Sound",t:"soundLabel",c:"sound"},
  ahdu:{n:"Duration - Hero",t:"unreal",c:"stats"},
  aher:{n:"Hero Ability",t:"bool",c:"stats"},
  ahky:{n:"Hotkey - Normal",t:"char",c:"text"},
  aite:{n:"Item Ability",t:"bool",c:"stats"},
  Akb1:{n:"Attack Damage Increase",t:"unreal"},
  alev:{n:"Levels",t:"int",c:"stats"},
  alig:{n:"Lightning Effects",t:"lightningList",c:"art"},
  alsk:{n:"Level Skip Requirement",t:"int",c:"stats"},
  amac:{n:"Missile Arc",t:"unreal",c:"art"},
  amat:{n:"Missile Art",t:"modelList",c:"art"},
  amcs:{n:"Mana Cost",t:"int",c:"stats"},
  amho:{n:"Missile Homing Enabled",t:"bool",c:"art"},
  Ams1:{n:"Summoned Unit Damage",t:"unreal"},
  Ams2:{n:"Magic Damage Reduction",t:"unreal"},
  Ams3:{n:"Shield Life",t:"int"},
  Ams4:{n:"Mana Loss",t:"int"},
  amsp:{n:"Missile Speed",t:"int",c:"art"},
  anam:{n:"Name",t:"string",c:"text"},
  Ans5:{n:"Base Order ID",t:"orderString"},
  Ans6:{n:"Charge Owning Player",t:"bool"},
  ansf:{n:"Editor Suffix",t:"string",c:"text"},
  aord:{n:"Order String - Use/Turn On",t:"orderString",c:"text"},
  aorf:{n:"Order String - Deactivate",t:"orderString",c:"text"},
  aoro:{n:"Order String - Activate",t:"orderString",c:"text"},
  aoru:{n:"Order String - Turn Off",t:"orderString",c:"text"},
  Apl1:{n:"Aura Duration",t:"unreal"},
  Apl2:{n:"Damage per Second",t:"unreal"},
  Apl3:{n:"Duration of Plague Ward",t:"unreal"},
  Aplu:{n:"Plague Ward Unit Type",t:"unitCode"},
  apri:{n:"Priority for Spell Steal",t:"int",c:"stats"},
  arac:{n:"Race",t:"unitRace",c:"stats"},
  aran:{n:"Cast Range",t:"unreal",c:"stats"},
  arar:{n:"Icon - Research",t:"icon",c:"art"},
  areq:{n:"Requirements",t:"techList",c:"techtree"},
  aret:{n:"Tooltip - Learn",t:"string",c:"text"},
  arhk:{n:"Hotkey - Learn",t:"char",c:"text"},
  arlv:{n:"Required Level",t:"int",c:"stats"},
  Arm1:{n:"Amount Regenerated",t:"unreal"},
  Arm2:{n:"Percentage",t:"bool"},
  arpx:{n:"Button Position - Research (X)",t:"int",c:"art"},
  arpy:{n:"Button Position - Research (Y)",t:"int",c:"art"},
  arqa:{n:"Requirements - Levels",t:"intList",c:"techtree"},
  arut:{n:"Tooltip - Learn - Extended",t:"string",c:"text"},
  asat:{n:"Special",t:"modelList",c:"art"},
  aspt:{n:"Special Attachment Point",t:"stringList",c:"art"},
  ast1:{n:"Life Restored Factor",t:"unreal"},
  ast2:{n:"Mana Restored Factor",t:"unreal"},
  ata0:{n:"Target Attachment Point 1",t:"stringList",c:"art"},
  ata1:{n:"Target Attachment Point 2",t:"stringList",c:"art"},
  ata2:{n:"Target Attachment Point 3",t:"stringList",c:"art"},
  ata3:{n:"Target Attachment Point 4",t:"stringList",c:"art"},
  ata4:{n:"Target Attachment Point 5",t:"stringList",c:"art"},
  ata5:{n:"Target Attachment Point 6",t:"stringList",c:"art"},
  atac:{n:"Target Attachments",t:"int",c:"art"},
  atar:{n:"Targets Allowed",t:"targetList",c:"stats"},
  atat:{n:"Target",t:"modelList",c:"art"},
  atp1:{n:"Tooltip - Normal",t:"string",c:"text"},
  auar:{n:"Icon - Turn Off",t:"icon",c:"art"},
  aub1:{n:"Tooltip - Normal - Extended",t:"string",c:"text"},
  aubx:{n:"Button Position - Turn Off (X)",t:"int",c:"art"},
  auby:{n:"Button Position - Turn Off (Y)",t:"int",c:"art"},
  auhk:{n:"Hotkey - Turn Off",t:"char",c:"text"},
  ausk:{n:"Unit Skin List",t:"string",c:"data"},
  aut1:{n:"Tooltip - Turn Off",t:"string",c:"text"},
  auu1:{n:"Tooltip - Turn Off - Extended",t:"string",c:"text"},
  ave5:{n:"Life Regeneration Rate (per second)",t:"unreal"},
  Bgm1:{n:"Gold per Interval",t:"int"},
  Bgm2:{n:"Interval Duration",t:"unreal"},
  Bgm3:{n:"Max Number of Miners",t:"int"},
  Bgm4:{n:"Radius of Mining Ring",t:"unreal"},
  Bli1:{n:"Expansion Amount",t:"unreal"},
  Bli2:{n:"Creates Blight",t:"bool"},
  Blo1:{n:"Attack Speed Increase (%)",t:"unreal"},
  Blo2:{n:"Movement Speed Increase (%)",t:"unreal"},
  Blo3:{n:"Scaling Factor",t:"unreal"},
  bsk1:{n:"Movement Speed Increase",t:"unreal"},
  bsk2:{n:"Attack Speed Increase",t:"unreal"},
  bsk3:{n:"Damage Taken Increase",t:"unreal"},
  Btl1:{n:"Allowed Unit Type",t:"unitCode"},
  Btl2:{n:"Summon Busy Units",t:"bool"},
  Cac1:{n:"Attack Damage Increase",t:"unreal"},
  Cad1:{n:"Number of Corpses Raised",t:"int"},
  Can1:{n:"Hit Points per Second",t:"unreal"},
  Can2:{n:"Max Hit Points",t:"unreal"},
  Car1:{n:"Cargo Capacity",t:"int"},
  Cha1:{n:"New Unit Type",t:"unitCode"},
  Chd1:{n:"Movement Update Frequency",t:"unreal"},
  Chd2:{n:"Attack Update Frequency",t:"unreal"},
  Chd3:{n:"Summoned Unit Damage",t:"unreal"},
  Chl1:{n:"Unit Type Allowed",t:"unitCode"},
  Cmg2:{n:"Mana per Summoned Hitpoint",t:"unreal"},
  Cmg3:{n:"Charge for Current Life",t:"unreal"},
  coa1:{n:"Partner Unit Type",t:"unitCode"},
  coa2:{n:"Move To Partner",t:"bool"},
  coau:{n:"Resulting Unit Type",t:"unitCode"},
  Cor1:{n:"Damage Per Second",t:"unreal"},
  Cri1:{n:"Movement Speed Reduction (%)",t:"unreal"},
  Cri2:{n:"Attack Speed Reduction (%)",t:"unreal"},
  Cri3:{n:"Damage Reduction",t:"unreal"},
  Crs:{n:"Chance to Miss",t:"unreal"},
  Ctb1:{n:"Damage",t:"unreal"},
  Ctc1:{n:"Damage",t:"unreal"},
  Ctc2:{n:"Extra Damage To Target",t:"unreal"},
  Ctc3:{n:"Movement Speed Reduction",t:"unreal"},
  Ctc4:{n:"Attack Speed Reduction",t:"unreal"},
  cyc1:{n:"Can Be Dispelled",t:"bool"},
  dcp1:{n:"Partner Unit Type One",t:"unitCode"},
  dcp2:{n:"Partner Unit Type Two",t:"unitCode"},
  Dda1:{n:"Full Damage Radius",t:"unreal"},
  Dda2:{n:"Full Damage Amount",t:"unreal"},
  Dda3:{n:"Partial Damage Radius",t:"unreal"},
  Dda4:{n:"Partial Damage Amount",t:"unreal"},
  Def1:{n:"Damage Taken (%)",t:"unreal"},
  Def2:{n:"Damage Dealt (%)",t:"unreal"},
  Def3:{n:"Movement Speed Factor",t:"unreal"},
  Def4:{n:"Attack Speed Factor",t:"unreal"},
  Def5:{n:"Magic Damage Reduction",t:"unreal"},
  Def6:{n:"Chance to Deflect",t:"unreal"},
  Def7:{n:"Deflect Damage Taken (Piercing)",t:"unreal"},
  Def8:{n:"Deflect Damage Taken (Spells)",t:"unreal"},
  Det1:{n:"Detection Type",t:"detectionType"},
  Dev1:{n:"Max Creep Level",t:"int"},
  Dev2:{n:"Damage per Second",t:"unreal"},
  Dev3:{n:"Maximum Creep Level",t:"int"},
  Dtn1:{n:"Mana Loss (per unit)",t:"unreal"},
  Dtn2:{n:"Damage to Summoned Units",t:"unreal"},
  dvm1:{n:"Life Per Unit",t:"unreal"},
  dvm2:{n:"Mana Per Unit",t:"unreal"},
  dvm3:{n:"Life Per Buff",t:"unreal"},
  dvm4:{n:"Mana Per Buff",t:"unreal"},
  dvm5:{n:"Summoned Unit Damage",t:"unreal"},
  dvm6:{n:"Ignore Friendly Buffs",t:"bool"},
  Eah1:{n:"Damage Dealt to Attackers",t:"unreal"},
  Eah2:{n:"Damage is Percent Received",t:"bool"},
  Ear1:{n:"Damage Bonus (%)",t:"unreal"},
  Ear2:{n:"Melee Bonus",t:"bool"},
  Ear3:{n:"Ranged Bonus",t:"bool"},
  Ear4:{n:"Flat Bonus",t:"bool"},
  Eat1:{n:"Rip Delay",t:"unreal"},
  Eat2:{n:"Eat Delay",t:"unreal"},
  Eat3:{n:"Hit Points Gained",t:"unreal"},
  Ebl1:{n:"Maximum Range",t:"unreal"},
  Ebl2:{n:"Minimum Range",t:"unreal"},
  Eer1:{n:"Damage per Second",t:"unreal"},
  Eev1:{n:"Chance to Evade",t:"unreal"},
  Efk1:{n:"Damage Per Target",t:"unreal"},
  Efk2:{n:"Maximum Total Damage",t:"unreal"},
  Efk3:{n:"Maximum Number of Targets",t:"int"},
  Efk4:{n:"Maximum Speed Adjustment",t:"unreal"},
  Efn1:{n:"Number of Summoned Units",t:"int"},
  Efnu:{n:"Summoned Unit Type",t:"unitCode"},
  Egm1:{n:"Gold per Interval",t:"int"},
  Egm2:{n:"Interval Duration",t:"unreal"},
  Eim1:{n:"Damage per Interval",t:"unreal"},
  Eim2:{n:"Mana Drained per Second",t:"unreal"},
  Eim3:{n:"Buffer Mana Required",t:"unreal"},
  Emb1:{n:"Max Mana Drained",t:"unreal"},
  Emb2:{n:"Bolt Delay",t:"unreal"},
  Emb3:{n:"Bolt Lifetime",t:"unreal"},
  Eme1:{n:"Normal Form Unit",t:"unitCode"},
  Eme2:{n:"Morphing Flags",t:"morphFlags"},
  Eme3:{n:"Altitude Adjustment Duration",t:"unreal"},
  Eme4:{n:"Landing Delay Time",t:"unreal"},
  Eme5:{n:"Alternate Form Hit Point Bonus",t:"unreal"},
  Emeu:{n:"Alternate Form Unit",t:"unitCode"},
  Ens1:{n:"Air Unit Lower Duration",t:"unreal"},
  Ens2:{n:"Air Unit Height",t:"unreal"},
  Ens3:{n:"Melee Attack Range",t:"unreal"},
  ent1:{n:"Resulting Unit Type",t:"unitCode"},
  Esf1:{n:"Damage Dealt",t:"unreal"},
  Esf2:{n:"Damage Interval",t:"unreal"},
  Esf3:{n:"Building Reduction",t:"unreal"},
  Esh1:{n:"Decaying Damage",t:"unreal"},
  Esh2:{n:"Movement Speed Factor",t:"unreal"},
  Esh3:{n:"Attack Speed Factor",t:"unreal"},
  Esh4:{n:"Decay Power",t:"unreal"},
  Esh5:{n:"Initial Damage",t:"unreal"},
  Esn1:{n:"In Flight Sight Radius",t:"unreal"},
  Esn2:{n:"Hovering Sight Radius",t:"unreal"},
  Esn3:{n:"Hovering Height",t:"unreal"},
  Esn4:{n:"Number of Owls",t:"int"},
  Esv1:{n:"Number of Summoned Units",t:"int"},
  Esvu:{n:"Summoned Unit Type",t:"unitCode"},
  Eth1:{n:"Immune to Morph Effects",t:"bool"},
  Eth2:{n:"Does Not Block Buildings",t:"bool"},
  Etq1:{n:"Life Healed",t:"unreal"},
  Etq2:{n:"Heal Interval",t:"unreal"},
  Etq3:{n:"Building Reduction",t:"unreal"},
  exh1:{n:"Maximum Number of Corpses",t:"int"},
  exhu:{n:"Unit Type",t:"unitCode"},
  Fae1:{n:"Defense Reduction",t:"int"},
  Fae2:{n:"Always Autocast",t:"bool"},
  fak1:{n:"Damage Bonus",t:"unreal"},
  fak2:{n:"Medium Damage Factor",t:"unreal"},
  fak3:{n:"Small Damage Factor",t:"unreal"},
  fak4:{n:"Full Damage Radius",t:"unreal"},
  fak5:{n:"Half Damage Radius",t:"unreal"},
  fbk1:{n:"Max Mana Drained - Units",t:"unreal"},
  fbk2:{n:"Damage Ratio - Units (%)",t:"unreal"},
  fbk3:{n:"Max Mana Drained - Heros",t:"unreal"},
  fbk4:{n:"Damage Ratio - Heros (%)",t:"unreal"},
  fbk5:{n:"Summoned Damage",t:"unreal"},
  Fla1:{n:"Detection Type",t:"detectionType"},
  Fla2:{n:"Effect Delay",t:"unreal"},
  Fla3:{n:"Flare Count",t:"int"},
  flk1:{n:"Medium Damage Radius",t:"unreal"},
  flk2:{n:"Small Damage Radius",t:"unreal"},
  flk3:{n:"Full Damage Amount",t:"unreal"},
  flk4:{n:"Medium Damage Amount",t:"unreal"},
  flk5:{n:"Small Damage Amount",t:"unreal"},
  Gho1:{n:"Auto-Acquire Attack Targets",t:"bool"},
  Gho2:{n:"Immune to Morph Effects",t:"bool"},
  Gho3:{n:"Does Not Block Buildings",t:"bool"},
  Gld1:{n:"Max Gold",t:"int"},
  Gld2:{n:"Mining Duration",t:"unreal"},
  Gld3:{n:"Mining Capacity",t:"int"},
  gra1:{n:"Attach Delay",t:"unreal"},
  gra2:{n:"Remove Delay",t:"unreal"},
  gra3:{n:"Disabled Attack Index",t:"int"},
  gra4:{n:"Enabled Attack Index",t:"int"},
  gra5:{n:"Maximum Attacks",t:"int"},
  Gyd1:{n:"Maximum Number of Corpses",t:"int"},
  Gyd2:{n:"Radius of Gravestones",t:"unreal"},
  Gyd3:{n:"Radius of Corpses",t:"unreal"},
  Gydu:{n:"Corpse Unit Type",t:"unitCode"},
  Hab1:{n:"Mana Regeneration Increase",t:"unreal"},
  Hab2:{n:"Percent Bonus",t:"bool"},
  Had1:{n:"Armor Bonus",t:"unreal"},
  Had2:{n:"Percent Bonus",t:"bool"},
  Har1:{n:"Damage to Tree",t:"int"},
  Har2:{n:"Lumber Capacity",t:"int"},
  Har3:{n:"Gold Capacity",t:"int"},
  Hav1:{n:"Defense Bonus",t:"unreal"},
  Hav2:{n:"Hit Point Bonus",t:"unreal"},
  Hav3:{n:"Damage Bonus",t:"unreal"},
  Hav4:{n:"Magic Damage Reduction",t:"unreal"},
  Hbh1:{n:"Chance to Bash",t:"unreal"},
  Hbh2:{n:"Damage Multiplier",t:"unreal"},
  Hbh3:{n:"Damage Bonus",t:"unreal"},
  Hbh4:{n:"Chance to Miss",t:"unreal"},
  Hbh5:{n:"Never Miss",t:"bool"},
  Hbn1:{n:"Movement Speed Reduction (%)",t:"unreal"},
  Hbn2:{n:"Attack Speed Reduction (%)",t:"unreal"},
  Hbz1:{n:"Number of Waves",t:"int"},
  Hbz2:{n:"Damage",t:"unreal"},
  Hbz3:{n:"Number of Shards",t:"int"},
  Hbz4:{n:"Building Reduction",t:"unreal"},
  Hbz5:{n:"Damage Per Second",t:"unreal"},
  Hbz6:{n:"Maximum Damage per Wave",t:"unreal"},
  Hca1:{n:"Extra Damage",t:"unreal"},
  Hca2:{n:"Movement Speed Factor",t:"unreal"},
  Hca3:{n:"Attack Speed Factor",t:"unreal"},
  Hca4:{n:"Stack Flags",t:"stackFlags"},
  Hds1:{n:"Can Deactivate",t:"bool"},
  Hea1:{n:"Hit Points Gained",t:"unreal"},
  Hfa1:{n:"Damage Bonus",t:"unreal"},
  Hfs1:{n:"Full Damage Dealt",t:"unreal"},
  Hfs2:{n:"Full Damage Interval",t:"unreal"},
  Hfs3:{n:"Half Damage Dealt",t:"unreal"},
  Hfs4:{n:"Half Damage Interval",t:"unreal"},
  Hfs5:{n:"Building Reduction",t:"unreal"},
  Hfs6:{n:"Maximum Damage",t:"unreal"},
  Hhb1:{n:"Amount Healed/Damaged",t:"unreal"},
  Hmt1:{n:"Number of Units Teleported",t:"int"},
  Hmt2:{n:"Casting Delay",t:"unreal"},
  Hmt3:{n:"Use Teleport Clustering",t:"bool"},
  Hre1:{n:"Number of Corpses Raised",t:"int"},
  Hre2:{n:"Raised Units Are Invulnerable",t:"bool"},
  Htb1:{n:"Damage",t:"unreal"},
  Htc1:{n:"AOE Damage",t:"unreal"},
  Htc2:{n:"Specific Target Damage",t:"unreal"},
  Htc3:{n:"Movement Speed Reduction (%)",t:"unreal"},
  Htc4:{n:"Attack Speed Reduction (%)",t:"unreal"},
  hwdu:{n:"Ward Unit Type",t:"unitCode"},
  Hwe1:{n:"Summoned Unit Type",t:"unitCode"},
  Hwe2:{n:"Summoned Unit Count",t:"int"},
  Iaa1:{n:"Attack Modification",t:"int"},
  Iagi:{n:"Agility Bonus",t:"int"},
  Iarp:{n:"Armor Penalty",t:"int"},
  Iatt:{n:"Attack Bonus",t:"int"},
  Ibl1:{n:"Unit Created (per player race)",t:"unitList"},
  Icfd:{n:"Damage Per Duration",t:"int"},
  Icfm:{n:"Mana Used Per Second",t:"int"},
  Icfx:{n:"Extra Mana Required",t:"int"},
  Icre:{n:"Maximum Creep Level",t:"int"},
  ict1:{n:"New Time of Day - Hour",t:"int"},
  ict2:{n:"New Time of Day - Minute",t:"int"},
  Idam:{n:"Damage Bonus",t:"unreal"},
  idc1:{n:"Mana Loss Per Unit",t:"unreal"},
  idc2:{n:"Summoned Unit Damage",t:"unreal"},
  idc3:{n:"Maximum Dispelled Units",t:"int"},
  Idef:{n:"Defense Bonus",t:"int"},
  Idel:{n:"Delay For Target Effect",t:"unreal"},
  Idet:{n:"Detection Radius",t:"detectionType"},
  Idic:{n:"Damage Bonus Dice",t:"int"},
  Idid:{n:"Damage To Summoned Units",t:"int"},
  Idim:{n:"Mana Loss Per Unit",t:"int"},
  Idps:{n:"Damage Per Second",t:"unreal"},
  Ifa1:{n:"Detection Type",t:"detectionType"},
  Igl1:{n:"Upgrade Levels",t:"int"},
  Iglu:{n:"Upgrade Type",t:"upgradeCode"},
  Ihid:{n:"Hide Button",t:"bool"},
  Ihp2:{n:"Hit Points Gained",t:"int"},
  Ihpg:{n:"Hit Points Gained",t:"int"},
  Ihpr:{n:"Hit Points Regenerated Per Second",t:"int"},
  Ihps:{n:"Hit Points Restored",t:"int"},
  Iild:{n:"Damage Dealt (% of normal)",t:"unreal"},
  Iilw:{n:"Damage Received Multiplier",t:"unreal"},
  Iint:{n:"Intelligence Bonus",t:"int"},
  Ilif:{n:"Max Life Gained",t:"int"},
  Iman:{n:"Max Mana Gained",t:"int"},
  imo1:{n:"Number of Lures",t:"int"},
  imo2:{n:"Activation Delay",t:"unreal"},
  imo3:{n:"Lure Interval (seconds)",t:"unreal"},
  imou:{n:"Lure Unit Type",t:"unitCode"},
  Imp2:{n:"Mana Points Gained",t:"int"},
  Impg:{n:"Mana Points Gained",t:"int"},
  Imps:{n:"Mana Points Restored",t:"int"},
  Imrp:{n:"Mana Regeneration Bonus (as fraction of normal)",t:"unreal"},
  Imvb:{n:"Movement Speed Bonus",t:"int"},
  Inf1:{n:"Damage Increase (%)",t:"unreal"},
  Inf2:{n:"Defense Increase",t:"int"},
  Inf3:{n:"Autocast Range",t:"unreal"},
  Inf4:{n:"Life Regen Rate",t:"unreal"},
  inv1:{n:"Item Capacity",t:"int"},
  inv2:{n:"Drop Items On Death",t:"bool"},
  inv3:{n:"Can Use Items",t:"bool"},
  inv4:{n:"Can Get Items",t:"bool"},
  inv5:{n:"Can Drop Items",t:"bool"},
  Iob2:{n:"Chance To Hit Units (%)",t:"unreal"},
  Iob3:{n:"Chance To Hit Heros (%)",t:"unreal"},
  Iob4:{n:"Chance To Hit Summons (%)",t:"unreal"},
  Iob5:{n:"Enabled Attack Index",t:"int"},
  Iobu:{n:"Effect Ability",t:"abilCode"},
  ipmu:{n:"Unit Type",t:"unitCode"},
  ipv1:{n:"Damage Bonus",t:"unreal"},
  ipv2:{n:"Life Steal Amount",t:"unreal"},
  ipv3:{n:"Amount Is Raw Value",t:"bool"},
  irc2:{n:"Restored Life",t:"int"},
  irc3:{n:"Restored Mana (-1 for current)",t:"int"},
  Ircd:{n:"Delay After Death (seconds)",t:"int"},
  Irec:{n:"Maximum Number of Units",t:"int"},
  irl1:{n:"Life Regenerated",t:"unreal"},
  irl2:{n:"Mana Regenerated",t:"unreal"},
  irl3:{n:"Allow When Full",t:"fullFlags"},
  irl4:{n:"No Target Required",t:"bool"},
  irl5:{n:"Dispel On Attack",t:"bool"},
  Isib:{n:"Sight Range Bonus",t:"int"},
  Isn1:{n:"Summon 1 - Amount",t:"int"},
  Isn2:{n:"Summon 2 - Amount",t:"int"},
  Ispi:{n:"Movement Speed Increase",t:"unreal"},
  isr1:{n:"Damage Bonus",t:"unreal"},
  isr2:{n:"Damage Reduction",t:"unreal"},
  Ist1:{n:"Summon 1 - Unit Type",t:"unitCode"},
  Ist2:{n:"Summon 2 - Unit Type",t:"unitCode"},
  Isx1:{n:"Attack Speed Increase",t:"unreal"},
  Itp2:{n:"Use Teleport Clustering",t:"bool"},
  Itpm:{n:"Maximum Number of Units",t:"int"},
  Ivam:{n:"Life Stolen Per Attack",t:"unreal"},
  Ivs1:{n:"Transition Time (seconds)",t:"unreal"},
  Ixpg:{n:"Experience Gained",t:"int"},
  Ixs1:{n:"Damage To Summoned Units",t:"unreal"},
  Ixs2:{n:"Magic Damage Reduction",t:"unreal"},
  liq1:{n:"Extra Damage Per Second",t:"unreal"},
  liq2:{n:"Movement Speed Reduction",t:"unreal"},
  liq3:{n:"Attack Speed Reduction",t:"unreal"},
  liq4:{n:"Repairs Allowed",t:"bool"},
  Lit1:{n:"Graphic Delay",t:"unreal"},
  Lit2:{n:"Graphic Duration",t:"unreal"},
  Loa1:{n:"Allowed Unit Type",t:"unitCode"},
  Lsh1:{n:"Damage per Second",t:"unreal"},
  Mbt1:{n:"Mana Gained",t:"unreal"},
  Mbt2:{n:"Hit Points Gained",t:"unreal"},
  Mbt3:{n:"Autocast Requirement",t:"unreal"},
  Mbt4:{n:"Water Height",t:"unreal"},
  Mbt5:{n:"Regenerate Only At Night",t:"bool"},
  mec1:{n:"Number of Units Created",t:"int"},
  mfl1:{n:"Unit - Damage Per Mana Point",t:"unreal"},
  mfl2:{n:"Hero - Damage Per Mana Point",t:"unreal"},
  mfl3:{n:"Unit - Maximum Damage",t:"unreal"},
  mfl4:{n:"Hero - Maximum Damage",t:"unreal"},
  mfl5:{n:"Damage Cooldown",t:"unreal"},
  mfl6:{n:"Caster Only Splash",t:"bool"},
  Mil1:{n:"Normal Form Unit",t:"unitCode"},
  Mil2:{n:"Alternate Form Unit",t:"unitCode"},
  mim1:{n:"Magic Damage Factor",t:"unreal"},
  Min1:{n:"Activation Delay",t:"unreal"},
  Min2:{n:"Invisibility Transition Time",t:"unreal"},
  mls1:{n:"Damage Per Second",t:"unreal"},
  Nab1:{n:"Movement Speed Reduction (%)",t:"unreal"},
  Nab2:{n:"Attack Speed Reduction (%)",t:"unreal"},
  Nab3:{n:"Armor Penalty",t:"int"},
  Nab4:{n:"Primary Damage",t:"unreal"},
  Nab5:{n:"Secondary Damage",t:"unreal"},
  Nab6:{n:"Damage Interval",t:"unreal"},
  Nba1:{n:"Damage Bonus",t:"unreal"},
  Nba2:{n:"Number of Summoned Units",t:"int"},
  Nba3:{n:"Summoned Unit Duration (seconds)",t:"unreal"},
  Nbau:{n:"Summoned Unit Type",t:"unitCode"},
  Nbf5:{n:"Damage Per Second",t:"unreal"},
  Nbr1:{n:"Damage Increase",t:"unreal"},
  nca1:{n:"Distributed Damage Factor",t:"unreal"},
  Nch1:{n:"Maximum Creep Level",t:"int"},
  Ncl1:{n:"Follow Through Time",t:"unreal"},
  Ncl2:{n:"Target Type",t:"channelType"},
  Ncl3:{n:"Options",t:"channelFlags"},
  Ncl4:{n:"Art Duration",t:"unreal"},
  Ncl5:{n:"Disable Other Abilities",t:"bool"},
  Ncl6:{n:"Base Order ID",t:"orderString"},
  Ncr5:{n:"Move Speed Bonus (Info Panel Only)",t:"unreal"},
  Ncr6:{n:"Attack Speed Bonus (Info Panel Only)",t:"unreal"},
  Ncs1:{n:"Damage Amount",t:"unreal"},
  Ncs2:{n:"Damage Interval",t:"unreal"},
  Ncs3:{n:"Missile Count",t:"int"},
  Ncs4:{n:"Max Damage",t:"unreal"},
  Ncs5:{n:"Building Damage Factor",t:"unreal"},
  Ncs6:{n:"Effect Duration",t:"unreal"},
  Ndc1:{n:"Race to Convert",t:"unitRace"},
  Ndc2:{n:"Conversion Unit",t:"unitCode"},
  Nde1:{n:"Chance to Demolish",t:"unreal"},
  Nde2:{n:"Damage Multiplier (Buildings)",t:"unreal"},
  Nde3:{n:"Damage Multiplier (Units)",t:"unreal"},
  Nde4:{n:"Damage Multiplier (Heroes)",t:"unreal"},
  Ndo1:{n:"Damage Per Second",t:"unreal"},
  Ndo2:{n:"Number of Summoned Units",t:"int"},
  Ndo3:{n:"Summoned Unit Duration (seconds)",t:"unreal"},
  Ndou:{n:"Summoned Unit Type",t:"unitCode"},
  Ndp1:{n:"Spawned Units",t:"unitList"},
  Ndp2:{n:"Minimum Number of Units",t:"int"},
  Ndp3:{n:"Maximum Number of Units",t:"int"},
  Ndr1:{n:"Hit Points Drained",t:"unreal"},
  Ndr2:{n:"Mana Points Drained",t:"unreal"},
  Ndr3:{n:"Drain Interval (seconds)",t:"unreal"},
  Ndr4:{n:"Life Transferred Per Second",t:"unreal"},
  Ndr5:{n:"Mana Transferred Per Second",t:"unreal"},
  Ndr6:{n:"Bonus Life Factor",t:"unreal"},
  Ndr7:{n:"Bonus Life Decay",t:"unreal"},
  Ndr8:{n:"Bonus Mana Factor",t:"unreal"},
  Ndr9:{n:"Bonus Mana Decay",t:"unreal"},
  Ndt1:{n:"Gold Cost",t:"int"},
  Ndt2:{n:"Lumber Cost",t:"int"},
  Ndt3:{n:"Detection Type",t:"detectionType"},
  Nef1:{n:"Summoned Unit Types",t:"unitList"},
  Neg1:{n:"Move Speed Bonus",t:"unreal"},
  Neg2:{n:"Damage Bonus",t:"unreal"},
  Neg3:{n:"Ability Upgrade 1",t:"heroAbilityList"},
  Neg4:{n:"Ability Upgrade 2",t:"heroAbilityList"},
  Neg5:{n:"Ability Upgrade 3",t:"heroAbilityList"},
  Neg6:{n:"Ability Upgrade 4",t:"heroAbilityList"},
  Neu1:{n:"Activation Radius",t:"unreal"},
  Neu2:{n:"Interaction Type",t:"interactionFlags"},
  Neu3:{n:"Show Select Unit Button",t:"bool"},
  Neu4:{n:"Show Unit Indicator",t:"bool"},
  Nfd1:{n:"Graphic Delay",t:"unreal"},
  Nfd2:{n:"Graphic Duration",t:"unreal"},
  Nfd3:{n:"Damage",t:"unreal"},
  Nfy1:{n:"Spawn Interval",t:"unreal"},
  Nfy2:{n:"Leash Range",t:"unreal"},
  Nfyu:{n:"Spawn Unit ID",t:"unitCode"},
  Nhs6:{n:"Wave Count",t:"int"},
  Nic1:{n:"Bonus Damage Multiplier",t:"unreal"},
  Nic2:{n:"Death Damage Full Amount",t:"unreal"},
  Nic3:{n:"Death Damage Full Area",t:"unreal"},
  Nic4:{n:"Death Damage Half Amount",t:"unreal"},
  Nic5:{n:"Death Damage Half Area",t:"unreal"},
  Nic6:{n:"Death Damage Delay",t:"unreal"},
  Nlm2:{n:"Split Delay",t:"unreal"},
  Nlm3:{n:"Split Attack Count",t:"int"},
  Nlm4:{n:"Max Hitpoint Factor",t:"unreal"},
  Nlm5:{n:"Life Duration Split Bonus",t:"unreal"},
  Nlm6:{n:"Generation Count",t:"int"},
  Nmr1:{n:"Mana Drained per Second",t:"unreal"},
  Nms1:{n:"Mana per Hit Point",t:"unreal"},
  Nms2:{n:"Damage Absorbed (%)",t:"unreal"},
  Npa5:{n:"Summoned Unit Count",t:"int"},
  Npa6:{n:"Summoned Unit Duration",t:"unreal"},
  Npr1:{n:"Building Types Allowed",t:"pickFlags"},
  Nrc1:{n:"Ability for Unit Creation",t:"abilCode"},
  Nrc2:{n:"Number of Units Created",t:"int"},
  Nrg5:{n:"Strength Bonus",t:"int"},
  Nrg6:{n:"Defense Bonus",t:"int"},
  Nsa1:{n:"Building Types Allowed",t:"pickFlags"},
  Nsa2:{n:"Hero Regeneration Delay",t:"unreal"},
  Nsa3:{n:"Unit Regeneration Delay",t:"unreal"},
  Nsa4:{n:"Magic Damage Reduction",t:"unreal"},
  Nsa5:{n:"Hit Points Per Second",t:"unreal"},
  Nse1:{n:"Shield Cooldown Time",t:"unreal"},
  Nsi1:{n:"Attacks Prevented",t:"silenceFlags"},
  Nsi2:{n:"Chance To Miss (%)",t:"unreal"},
  Nsi3:{n:"Movement Speed Modifier",t:"unreal"},
  Nsi4:{n:"Attack Speed Modifier",t:"unreal"},
  Nsl1:{n:"Unit to Preserve",t:"unitCode"},
  Nso1:{n:"Damage Amount",t:"unreal"},
  Nso2:{n:"Damage Period",t:"unreal"},
  Nso3:{n:"Damage Penalty",t:"unreal"},
  Nso4:{n:"Movement Speed Reduction (%)",t:"unreal"},
  Nso5:{n:"Attack Speed Reduction (%)",t:"unreal"},
  Nsp1:{n:"Gold Cost per Structure",t:"int"},
  Nsp2:{n:"Lumber Cost per Use",t:"int"},
  Nsp3:{n:"Detection Type",t:"detectionType"},
  Nst1:{n:"Beasts Per Second",t:"int"},
  Nst2:{n:"Beast Collision Radius",t:"unreal"},
  Nst3:{n:"Damage Amount",t:"unreal"},
  Nst4:{n:"Damage Radius",t:"unreal"},
  Nst5:{n:"Damage Delay",t:"unreal"},
  Nsy1:{n:"Spawn Interval",t:"unreal"},
  Nsy2:{n:"Spawn Unit ID",t:"unitCode"},
  Nsy3:{n:"Spawn Unit Duration",t:"unreal"},
  Nsy4:{n:"Spawn Unit Offset",t:"unreal"},
  Nsy5:{n:"Leash Range",t:"unreal"},
  Nsyu:{n:"Factory Unit ID",t:"unitCode"},
  Ntm1:{n:"Gold Cost Factor",t:"unreal"},
  Ntm2:{n:"Lumber Cost Factor",t:"unreal"},
  Ntm3:{n:"Max Creep Level",t:"int"},
  Ntm4:{n:"Allow Bounty",t:"bool"},
  Ntou:{n:"Summoned Unit Type",t:"unitCode"},
  Nvc1:{n:"Rock Ring Count",t:"int"},
  Nvc2:{n:"Wave Count",t:"int"},
  Nvc3:{n:"Wave Interval",t:"unreal"},
  Nvc4:{n:"Building Damage Factor",t:"unreal"},
  Nvc5:{n:"Full Damage Amount",t:"unreal"},
  Nvc6:{n:"Half Damage Factor",t:"unreal"},
  Nvcu:{n:"Destructible ID",t:"unitCode"},
  Oae1:{n:"Movement Speed Increase (%)",t:"unreal"},
  Oae2:{n:"Attack Speed Increase (%)",t:"unreal"},
  Oar1:{n:"Amount of Hit Points Regenerated",t:"unreal"},
  Oar2:{n:"Percentage",t:"bool"},
  Ocl1:{n:"Damage per Target",t:"unreal"},
  Ocl2:{n:"Number of Targets Hit",t:"int"},
  Ocl3:{n:"Damage Reduction per Target",t:"unreal"},
  Ocr1:{n:"Chance to Critical Strike",t:"unreal"},
  Ocr2:{n:"Damage Multiplier",t:"unreal"},
  Ocr3:{n:"Damage Bonus",t:"unreal"},
  Ocr4:{n:"Chance to Evade",t:"unreal"},
  Ocr5:{n:"Never Miss",t:"bool"},
  Oeq1:{n:"Effect Delay",t:"unreal"},
  Oeq2:{n:"Damage per Second to Buildings",t:"unreal"},
  Oeq3:{n:"Units Slowed (%)",t:"unreal"},
  Oeq4:{n:"Final Area",t:"unreal"},
  Ofs1:{n:"Detection Type",t:"detectionType"},
  Omi1:{n:"Number of Images",t:"int"},
  Omi2:{n:"Damage Dealt (%)",t:"unreal"},
  Omi3:{n:"Damage Taken (%)",t:"unreal"},
  Omi4:{n:"Animation Delay",t:"unreal"},
  Ore1:{n:"Reincarnation Delay",t:"unreal"},
  Osf1:{n:"Summoned Unit",t:"unitCode"},
  Osf2:{n:"Number of Summoned Units",t:"int"},
  Osh1:{n:"Damage",t:"unreal"},
  Osh2:{n:"Maximum Damage",t:"unreal"},
  Osh3:{n:"Distance",t:"unreal"},
  Osh4:{n:"Final Area",t:"unreal"},
  Owk1:{n:"Transition Time",t:"unreal"},
  Owk2:{n:"Movement Speed Increase (%)",t:"unreal"},
  Owk3:{n:"Backstab Damage",t:"unreal"},
  Owk4:{n:"Backstab Damage",t:"bool"},
  Oww1:{n:"Damage Per Second",t:"unreal"},
  Oww2:{n:"Magic Damage Reduction",t:"unreal"},
  Ply1:{n:"Maximum Creep Level",t:"int"},
  Ply2:{n:"Morph Units - Ground",t:"unitList"},
  Ply3:{n:"Morph Units - Air",t:"unitList"},
  Ply4:{n:"Morph Units - Amphibious",t:"unitList"},
  Ply5:{n:"Morph Units - Water",t:"unitList"},
  Poa1:{n:"Extra Damage",t:"unreal"},
  Poa2:{n:"Damage per Second",t:"unreal"},
  Poa3:{n:"Attack Speed Factor",t:"unreal"},
  Poa4:{n:"Movement Speed Factor",t:"unreal"},
  Poa5:{n:"Stacking Type",t:"stackFlags"},
  Poi1:{n:"Damage per Second",t:"unreal"},
  Poi2:{n:"Attack Speed Factor",t:"unreal"},
  Poi3:{n:"Movement Speed Factor",t:"unreal"},
  Poi4:{n:"Stacking Type",t:"stackFlags"},
  Pos1:{n:"Maximum Creep Level",t:"int"},
  Pos2:{n:"Damage Amplification",t:"unreal"},
  Pos3:{n:"Target Is Invulnerable",t:"bool"},
  Pos4:{n:"Target Is Magic Immune",t:"bool"},
  Prg1:{n:"Movement Update Frequency",t:"int"},
  Prg2:{n:"Attack Update Frequency",t:"int"},
  Prg3:{n:"Summoned Unit Damage",t:"unreal"},
  Prg4:{n:"Unit Pause Duration",t:"unreal"},
  Prg5:{n:"Hero Pause Duration",t:"unreal"},
  Prg6:{n:"Mana Loss",t:"int"},
  pxf1:{n:"Initial Damage",t:"unreal"},
  pxf2:{n:"Damage Per Second",t:"unreal"},
  Rai1:{n:"Units Summoned (Type One)",t:"int"},
  Rai2:{n:"Units Summoned (Type Two)",t:"int"},
  Rai3:{n:"Unit Type One",t:"unitCode"},
  Rai4:{n:"Unit Type Two",t:"unitCode"},
  Raiu:{n:"Unit Type For Limit Check",t:"unitCode"},
  Rej1:{n:"Hit Points Gained",t:"unreal"},
  Rej2:{n:"Mana Points Gained",t:"unreal"},
  Rej3:{n:"Allow When Full",t:"fullFlags"},
  Rej4:{n:"No Target Required",t:"bool"},
  Rep1:{n:"Repair Cost Ratio",t:"unreal"},
  Rep2:{n:"Repair Time Ratio",t:"unreal"},
  Rep3:{n:"Powerbuild Cost",t:"unreal"},
  Rep4:{n:"Powerbuild Rate",t:"unreal"},
  Rep5:{n:"Naval Range Bonus",t:"unreal"},
  Roa1:{n:"Damage Increase (%)",t:"unreal"},
  Roa2:{n:"Defense Increase",t:"int"},
  Roa3:{n:"Life Regeneration Rate",t:"unreal"},
  Roa4:{n:"Mana Regen",t:"unreal"},
  Roa5:{n:"Prefer Hostiles",t:"bool"},
  Roa6:{n:"Prefer Friendlies",t:"bool"},
  Roa7:{n:"Max Units",t:"int"},
  Roo1:{n:"Rooted Weapons",t:"attackBits"},
  Roo2:{n:"Uprooted Weapons",t:"attackBits"},
  Roo3:{n:"Rooted Turning",t:"bool"},
  Roo4:{n:"Uprooted Defense Type",t:"defenseTypeInt"},
  Rpb3:{n:"Minimum Life Required",t:"unreal"},
  Rpb4:{n:"Minimum Mana Required",t:"unreal"},
  Rpb5:{n:"Maximum Units Charged To Caster",t:"int"},
  Rpb6:{n:"Maximum Units Affected",t:"int"},
  Rtn1:{n:"Accepts Gold",t:"bool"},
  Rtn2:{n:"Accepts Lumber",t:"bool"},
  Sal1:{n:"Salvage Cost Ratio",t:"unreal"},
  Sal2:{n:"Accumulation Step",t:"int"},
  Sds1:{n:"Building Damage Factor",t:"unreal"},
  Sds6:{n:"Explodes on Death",t:"bool"},
  Shm1:{n:"Fade Duration",t:"unreal"},
  Shm2:{n:"Day/Night Duration",t:"unreal"},
  Shm3:{n:"Action Duration",t:"unreal"},
  sla1:{n:"Sleep Once",t:"bool"},
  sla2:{n:"Allow On Any Player Slot",t:"bool"},
  Slo1:{n:"Movement Speed Factor",t:"unreal"},
  Slo2:{n:"Attack Speed Factor",t:"unreal"},
  Slo3:{n:"Always Autocast",t:"bool"},
  Sod1:{n:"Number of Units",t:"int"},
  Sod2:{n:"Unit Type",t:"unitCode"},
  Spa1:{n:"Spider Capacity",t:"int"},
  spb1:{n:"Spell List",t:"abilityList"},
  spb2:{n:"Shared Spell Cooldown",t:"bool"},
  spb3:{n:"Minimum Spells",t:"int"},
  spb4:{n:"Maximum Spells",t:"int"},
  spb5:{n:"Base Order ID",t:"orderString"},
  spl1:{n:"Distributed Damage Factor",t:"unreal"},
  spl2:{n:"Maximum Number of Targets",t:"int"},
  Spo1:{n:"Damage Per Second",t:"unreal"},
  Spo2:{n:"Movement Speed Factor",t:"unreal"},
  Spo3:{n:"Attack Speed Factor",t:"unreal"},
  Spo4:{n:"Stacking Type",t:"stackFlags"},
  Ssk1:{n:"Chance to Reduce Damage (%)",t:"unreal"},
  Ssk2:{n:"Minimum Damage",t:"unreal"},
  Ssk3:{n:"Ignored Damage",t:"unreal"},
  Ssk4:{n:"Include Ranged Damage",t:"bool"},
  Ssk5:{n:"Include Melee Damage",t:"bool"},
  Sta1:{n:"Activation Delay",t:"unreal"},
  Sta2:{n:"Detection Radius",t:"unreal"},
  Sta3:{n:"Detonation Radius",t:"unreal"},
  Sta4:{n:"Stun Duration",t:"unreal"},
  Stau:{n:"Ward Unit Type",t:"unitCode"},
  Tau1:{n:"Prefer Hostiles",t:"int"},
  Tau2:{n:"Prefer Friendlies",t:"int"},
  Tau3:{n:"Max Units",t:"int"},
  Tdg1:{n:"Damage Per Second",t:"unreal"},
  Tdg2:{n:"Medium Damage Radius",t:"unreal"},
  Tdg3:{n:"Medium Damage Per Second",t:"unreal"},
  Tdg4:{n:"Small Damage Radius",t:"unreal"},
  Tdg5:{n:"Small Damage Per Second",t:"unreal"},
  tpi1:{n:"Required Unit Type",t:"unitCode"},
  tpi2:{n:"Converted Unit Type",t:"unitCode"},
  Tsp1:{n:"Air Time (seconds)",t:"unreal"},
  Tsp2:{n:"Minimum Hit Interval (seconds)",t:"unreal"},
  Uan1:{n:"Number of Corpses Raised",t:"int"},
  Uan3:{n:"Inherit Upgrades",t:"bool"},
  Uau1:{n:"Movement Speed Increase (%)",t:"unreal"},
  Uau2:{n:"Life Regeneration Increase (%)",t:"unreal"},
  Uau3:{n:"Percent Bonus",t:"bool"},
  Uav1:{n:"Attack Damage Stolen (%)",t:"unreal"},
  Ucb5:{n:"Max Units Summoned",t:"int"},
  Ucb6:{n:"Kill On Caster Death",t:"bool"},
  Uco5:{n:"Max Damage",t:"unreal"},
  Uco6:{n:"Move Speed Bonus",t:"unreal"},
  Ucs3:{n:"Distance",t:"unreal"},
  Ucs4:{n:"Final Area",t:"unreal"},
  Udc1:{n:"Amount Healed/Damaged",t:"unreal"},
  Udd1:{n:"Max Life Drained per Second (%)",t:"unreal"},
  Udd2:{n:"Building Reduction",t:"unreal"},
  Udp3:{n:"Mana Conversion As Percent",t:"bool"},
  Udp4:{n:"Life Conversion As Percent",t:"bool"},
  Udp5:{n:"Leave Target Alive",t:"bool"},
  Uds1:{n:"Maximum Units",t:"int"},
  Uds2:{n:"Casting Delay (seconds)",t:"unreal"},
  Ufa1:{n:"Armor Duration",t:"unreal"},
  Ufa2:{n:"Armor Bonus",t:"unreal"},
  Ufn1:{n:"Area of Effect Damage",t:"unreal"},
  Ufn2:{n:"Specific Target Damage",t:"unreal"},
  Uhf1:{n:"Attack Speed Bonus (%)",t:"unreal"},
  Uhf2:{n:"Damage per Second",t:"unreal"},
  Uim1:{n:"Wave Distance",t:"unreal"},
  Uim2:{n:"Wave Time (seconds)",t:"unreal"},
  Uim3:{n:"Damage Dealt",t:"unreal"},
  Uim4:{n:"Air Time (seconds)",t:"unreal"},
  Uin1:{n:"Damage",t:"unreal"},
  Uin2:{n:"Duration",t:"unreal"},
  Uin3:{n:"Impact Delay",t:"unreal"},
  Uin4:{n:"Summoned Unit",t:"unitCode"},
  Uls1:{n:"Number of Swarm Units",t:"int"},
  Uls2:{n:"Unit Release Interval (seconds)",t:"unreal"},
  Uls3:{n:"Max Swarm Units Per Target",t:"int"},
  Uls4:{n:"Damage Return Factor",t:"unreal"},
  Uls5:{n:"Damage Return Threshold",t:"unreal"},
  Ulsu:{n:"Swarm Unit Type",t:"unitCode"},
  Usl1:{n:"Stun Duration",t:"unreal"},
  Uts1:{n:"Returned Damage Factor",t:"unreal"},
  Uts2:{n:"Received Damage Factor",t:"unreal"},
  Uts3:{n:"Defense Bonus",t:"unreal"},
  War1:{n:"Chance to Stomp (%)",t:"unreal"},
  War2:{n:"Damage Dealt",t:"unreal"},
  War3:{n:"Full Damage Radius",t:"unreal"},
  War4:{n:"Half Damage Radius",t:"unreal"},
  Wha1:{n:"Lumber per Interval",t:"unreal"},
  Wha2:{n:"Intervals Before Changing Trees",t:"int"},
  Wha3:{n:"Art Attachment Height",t:"unreal"},
  Wrp1:{n:"Teleport Area Width",t:"unreal"},
  Wrp2:{n:"Teleport Area Height",t:"unreal"},
  Wrs1:{n:"Damage",t:"unreal"},
  Wrs2:{n:"Terrain Deformation Amplitude",t:"unreal"},
  Wrs3:{n:"Terrain Deformation Duration (ms)",t:"int"},
  // -- Buffs --
  fart:{n:"Icon",t:"icon",c:"art"},
  feat:{n:"Effect",t:"modelList",c:"art"},
  feff:{n:"Is an Effect",t:"bool",c:"stats"},
  fefl:{n:"Effect Sound (Looping)",t:"soundLabel",c:"sound"},
  fefs:{n:"Effect Sound",t:"soundLabel",c:"sound"},
  feft:{n:"Effect Attachment Point",t:"stringList",c:"art"},
  flig:{n:"Lightning",t:"lightningEffect",c:"art"},
  fmac:{n:"Missile Arc",t:"unreal",c:"art"},
  fmat:{n:"Missile Art",t:"modelList",c:"art"},
  fmho:{n:"Missile Homing Enabled",t:"bool",c:"art"},
  fmsp:{n:"Missile Speed",t:"int",c:"art"},
  fnam:{n:"Name (Editor Only)",t:"string",c:"text"},
  fnsf:{n:"Editor Suffix",t:"string",c:"text"},
  frac:{n:"Race",t:"unitRace",c:"stats"},
  fsat:{n:"Special",t:"modelList",c:"art"},
  fspd:{n:"Required Spell Detail",t:"spellDetail",c:"art"},
  fspt:{n:"Special Attachment Point",t:"stringList",c:"art"},
  fta0:{n:"Target Attachment Point 1",t:"stringList",c:"art"},
  fta1:{n:"Target Attachment Point 2",t:"stringList",c:"art"},
  fta2:{n:"Target Attachment Point 3",t:"stringList",c:"art"},
  fta3:{n:"Target Attachment Point 4",t:"stringList",c:"art"},
  fta4:{n:"Target Attachment Point 5",t:"stringList",c:"art"},
  fta5:{n:"Target Attachment Point 6",t:"stringList",c:"art"},
  ftac:{n:"Target Attachments",t:"int",c:"art"},
  ftat:{n:"Target",t:"modelList",c:"art"},
  ftip:{n:"Tooltip",t:"string",c:"text"},
  fube:{n:"Tooltip - Extended",t:"string",c:"text"},
  // -- Destructables --
  barm:{n:"Armor Type",t:"armorType",c:"combat"},
  bbut:{n:"Build Time",t:"int",c:"stats"},
  bcat:{n:"Category",t:"destructableCategory",c:"editor"},
  bclh:{n:"Cliff Height",t:"int",c:"pathing"},
  bcpd:{n:"Show Dead Version in Palette",t:"bool",c:"editor"},
  bcpr:{n:"Can Place Random Scale",t:"bool",c:"editor"},
  bdsn:{n:"Death",t:"soundLabel",c:"sound"},
  bfil:{n:"Model File",t:"model",c:"art"},
  bflh:{n:"Fly-Over Height",t:"unreal",c:"art"},
  bflo:{n:"Fat Line of Sight",t:"bool",c:"art"},
  bfra:{n:"Fog Radius",t:"unreal",c:"art"},
  bfvi:{n:"Fog Visibility",t:"bool",c:"art"},
  bfxr:{n:"Fixed Rotation",t:"unreal",c:"art"},
  bgpm:{n:"Model File - Portrait",t:"model",c:"art"},
  bgsc:{n:"Selection Size - Game",t:"real",c:"art"},
  bgse:{n:"Selectable In Game",t:"bool",c:"art"},
  bhps:{n:"Hit Points",t:"unreal",c:"stats"},
  blit:{n:"Model File - Has Lightweight Model",t:"bool",c:"art"},
  bmap:{n:"Maximum Pitch Angle (degrees)",t:"unreal",c:"art"},
  bmar:{n:"Max Roll Angle (degrees)",t:"unreal",c:"art"},
  bmas:{n:"Maximum Scale",t:"unreal",c:"editor"},
  bmis:{n:"Minimum Scale",t:"unreal",c:"editor"},
  bmmb:{n:"Minimap Color 3 (Blue)",t:"int",c:"art"},
  bmmg:{n:"Minimap Color 2 (Green)",t:"int",c:"art"},
  bmmr:{n:"Minimap Color 1 (Red)",t:"int",c:"art"},
  bnam:{n:"Name",t:"string",c:"text"},
  boch:{n:"Occlusion Height",t:"unreal",c:"art"},
  bonc:{n:"Placeable on Cliffs",t:"bool",c:"editor"},
  bonw:{n:"Placeable on Water",t:"bool",c:"editor"},
  bptd:{n:"Pathing Texture (Dead)",t:"pathingTexture",c:"pathing"},
  bptx:{n:"Pathing Texture",t:"pathingTexture",c:"pathing"},
  brad:{n:"Elevation Sample Radius",t:"unreal",c:"art"},
  breg:{n:"Repair Gold Cost",t:"int",c:"stats"},
  brel:{n:"Repair Lumber Cost",t:"int",c:"stats"},
  bret:{n:"Repair Time",t:"int",c:"stats"},
  bsel:{n:"Selection Size - Editor",t:"unreal",c:"art"},
  bshd:{n:"Shadow",t:"shadowTexture",c:"art"},
  bsmm:{n:"Minimap - Show",t:"bool",c:"art"},
  bsuf:{n:"Editor Suffix",t:"string",c:"text"},
  btar:{n:"Targeted As",t:"targetList",c:"combat"},
  btil:{n:"Tilesets",t:"tilesetList",c:"editor"},
  btsp:{n:"Has Tileset Specific Data",t:"bool",c:"editor"},
  btxf:{n:"Replaceable Texture File",t:"texture",c:"art"},
  btxi:{n:"Replaceable Texture ID",t:"int",c:"art"},
  buch:{n:"Show Helper Object for Selection",t:"bool",c:"editor"},
  bumm:{n:"Minimap - Use Custom Color",t:"bool",c:"art"},
  busr:{n:"On User-Specified List",t:"bool",c:"editor"},
  bvar:{n:"Model File - Variations",t:"int",c:"art"},
  bvcb:{n:"Tinting Color 3 (Blue)",t:"int",c:"art"},
  bvcg:{n:"Tinting Color 2 (Green)",t:"int",c:"art"},
  bvcr:{n:"Tinting Color 1 (Red)",t:"int",c:"art"},
  bwal:{n:"Is Walkable",t:"bool",c:"pathing"},
  // -- Doodads --
  danf:{n:"Animate in Fog",t:"bool",c:"art"},
  dcat:{n:"Category",t:"doodadCategory",c:"editor"},
  dcpr:{n:"Can Place Random Scale",t:"bool",c:"editor"},
  ddes:{n:"Default Scale",t:"unreal",c:"art"},
  dfil:{n:"Model File",t:"model",c:"art"},
  dflt:{n:"Floats",t:"bool",c:"art"},
  dfxr:{n:"Fixed Rotation",t:"unreal",c:"art"},
  dimc:{n:"Ignore Model Clicks",t:"bool",c:"editor"},
  dmap:{n:"Maximum Pitch Angle (degrees)",t:"unreal",c:"art"},
  dmar:{n:"Max Roll Angle (degrees)",t:"unreal",c:"art"},
  dmas:{n:"Maximum Scale",t:"unreal",c:"editor"},
  dmis:{n:"Minimum Scale",t:"unreal",c:"editor"},
  dmmb:{n:"Minimap Color 3 (Blue)",t:"int",c:"art"},
  dmmg:{n:"Minimap Color 2 (Green)",t:"int",c:"art"},
  dmmr:{n:"Minimap Color 1 (Red)",t:"int",c:"art"},
  dnam:{n:"Name",t:"string",c:"text"},
  donc:{n:"Placeable on Cliffs",t:"bool",c:"editor"},
  donw:{n:"Placeable on Water",t:"bool",c:"editor"},
  dptx:{n:"Pathing Texture",t:"pathingTexture",c:"pathing"},
  dsel:{n:"Selection Size",t:"unreal",c:"art"},
  dshd:{n:"Has a Shadow",t:"bool",c:"art"},
  dshf:{n:"Show in Fog",t:"bool",c:"art"},
  dsmm:{n:"Minimap - Show",t:"bool",c:"art"},
  dsnd:{n:"Looping Sound",t:"soundLabel",c:"sound"},
  dtil:{n:"Tilesets",t:"tilesetList",c:"editor"},
  dtsp:{n:"Has Tileset Specific Data",t:"bool",c:"editor"},
  duch:{n:"Use Click Helper",t:"bool",c:"editor"},
  dumc:{n:"Minimap - Use Custom Color",t:"bool",c:"art"},
  dusr:{n:"On User-Specified List",t:"bool",c:"editor"},
  dvar:{n:"Variations",t:"int",c:"art"},
  dvb1:{n:"Tinting Color 3 (Blue)",t:"int",c:"art"},
  dvg1:{n:"Tinting Color 2 (Green)",t:"int",c:"art"},
  dvis:{n:"Visibility Radius",t:"unreal",c:"art"},
  dvr1:{n:"Tinting Color 1 (Red)",t:"int",c:"art"},
  dwlk:{n:"Walkable",t:"bool",c:"pathing"},
  // -- Upgrades --
  gar1:{n:"Icon",t:"icon",c:"art"},
  gba1:{n:"Effect 1 - Base",t:"unreal",c:"data"},
  gba2:{n:"Effect 2 - Base",t:"unreal",c:"data"},
  gba3:{n:"Effect 3 - Base",t:"unreal",c:"data"},
  gba4:{n:"Effect 4 - Base",t:"unreal",c:"data"},
  gbpx:{n:"Button Position (X)",t:"int",c:"art"},
  gbpy:{n:"Button Position (Y)",t:"int",c:"art"},
  gcls:{n:"Class",t:"upgradeClass",c:"stats"},
  gco1:{n:"Effect 1 - Ability Affected",t:"string",c:"data"},
  gco2:{n:"Effect 2 - Ability Affected",t:"string",c:"data"},
  gco3:{n:"Effect 3 - Ability Affected",t:"string",c:"data"},
  gco4:{n:"Effect 4 - Ability Affected",t:"string",c:"data"},
  gef1:{n:"Effect 1",t:"upgradeEffect",c:"data"},
  gef2:{n:"Effect 2",t:"upgradeEffect",c:"data"},
  gef3:{n:"Effect 3",t:"upgradeEffect",c:"data"},
  gef4:{n:"Effect 4",t:"upgradeEffect",c:"data"},
  gglb:{n:"Gold Base",t:"int",c:"stats"},
  gglm:{n:"Gold Increment",t:"int",c:"stats"},
  ghk1:{n:"Hotkey",t:"char",c:"text"},
  ginh:{n:"Transfer with Unit Ownership",t:"bool",c:"stats"},
  glmb:{n:"Lumber Base",t:"int",c:"stats"},
  glmm:{n:"Lumber Increment",t:"int",c:"stats"},
  glob:{n:"Applies to All Units",t:"bool",c:"stats"},
  glvl:{n:"Levels",t:"int",c:"stats"},
  gmo1:{n:"Effect 1 - Increment",t:"unreal",c:"data"},
  gmo2:{n:"Effect 2 - Increment",t:"unreal",c:"data"},
  gmo3:{n:"Effect 3 - Increment",t:"unreal",c:"data"},
  gmo4:{n:"Effect 4 - Increment",t:"unreal",c:"data"},
  gnam:{n:"Name",t:"string",c:"text"},
  gnsf:{n:"Editor Suffix",t:"string",c:"text"},
  grac:{n:"Race",t:"unitRace",c:"stats"},
  greq:{n:"Requirements",t:"techList",c:"techtree"},
  grqc:{n:"Requirements - Levels",t:"intList",c:"techtree"},
  gtib:{n:"Time Base",t:"int",c:"stats"},
  gtim:{n:"Time Increment",t:"int",c:"stats"},
  gtp1:{n:"Tooltip",t:"string",c:"text"},
  gub1:{n:"Tooltip - Extended",t:"string",c:"text"},
};
