export const unitCodes = {
    nvk2: 'Child',
    nvlk: 'Child',
    nvl2: 'Villager',
    nvil: 'Villager',
    nvlw: 'Villager',
    nahy: 'Ancient Hydra',
    nsqa: 'Ancient Sasquatch',
    nwna: 'Ancient Wendigo',
    nwiz: 'Apprentice Wizard',
    nane: 'Arachnathid Earth-borer',
    nass: 'Assassin',
    nban: 'Bandit',
    nbld: 'Bandit Lord',
    nanm: 'Barbed Arachnathid',
    nanb: 'Barbed Arachnathid',
    narg: 'Battle Golem',
    ngz1: 'Bear',
    nelb: 'Berserk Elemental',
    nowk: 'Berserk Wildkin',
    nbwm: 'Black Dragon',
    nbdr: 'Black Dragon Whelp',
    nbdk: 'Black Drake',
    nspb: 'Black Spider',
    nfgb: 'Bloodfiend',
    nadr: 'Blue Dragon',
    nadw: 'Blue Dragon Whelp',
    nbda: 'Blue Dragonspawn Apprentice',
    nbdm: 'Blue Dragonspawn Meddler',
    nbdo: 'Blue Dragonspawn Overseer',
    nbds: 'Blue Dragonspawn Sorcerer',
    nbdw: 'Blue Dragonspawn Warrior',
    nadk: 'Blue Drake',
    nbrg: 'Brigand',
    nbzd: 'Bronze Dragon',
    nbzw: 'Bronze Dragon Whelp',
    nbzk: 'Bronze Drake',
    nsbm: 'Brood Mother',
    nskf: 'Burning Archer',
    nbnb: 'Burrowed Barbed Arachnathid',
    ncea: 'Centaur Archer',
    ncer: 'Centaur Drudge',
    ncim: 'Centaur Impaler',
    ncnk: 'Centaur Khan',
    ncen: 'Centaur Outrunner',
    ncks: 'Centaur Sorcerer',
    nenc: 'Corrupted Treant',
    nanc: 'Crystal Arachnathid',
    ndmu: 'Dalaran Mutant',
    ndrj: 'Dalaran Reject',
    ndtr: 'Dark Troll',
    ndtb: 'Dark Troll Berserker',
    ndth: 'Dark Troll High Priest',
    ndtp: 'Dark Troll Shadow Priest',
    ndtt: 'Dark Troll Trapper',
    ndtw: 'Dark Troll Warlord',
    nwzd: 'Dark Wizard',
    nrvd: 'Death Revenant',
    nhdc: 'Deceiver',
    nlrv: 'Deeplord Revenant',
    nwwd: 'Dire Frost Wolf',
    nmdr: 'Dire Mammoth',
    nwld: 'Dire Wolf',
    ndrd: 'Draenei Darkslayer',
    ndrm: 'Draenei Disciple',
    ndrf: 'Draenei Guardian',
    ndrh: 'Draenei Harbinger',
    ndrp: 'Draenei Protector',
    ndrs: 'Draenei Seer',
    ndrw: 'Draenei Watcher',
    ntrd: 'Dragon Turtle',
    npn3: 'Earth',
    npn6: 'Earth',
    nehy: 'Elder Hydra',
    njga: 'Elder Jungle Stalker',
    nsqe: 'Elder Sasquatch',
    nvde: 'Elder Voidwalker',
    nwnr: 'Elder Wendigo',
    nenf: 'Enforcer',
    nele: 'Enraged Elemental',
    njgb: 'Enraged Jungle Stalker',
    nowe: 'Enraged Wildkin',
    nerd: 'Eredar Diabolist',
    ners: 'Eredar Sorcerer',
    nerw: 'Eredar Warlock',
    nfod: 'Faceless One Deathbringer',
    nfot: 'Faceless One Terror',
    nfor: 'Faceless One Trickster',
    nhfp: 'Fallen Priest',
    npfl: 'Fel Beast',
    npfm: 'Fel Ravager',
    nfgu: 'Felguard',
    npn1: 'Fire',
    npn4: 'Fire',
    nrvf: 'Fire Revenant',
    nspg: 'Forest Spider',
    nftr: 'Forest Troll',
    nftb: 'Forest Troll Berserker',
    nfsh: 'Forest Troll High Priest',
    nfsp: 'Forest Troll Shadow Priest',
    nftt: 'Forest Troll Trapper',
    nftk: 'Forest Troll Warlord',
    nrvs: 'Frost Revenant',
    nwwf: 'Frost Wolf',
    nfrl: 'Furbolg',
    nfrg: 'Furbolg Champion',
    nfre: 'Furbolg Elder Shaman',
    nfrs: 'Furbolg Shaman',
    nfrb: 'Furbolg Tracker',
    nfra: 'Furbolg Ursa Warrior',
    ntrg: 'Gargantuan Sea Turtle',
    ngh1: 'Ghost',
    nwwg: 'Giant Frost Wolf',
    nplg: 'Giant Polar Bear',
    ntrt: 'Giant Sea Turtle',
    nskg: 'Giant Skeleton Warrior',
    nsgt: 'Giant Spider',
    nwlg: 'Giant Wolf',
    ngno: 'Gnoll',
    ngns: 'Gnoll Assassin',
    ngnb: 'Gnoll Brute',
    ngnv: 'Gnoll Overseer',
    ngna: 'Gnoll Poacher',
    ngnw: 'Gnoll Warden',
    ngsp: 'Goblin Sapper',
    ngir: 'Goblin Shredder',
    nzep: 'Goblin Zeppelin',
    nggr: 'Granite Golem',
    nvdg: 'Greater Voidwalker',
    ngrd: 'Green Dragon',
    ngrw: 'Green Dragon Whelp',
    ngdk: 'Green Drake',
    nhrq: 'Harpy Queen',
    nhrr: 'Harpy Rogue',
    nhar: 'Harpy Scout',
    nhrh: 'Harpy Storm-hag',
    nhrw: 'Harpy Windwitch',
    nhhr: 'Heretic',
    nhyd: 'Hydra',
    nhyh: 'Hydra Hatchling',
    nrvi: 'Ice Revenant',
    nitr: 'Ice Troll',
    nits: 'Ice Troll Berserker',
    nith: 'Ice Troll High Priest',
    nitp: 'Ice Troll Priest',
    nitt: 'Ice Troll Trapper',
    nitw: 'Ice Troll Warlord',
    nmit: 'Icetusk Mammoth',
    ninc: 'Infernal Contraption',
    nina: 'Infernal Juggernaut',
    ninm: 'Infernal Machine',
    njg1: 'Jungle Stalker',
    nkob: 'Kobold',
    nkog: 'Kobold Geomancer',
    nkol: 'Kobold Taskmaster',
    nkot: 'Kobold Tunneler',
    nvdl: 'Lesser Voidwalker',
    nltl: 'Lightning Lizard',
    nrvl: 'Lightning Revenant',
    nmgd: 'Magnataur Destroyer',
    nmgr: 'Magnataur Reaver',
    nmgw: 'Magnataur Warrior',
    ndqp: 'Maiden of Pain',
    nlds: 'Makrura Deepseer',
    nlpd: 'Makrura Pooldweller',
    nlpr: 'Makrura Prawn',
    nlsn: 'Makrura Snapper',
    nlkl: 'Makrura Tidal Lord',
    nltc: 'Makrura Tidecaller',
    nmam: 'Mammoth',
    nlur: 'Monster Lure',
    ngrk: 'Mud Golem',
    nmfs: 'Murloc Flesheater',
    nmrr: 'Murloc Huntsman',
    nmmu: 'Murloc Mutant',
    nmrm: 'Murloc Nightcrawler',
    nmpg: 'Murloc Plaguebearer',
    nmrl: 'Murloc Tiderunner',
    nnwq: 'Nerubian Queen',
    nnwr: 'Nerubian Seer',
    nnws: 'Nerubian Spider Lord',
    nnwa: 'Nerubian Warrior',
    nnwl: 'Nerubian Webspinner',
    nndr: 'Nether Dragon',
    nnht: 'Nether Dragon Hatchling',
    nndk: 'Nether Drake',
    nogl: 'Ogre Lord',
    nomg: 'Ogre Magi',
    nogm: 'Ogre Mauler',
    nogr: 'Ogre Warrior',
    nfov: 'Overlord',
    nano: 'Overlord Arachnathid',
    nfrp: 'Pandaren',
    nepl: 'Plague Treant',
    nenp: 'Poison Treant',
    nplb: 'Polar Bear',
    nfpl: 'Polar Furbolg',
    nfpc: 'Polar Furbolg Champion',
    nfpe: 'Polar Furbolg Elder Shaman',
    nfps: 'Polar Furbolg Shaman',
    nfpt: 'Polar Furbolg Tracker',
    nfpu: 'Polar Furbolg Ursa Warrior',
    ndqs: 'Queen of Suffering',
    nrzt: 'Quillboar',
    nqbh: 'Quillboar Hunter',
    ngz2: 'Raging Bear',
    nrzb: 'Razormane Brute',
    nrzg: 'Razormane Chieftain',
    nrzm: 'Razormane Medicine Man',
    nrzs: 'Razormane Scout',
    nrwm: 'Red Dragon',
    nrdk: 'Red Dragon Whelp',
    nrdr: 'Red Drake',
    nrel: 'Reef Elemental',
    nwzg: 'Renegade Wizard',
    ndrv: 'Revenant of the Depths',
    nsrv: 'Revenant of the Seas',
    ntrv: 'Revenant of the Tides',
    ngst: 'Rock Golem',
    nrog: 'Rogue',
    nwzr: 'Rogue Wizard',
    nslr: 'Salamander',
    nslh: 'Salamander Hatchling',
    nsll: 'Salamander Lord',
    nslv: 'Salamander Vizier',
    nsqt: 'Sasquatch',
    nsqo: 'Sasquatch Oracle',
    nsty: 'Satyr',
    nsth: 'Satyr Hellcaller',
    nsts: 'Satyr Shadowdancer',
    nstl: 'Satyr Soulstealer',
    nsat: 'Satyr Trickster',
    nsel: 'Sea Elemental',
    nsgn: 'Sea Giant',
    nsgb: 'Sea Giant Behemoth',
    nsgh: 'Sea Giant Hunter',
    ntrs: 'Sea Turtle',
    ntrh: 'Sea Turtle Hatchling',
    nsgg: 'Siege Golem',
    nskm: 'Skeletal Marksman',
    nsko: 'Skeletal Orc',
    nsoc: 'Skeletal Orc Champion',
    nsog: 'Skeletal Orc Grunt',
    nska: 'Skeleton Archer',
    nsca: 'Skeleton Archer',
    nske: 'Skeleton Warrior',
    nsce: 'Skeleton Warrior',
    nslf: 'Sludge Flinger',
    nslm: 'Sludge Minion',
    nsln: 'Sludge Monstrosity',
    nspr: 'Spider',
    nsc3: 'Spider Crab Behemoth',
    nsc2: 'Spider Crab Limbripper',
    nscb: 'Spider Crab Shorecrawler',
    nspd: 'Spiderling',
    ngz3: 'Spirit Bear',
    nspp: 'Spirit Pig',
    nssp: 'Spitting Spider',
    npn2: 'Storm',
    npn5: 'Storm',
    nstw: 'Storm Wyrm',
    nsra: 'Stormreaver Apprentice',
    nsrh: 'Stormreaver Hermit',
    nsrn: 'Stormreaver Necrolyte',
    nsrw: 'Stormreaver Warlock',
    ndqn: 'Succubus',
    nlps: 'Summoned Prawn',
    nfgt: 'Tentacle',
    nthl: 'Thunder Lizard',
    nwlt: 'Timber Wolf',
    nbot: 'Transport Ship',
    ntkc: 'Tuskarr Chieftain',
    ntkf: 'Tuskarr Fighter',
    ntkh: 'Tuskarr Healer',
    ntks: 'Tuskarr Sorcerer',
    ntka: 'Tuskarr Spearman',
    ntkt: 'Tuskarr Trapper',
    ntkw: 'Tuskarr Warrior',
    nubk: 'Unbroken Darkhunter',
    nubw: 'Unbroken Darkweaver',
    nubr: 'Unbroken Rager',
    ndqt: 'Vile Temptress',
    ndqv: 'Vile Tormentor',
    nvdw: 'Voidwalker',
    nwrg: 'War Golem',
    nanw: 'Warrior Arachnathid',
    ncfs: 'Watery Minion',
    ntws: 'Watery Minion',
    nsns: 'Watery Minion',
    nwen: 'Wendigo',
    nwns: 'Wendigo Shaman',
    nowb: 'Wildkin',
    ngh2: 'Wraith',
    Nalm: 'Alchemist',
    Nal2: 'Alchemist',
    Nal3: 'Alchemist',
    Nalc: 'Alchemist',
    Nbst: 'Beastmaster',
    Nbrn: 'Dark Ranger',
    Nfir: 'Firelord',
    Nngs: 'Naga Sea Witch',
    Npbm: 'Pandaren Brewmaster',
    Nplh: 'Pit Lord',
    Nrob: 'Tinker',
    Ntin: 'Tinker',
    nfgo: 'Forgotten One',
    ncat: 'Draenei Demolisher',
    ndrl: 'Draenei Laborer',
    ndrt: 'Draenei Stalker',
    ndrn: 'Draenei Vindicator',
    nfgl: 'Flesh Golem',
    nglm: 'Goblin Land Mine',
    nsw3: 'Greater Spirit Beast',
    nsw1: 'Lesser Spirit Beast',
    ndsa: 'Salamander',
    nsw2: 'Spirit Beast',
    nogn: 'Stonemaul Magi',
    nogo: 'Stonemaul Ogre',
    noga: 'Stonemaul Warchief',
    Naka: 'Elder Sage',
    nalb: 'Albatross',
    nech: 'Chicken',
    ncrb: 'Crab',
    ndog: 'Dog',
    ndwm: 'Dune Worm',
    nfbr: 'Fel Boar',
    nshf: 'Flying Sheep',
    nfro: 'Frog',
    nhmc: 'Hermit Crab',
    npnw: 'Penguin',
    npng: 'Penguin',
    npig: 'Pig',
    necr: 'Rabbit',
    nrac: 'Raccoon',
    nrat: 'Rat',
    nsea: 'Seal',
    nshe: 'Sheep',
    nshw: 'Sheep',
    nsha: 'Sheep',
    nskk: 'Skink',
    nsno: 'Snowy Owl',
    nder: 'Stag',
    nvul: 'Vulture',
    nbal: 'Doom Guard',
    nba2: 'Doom Guard',
    nfel: 'Fel Stalker',
    ninf: 'Infernal',
    ncmw: 'Corrupted Moon Well',
    nqb4: 'Berserk Quilbeast',
    ncg3: 'Clockwerk Goblin',
    ncg1: 'Clockwerk Goblin',
    ncgb: 'Clockwerk Goblin',
    ncg2: 'Clockwerk Goblin',
    ndr2: 'Dark Minion',
    nqb2: 'Dire Quilbeast',
    ndr3: 'Greater Dark Minion',
    nwe1: 'Hawk',
    zshv: 'Kobold Shoveler',
    nlv1: 'Lava Spawn',
    nlv3: 'Lava Spawn',
    nlv2: 'Lava Spawn',
    ndr1: 'Lesser Dark Minion',
    ngza: 'Misha',
    ngzc: 'Misha',
    ngz4: 'Misha',
    ngzd: 'Misha',
    nfac: 'Pocket Factory',
    nfa2: 'Pocket Factory',
    nfa1: 'Pocket Factory',
    nqb1: 'Quilbeast',
    nqb3: 'Raging Quilbeast',
    nwe3: 'Spirit Hawk',
    nwe2: 'Thunder Hawk',
    ntor: 'Tornado',
    ndrk: 'Black Dragon Roost',
    ndru: 'Blue Dragon Roost',
    ndrz: 'Bronze Dragon Roost',
    ncnt: 'Centaur Tent',
    nct2: 'Centaur Tent',
    nct1: 'Centaur Tent',
    ndh1: 'Draenei Hut',
    ndh0: 'Draenei Hut',
    nfh0: 'Forest Troll Hut',
    nfh1: 'Forest Troll Hut',
    nfoh: 'Fountain of Health',
    nmoo: 'Fountain of Mana',
    nfr2: 'Furbolg Hut',
    nfr1: 'Furbolg Hut',
    ngnh: 'Gnoll Hut',
    ngt2: 'Gnoll Hut',
    ngad: 'Goblin Laboratory',
    ngme: 'Goblin Merchant',
    nshp: 'Goblin Shipyard',
    ngol: 'Gold Mine',
    ndrg: 'Green Dragon Roost',
    nhns: 'Harpy Nest',
    nth1: 'Ice Troll Hut',
    nth0: 'Ice Troll Hut',
    nmrk: 'Marketplace',
    nmer: 'Mercenary Camp',
    nmrf: 'Mercenary Camp',
    nmr6: 'Mercenary Camp',
    nmrc: 'Mercenary Camp',
    nmrd: 'Mercenary Camp',
    nmr3: 'Mercenary Camp',
    nmrb: 'Mercenary Camp',
    nmr4: 'Mercenary Camp',
    nmra: 'Mercenary Camp',
    nmre: 'Mercenary Camp',
    nmr8: 'Mercenary Camp',
    nmr9: 'Mercenary Camp',
    nmr2: 'Mercenary Camp',
    nmr7: 'Mercenary Camp',
    nmr5: 'Mercenary Camp',
    nmr0: 'Mercenary Camp',
    nmh1: 'Murloc Hut',
    nmh0: 'Murloc Hut',
    nnzg: 'Nerubian Ziggurat',
    ndro: 'Nether Dragon Roost',
    ndrr: 'Red Dragon Roost',
    ntt2: 'Tauren Tent',
    ntnt: 'Tauren Tent',
    ntav: 'Tavern',
    ntn2: 'Tent',
    nten: 'Tent',
    nwgt: 'Way Gate',
    zhyd: 'Hydralisk',
    zmar: 'Marine',
    zjug: 'Orc Juggernaught',
    nbsp: 'Ship',
    zcso: 'Space Fel Orc',
    zzrg: 'Zergling',
    ncp2: 'Circle of Power',
    ncop: 'Circle of Power',
    ncp3: 'Circle of Power',
    ncbe: 'City Building',
    ncbc: 'City Building',
    ncbd: 'City Building',
    ncbf: 'City Building',
    ncba: 'City Building',
    ncbb: 'City Building',
    ncb3: 'City Building',
    ncb4: 'City Building',
    ncb6: 'City Building',
    ncb0: 'City Building',
    ncb9: 'City Building',
    ncb7: 'City Building',
    ncb5: 'City Building',
    ncb1: 'City Building',
    ncb2: 'City Building',
    ncb8: 'City Building',
    ndke: 'Dimensional Gate',
    ndkw: 'Dimensional Gate',
    ndh3: 'Draenei Barracks',
    ndh2: 'Draenei Haven',
    nico: 'Icecrown Obelisk',
    nbsw: 'Resurrection Stone',
    nbse: 'Resurrection Stone',
    nzin: 'Zone Indicator',
    npgr: 'Power Generator',
    nwc1: 'Wyvern Cage',
    nwc2: 'Wyvern Cage',
    hdhw: 'Dragonhawk Rider',
    hgyr: 'Flying Machine',
    hfoo: 'Footman',
    hgry: 'Gryphon Rider',
    hkni: 'Knight',
    hmil: 'Militia',
    hmtm: 'Mortar Team',
    hpea: 'Peasant',
    hphx: 'Phoenix',
    hpxe: 'Phoenix Egg',
    hmpr: 'Priest',
    hrif: 'Rifleman',
    hmtt: 'Siege Engine',
    hrtt: 'Siege Engine',
    hsor: 'Sorceress',
    hspt: 'Spell Breaker',
    hwt2: 'Water Elemental',
    hwat: 'Water Elemental',
    hwt3: 'Water Elemental',
    Hamg: 'Archmage',
    Hblm: 'Blood Mage',
    Hmkg: 'Mountain King',
    Hpal: 'Paladin',
    halt: 'Altar of Kings',
    hars: 'Arcane Sanctum',
    hatw: 'Arcane Tower',
    hvlt: 'Arcane Vault',
    hbar: 'Barracks',
    hbla: 'Blacksmith',
    hctw: 'Cannon Tower',
    hcas: 'Castle',
    hhou: 'Farm',
    hgra: 'Gryphon Aviary',
    hgtw: 'Guard Tower',
    hkee: 'Keep',
    hlum: 'Lumber Mill',
    hwtw: 'Scout Tower',
    htow: 'Town Hall',
    harm: 'Workshop',
    nhea: 'Archer',
    nbee: 'Blood Elf Engineer',
    nbel: 'Blood Elf Lieutenant',
    hcth: 'Captain',
    nchp: 'Chaplain',
    nws1: 'Dragon Hawk',
    nemi: 'Emissary',
    nhem: 'High Elf',
    nhef: 'High Elf',
    hbsh: 'Human Battleship',
    hdes: 'Human Frigate',
    hbot: 'Human Transport Ship',
    nhym: 'Hydromancer',
    njks: 'Jailor Kassan',
    nmed: 'Medivh',
    nmdm: 'Medivh',
    hrdh: 'Pack Horse',
    hprt: 'Portal',
    hhdl: 'Riderless Horse',
    nser: 'Searinox',
    hhes: 'Swordsman',
    hbew: 'Wagon',
    nhew: 'Worker',
    Hant: 'Archmage',
    Hjai: 'Archmage',
    Hkal: 'Blood Mage',
    Hlgr: 'Dark Knight',
    Hgam: 'Ghostly Archmage',
    Hmbr: 'Mountain King',
    Hhkl: 'Paladin',
    Hpb1: 'Paladin',
    Hart: 'Paladin',
    Hdgo: 'Paladin',
    Harf: 'Paladin',
    Hmgd: 'Paladin',
    Hapm: 'Paladin',
    Hpb2: 'Paladin',
    Huth: 'Paladin',
    Hvwd: 'Ranger',
    nbt2: 'Advanced Boulder Tower',
    ndt2: 'Advanced Cold Tower',
    ntx2: 'Advanced Death Tower',
    net2: 'Advanced Energy Tower',
    nft2: 'Advanced Flame Tower',
    haro: 'Arcane Observatory',
    nbt1: 'Boulder Tower',
    ndt1: 'Cold Tower',
    ndgt: 'Dalaran Guard Tower',
    ntt1: 'Death Tower',
    negf: 'Earth-Fury Tower',
    net1: 'Energy Tower',
    nft1: 'Flame Tower',
    nfrt: 'Fruit Stand',
    ngwr: 'Grain Warehouse',
    nheb: 'High Elven Barracks',
    nef7: 'High Elven Farm',
    nef0: 'High Elven Farm',
    nef2: 'High Elven Farm',
    nef3: 'High Elven Farm',
    nef1: 'High Elven Farm',
    nef5: 'High Elven Farm',
    nef4: 'High Elven Farm',
    nefm: 'High Elven Farm',
    nef6: 'High Elven Farm',
    negt: 'High Elven Guard Tower',
    hshy: 'Human Shipyard',
    nitb: 'Icy Treasure Box',
    nmgv: 'Magic Vault',
    negm: 'Sky-Fury Tower',
    nwgs: 'Couatl',
    nhyc: 'Dragon Turtle',
    nmyr: 'Naga Myrmidon',
    nnrg: 'Naga Royal Guard',
    nnsw: 'Naga Siren',
    nsnp: 'Snap Dragon',
    nmys: 'Submerged Naga Myrmidon',
    nnrs: 'Submerged Naga Royal Guard',
    nsbs: 'Submerged Snap Dragon',
    nnsu: 'Summoner',
    Hvsh: 'Naga Sea Witch',
    nnad: 'Altar of the Depths',
    nnfm: 'Coral Bed',
    nnsa: 'Shrine of Azshara',
    nnsg: 'Spawning Grounds',
    nntt: 'Temple of Tides',
    nntg: 'Tidal Guardian',
    earc: 'Archer',
    espv: 'Avatar of Vengeance',
    echm: 'Chimaera',
    edoc: 'Druid of the Claw',
    edcm: 'Druid of the Claw',
    edtm: 'Druid of the Talon',
    edot: 'Druid of the Talon',
    edry: 'Dryad',
    efdr: 'Faerie Dragon',
    ebal: 'Glaive Thrower',
    ehip: 'Hippogryph',
    ehpr: 'Hippogryph Rider',
    esen: 'Huntress',
    emtg: 'Mountain Giant',
    now2: 'Owl Scout',
    now3: 'Owl Scout',
    nowl: 'Owl Scout',
    even: 'Spirit of Vengeance',
    efon: 'Treant',
    ewsp: 'Wisp',
    Edmm: 'Demon Hunter',
    Edem: 'Demon Hunter',
    Ekee: 'Keeper of the Grove',
    Emoo: 'Priestess of the Moon',
    Ewar: 'Warden',
    eate: 'Altar of Elders',
    etrp: 'Ancient Protector',
    eaoe: 'Ancient of Lore',
    eaom: 'Ancient of War',
    eaow: 'Ancient of Wind',
    eden: 'Ancient of Wonders',
    edos: 'Chimaera Roost',
    egol: 'Entangled Gold Mine',
    emow: 'Moon Well',
    etoa: 'Tree of Ages',
    etoe: 'Tree of Eternity',
    etol: 'Tree of Life',
    ensh: 'Naisha',
    ebsh: 'Night Elf Battleship',
    edes: 'Night Elf Frigate',
    enec: 'Night Elf Runner',
    etrs: 'Night Elf Transport Ship',
    eilw: 'Prison Wagon',
    nwat: 'Sentry',
    eshd: 'Shandris',
    nthr: 'Tharifas',
    nssn: 'Warden',
    Ecen: 'Demigod',
    Eidm: 'Demon Hunter',
    Eevi: 'Demon Hunter',
    Eevm: 'Demon Hunter',
    Eilm: 'Demon Hunter',
    Eill: 'Demon Hunter',
    Emfr: 'Keeper of the Grove',
    Efur: 'Keeper of the Grove',
    Ekgg: 'Keeper of the Grove',
    Emns: 'Keeper of the Grove',
    Etyr: 'Priestess of the Moon',
    Ewrd: 'Warden',
    nbwd: 'Barrow Den',
    ncap: 'Corrupted Ancient Protector',
    ncaw: 'Corrupted Ancient of War',
    ncta: 'Corrupted Tree of Ages',
    ncte: 'Corrupted Tree of Eternity',
    nctl: 'Corrupted Tree of Life',
    ngob: 'Enchanted Gemstone Obelisk',
    nfnp: 'Fountain of Power',
    nhcn: 'Horn of Cenarius Pedestal',
    nvr1: 'Night Elf Fishing Village',
    nfv3: 'Night Elf Fishing Village',
    nfv4: 'Night Elf Fishing Village',
    nfv0: 'Night Elf Fishing Village',
    nfv2: 'Night Elf Fishing Village',
    nvr0: 'Night Elf Fishing Village',
    nvr2: 'Night Elf Fishing Village',
    nfv1: 'Night Elf Fishing Village',
    eshy: 'Night Elf Shipyard',
    ocat: 'Demolisher',
    osw2: 'Dire Wolf',
    ogru: 'Grunt',
    ohwd: 'Healing Ward',
    okod: 'Kodo Beast',
    opeo: 'Peon',
    orai: 'Raider',
    oeye: 'Sentry Ward',
    osp2: 'Serpent Ward',
    osp3: 'Serpent Ward',
    osp1: 'Serpent Ward',
    osp4: 'Serpent Ward',
    osw3: 'Shadow Wolf',
    oshm: 'Shaman',
    ospw: 'Spirit Walker',
    ospm: 'Spirit Walker',
    osw1: 'Spirit Wolf',
    otot: 'Stasis Trap',
    otau: 'Tauren',
    otbr: 'Troll Batrider',
    otbk: 'Troll Berserker',
    ohun: 'Troll Headhunter',
    odoc: 'Troll Witch Doctor',
    nwad: 'Watcher Ward',
    owyv: 'Wind Rider',
    Obla: 'Blademaster',
    Ofar: 'Far Seer',
    Oshd: 'Shadow Hunter',
    Otch: 'Tauren Chieftain',
    oalt: 'Altar of Storms',
    obar: 'Barracks',
    obea: 'Beastiary',
    ofrt: 'Fortress',
    ogre: 'Great Hall',
    otrb: 'Orc Burrow',
    osld: 'Spirit Lodge',
    ostr: 'Stronghold',
    otto: 'Tauren Totem',
    ovln: 'Voodoo Lounge',
    ofor: 'War Mill',
    owtw: 'Watch Tower',
    negz: 'Engineer Gazlowe',
    nchg: 'Fel Orc Grunt',
    nckb: 'Fel Orc Kodo Beast',
    ncpn: 'Fel Orc Peon',
    nchr: 'Fel Orc Raider',
    nchw: 'Fel Orc Warlock',
    ngbl: 'Goblin Blaster',
    oosc: 'Kodo Beast',
    omtg: 'Mathog',
    nmsh: 'Misha',
    onzg: 'Nazgrel',
    odes: 'Orc Frigate',
    ojgn: 'Orc Juggernaught',
    obot: 'Orc Transport Ship',
    owar: 'Orc Warchief',
    nw2w: 'Orc Warlock',
    oswy: 'Spirit Wyvern',
    nspc: 'Support Column',
    ownr: 'Wyvern',
    Orex: 'Beastmaster',
    Ogrh: 'Blademaster',
    Nbbc: 'Blademaster',
    Opgh: 'Blademaster',
    Osam: 'Blademaster',
    Othr: 'Far Seer',
    Odrt: 'Far Seer',
    Nsjs: 'Pandaren Brewmaster',
    Orkn: 'Shadow Hunter',
    Ocbh: 'Tauren Chieftain',
    Ocb2: 'Tauren Chieftain',
    Otcc: 'Tauren Chieftain',
    Ogld: 'Warlock',
    ndfl: 'Defiled Fountain of Life',
    ndrb: 'Dragon Roost',
    ocbw: 'Fel Orc Burrow',
    nbfl: 'Fountain of Blood',
    oshy: 'Orc Shipyard',
    npgf: 'Pig Farm',
    uabo: 'Abomination',
    uaco: 'Acolyte',
    uban: 'Banshee',
    ucsB: 'Burrowed Carrion Beetle',
    ucsC: 'Burrowed Carrion Beetle',
    ucrm: 'Burrowed Crypt Fiend',
    ucs3: 'Carrion Beetle',
    ucs2: 'Carrion Beetle',
    ucs1: 'Carrion Beetle',
    ucry: 'Crypt Fiend',
    ubsp: 'Destroyer',
    uplg: 'Disease Cloud',
    ufro: 'Frost Wyrm',
    ugar: 'Gargoyle',
    ugho: 'Ghoul',
    uloc: 'Locust',
    umtw: 'Meat Wagon',
    unec: 'Necromancer',
    uobs: 'Obsidian Statue',
    ushd: 'Shade',
    uskm: 'Skeletal Mage',
    uske: 'Skeleton Warrior',
    ugrm: 'Stone Form Gargoyle',
    Ucrl: 'Crypt Lord',
    Udea: 'Death Knight',
    Udre: 'Dreadlord',
    Ulic: 'Lich',
    uaod: 'Altar of Darkness',
    unp2: 'Black Citadel',
    ubon: 'Boneyard',
    usep: 'Crypt',
    ugrv: 'Graveyard',
    unp1: 'Halls of the Dead',
    ugol: 'Haunted Gold Mine',
    unpl: 'Necropolis',
    uzg2: 'Nerubian Tower',
    usap: 'Sacrificial Pit',
    uslh: 'Slaughterhouse',
    uzg1: 'Spirit Tower',
    utod: 'Temple of the Damned',
    utom: 'Tomb of Relics',
    uzig: 'Ziggurat',
    uabc: 'Abomination',
    nzlc: 'Lich King',
    ubdd: 'Sapphiron',
    ubdr: 'Sapphiron',
    uarb: 'Sky Barge',
    uswb: 'Sylvanas Windrunner',
    uubs: 'Undead Battleship',
    udes: 'Undead Frigate',
    ubot: 'Undead Transport Ship',
    nzom: 'Zombie',
    Uanb: 'Crypt Lord',
    Usyl: 'Dark Ranger',
    Uear: 'Death Knight',
    Uvar: 'Dreadlord',
    Udth: 'Dreadlord',
    Utic: 'Dreadlord',
    Ubal: 'Dreadlord',
    Uvng: 'Dreadlord',
    Umal: 'Dreadlord',
    Uclc: 'Lich',
    Uktl: 'Lich',
    Npld: 'Pit Lord',
    Nman: 'Pit Lord',
    Nmag: 'Pit Lord',
    Nkjx: 'Warlock',
    Uwar: 'Warlock',
    Nklj: 'Warlock',
    nbsm: 'Book of Summoning Pedestal',
    ndmg: 'Demon Gate',
    nfrm: 'Frostmourne Pedestal',
    ngni: 'Infected Granary',
    nshr: 'Shrine',
    ushp: 'Undead Shipyard',
}